import { writeFileSync } from 'node:fs';
import { ISLAND_CAMPAIGNS } from '@/constants/island-campaigns/registry';
import { chapterBoards, mistLevelBoard } from '@/constants/island-campaigns/ladder';
import { budgetKey, solveBudget } from '@/features/encounter/budget';
import type { EncounterDefinition } from '@/types/encounter';

/**
 * The Resolve budget of every bundled board that is authored without one (the
 * friends' islands, read as ladders): searched once here, read at runtime.
 */
const boards: EncounterDefinition[] = [];
for (const campaign of ISLAND_CAMPAIGNS) {
  // Territory battles have no Resolve budget; only the older boards left are searched.
  if (mistLevelBoard(campaign).territory == null) boards.push(mistLevelBoard(campaign));
  for (const chapter of campaign.chapters) for (const mission of chapterBoards(campaign, chapter)) {
    if (!mission.rush && mission.encounter.resolve == null && mission.encounter.territory == null) boards.push(mission.encounter);
  }
}
const table: Record<string, ReturnType<typeof solveBudget>> = {};
for (const board of boards) table[budgetKey(board)] = solveBudget(board);
const body = Object.entries(table).sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`).join('\n');
writeFileSync('constants/encounters/budgets.generated.ts', `import type { EncounterSpawner } from '@/types/encounter';\n\n/** Generated by \`npm run encounters:budgets\`. Do not edit. */\nexport const ENCOUNTER_BUDGETS: Readonly<Record<string, { resolve: number; refill: EncounterSpawner | null }>> = {\n${body}\n};\n`);
console.log(`${Object.keys(table).length} budgets written`);
