import { writeFileSync } from 'node:fs';
import { ISLAND_CAMPAIGNS } from '@/constants/island-campaigns/registry';
import { templateEncounter } from '@/constants/island-campaigns/ladder';
import { encounterFromRestoration } from '@/features/encounter/adapt';
import { budgetKey, solveBudget } from '@/features/encounter/budget';
import type { EncounterDefinition } from '@/types/encounter';

/**
 * The Resolve budget of every bundled board that is authored without one (the
 * friends' islands, read as ladders): searched once here, read at runtime.
 */
const DIFFICULTY = ['calm', 'thick', 'thick', 'dark'] as const;
const boards: EncounterDefinition[] = [];
for (const campaign of ISLAND_CAMPAIGNS) for (const chapter of campaign.chapters) {
  if (chapter.missions?.length) { for (const mission of chapter.missions) if (!mission.rush && mission.encounter.resolve == null) boards.push(mission.encounter); continue; }
  if (chapter.restoration) { if (!chapter.restoration.rush) boards.push(encounterFromRestoration(chapter.restoration, campaign.campaignId, chapter.level, `katchimeras.mist-mission.${campaign.campaignId}.${chapter.level}.v1`, chapter.fallbackOrder.requirements, DIFFICULTY[chapter.level - 1])); continue; }
  boards.push(templateEncounter(campaign, chapter));
}
const table: Record<string, ReturnType<typeof solveBudget>> = {};
for (const board of boards) table[budgetKey(board)] = solveBudget(board);
const body = Object.entries(table).sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`).join('\n');
writeFileSync('constants/encounters/budgets.generated.ts', `import type { EncounterSpawner } from '@/types/encounter';\n\n/** Generated by \`npm run encounters:budgets\`. Do not edit. */\nexport const ENCOUNTER_BUDGETS: Readonly<Record<string, { resolve: number; refill: EncounterSpawner | null }>> = {\n${body}\n};\n`);
console.log(`${Object.keys(table).length} budgets written`);
