import React,{useEffect,useState} from 'react';
import './journey.css';
const characters=['mossprout','steppling','petalimp','baristabbit','feastle'];
const label=s=>s.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
async function api(route,body){const r=await fetch(`/api/characters/${route}`,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw new Error(v.error??v.issues?.join('\n'));return v;}
const inside=(path,prefix)=>path===prefix||path.startsWith(prefix+'/');
const at=(model,path)=>path.split('/').reduce((o,k)=>o?.[k],model);
export function CharacterStudio(){
  const [character,setCharacter]=useState('mossprout'),[catalog,setCatalog]=useState(null),[draft,setDraft]=useState(null),[section,setSection]=useState('chapter');
  const [status,setStatus]=useState('Loading character…'),[busy,setBusy]=useState(false),[issues,setIssues]=useState([]),[saved,setSaved]=useState([]),[load,setLoad]=useState(''),[query,setQuery]=useState('');
  const [conversation,setConversation]=useState(null),[nodeId,setNodeId]=useState(null),[reply,setReply]=useState(''),[choice,setChoice]=useState(null),[boards,setBoards]=useState([]);
  useEffect(()=>{let alive=true;setCatalog(null);setDraft(null);setLoad('');setIssues([]);setConversation(null);setBoards([]);setChoice(null);setQuery('');
    Promise.all([api(`${character}/source`),api(`${character}/drafts`)]).then(([c,s])=>{if(!alive)return;let stored;try{stored=JSON.parse(localStorage.getItem(`character-editor-${character}`));}catch{/* saved disk versions still work */}
      setCatalog(c);setDraft(stored?.character===character&&stored.edits&&stored.art?stored:c.draft);setSection(c.sections[0].path);setSaved(s.drafts);setStatus(`Editing ${label(character)}'s existing bundled content. Changes are drafts until integrated.`);
    }).catch(e=>alive&&setStatus(e.message));return()=>{alive=false;};},[character]);
  useEffect(()=>{if(draft)try{localStorage.setItem(`character-editor-${draft.character}`,JSON.stringify(draft));}catch{setStatus('Browser storage is full. Save a version to disk.');}},[draft]);
  async function run(task){if(busy)return;setBusy(true);try{await task();}catch(e){setStatus(e.message);}finally{setBusy(false);}}
  function change(next){setDraft(next);setIssues([]);setConversation(null);setBoards([]);setStatus('Draft changed · browser autosaved');}
  if(!catalog||!draft)return <div className="journey-loading" role="status">{status}</div>;
  const model=structuredClone(catalog.source);
  for(const [path,value]of Object.entries(draft.edits)){if(!catalog.fields.some(f=>f.path===path))continue;const p=path.split('/');const parent=p.slice(0,-1).reduce((o,k)=>o?.[k],model);if(parent)parent[p.at(-1)]=value;}
  const episode=section.startsWith('chapter/episodes/')?at(model,section):null;
  const linkedIndex=episode?.conversationId?model.conversations?.findIndex(c=>c.id===episode.conversationId):-1;
  const selectedFields=catalog.fields.filter(f=>(inside(f.path,section)&&!(section==='chapter'&&f.path.startsWith('chapter/episodes/')))||(linkedIndex>=0&&inside(f.path,`conversations/${linkedIndex}`)));
  const fields=selectedFields.filter(f=>`${f.path} ${draft.edits[f.path]??f.value}`.toLowerCase().includes(query.toLowerCase()));
  const selectedData=at(model,section),node=conversation?.nodes.find(n=>n.id===nodeId);
  const edit=(path,value)=>change({...draft,edits:{...draft.edits,[path]:value}});
  const previewChoices=Array.isArray(selectedData?.choices)?selectedData.choices:[];
  const chosen=previewChoices.find(c=>c.id===choice);
  function field(f){const value=draft.edits[f.path]??f.value;return <label className="field" key={f.path}><span>{label(f.label)} <small>{f.path}</small></span>
    {f.options?<select value={value} onChange={e=>edit(f.path,e.target.value)}>{f.options.map(o=><option key={o.id} value={o.id}>{o.name} · {o.id}</option>)}</select>:typeof f.value==='number'?<input type="number" min={f.min} max={f.max} step="1" value={value} onChange={e=>edit(f.path,e.target.value===''?'':Number(e.target.value))}/>:<textarea rows={value.length>140?4:2} maxLength={f.max} value={value} onChange={e=>edit(f.path,e.target.value)}/>}
    {Object.hasOwn(draft.edits,f.path)&&<button type="button" onClick={()=>{const edits={...draft.edits};delete edits[f.path];change({...draft,edits});}}>Revert field</button>}
  </label>;}
  return <div className="journey-studio"><header><a className="brand" href="/characters">Katchimeras<span>Existing character editor</span></a><div className="toolbar"><a href="/new-companion">Create a Katchimera</a><a href="/arcs">New arcs</a><a href="/journeys">Journey walkthrough</a><a href="/">Live events</a>
    <button disabled={busy} onClick={()=>run(async()=>{const r=await api('drafts',draft);setSaved((await api(`${character}/drafts`)).drafts);setStatus(`Saved ${r.saved}`);})}>Save character draft</button>
    <button disabled={busy} onClick={()=>run(async()=>{const r=await api('validate',draft);setIssues(r.issues);setBoards(r.boards);setStatus(r.issues.length?'Resolve these issues before export.':'Structural checks passed. Playtest edited boards and progression before integrating.');})}>Validate character</button>
    <button className="primary" disabled={busy} onClick={()=>run(async()=>{const r=await fetch('/api/characters/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});if(!r.ok){const e=await r.json();throw new Error(e.error??e.issues?.join('\n'));}const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`${character}-review.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Review bundle exported: edited definitions, field diff, draft and assigned images. Requires source integration and rebuild; not an installable content pack.');})}>Export review bundle</button>
  </div></header><div className="journey-status" role="status">{busy?'Working…':status}{issues.map((s,i)=><p className="error" key={i}>{s}</p>)}</div>
  <main className="journey-layout"><aside className="journey-outline"><label className="field"><span>Character</span><select disabled={busy} value={character} onChange={e=>setCharacter(e.target.value)}>{characters.map(c=><option key={c} value={c}>{label(c)}</option>)}</select></label><p className="muted">Each character keeps a separate browser draft.</p><nav aria-label="Character sections">{catalog.sections.map(s=><button disabled={busy} key={s.path} className={section===s.path?'selected':''} onClick={()=>{setSection(s.path);setConversation(null);setChoice(null);setQuery('');}}>{s.title}</button>)}</nav>
    <label className="field"><span>Saved versions</span><select value={load} onChange={e=>setLoad(e.target.value)}><option value="">Choose a version</option>{saved.map(s=><option key={s}>{s}</option>)}</select></label><button disabled={busy||!load} onClick={()=>run(async()=>{await api('drafts',draft);const next=await api(`drafts/${load}`);if(next.character!==character)throw new Error('Wrong character draft');change(next);setSaved((await api(`${character}/drafts`)).drafts);setStatus('Loaded saved version. Previous workspace also saved.');})}>Load saved version</button>
    <button disabled={busy} onClick={()=>run(async()=>{await api('drafts',draft);change(catalog.draft);setSaved((await api(`${character}/drafts`)).drafts);setStatus('Source restored. Previous workspace saved to disk.');})}>Save and reset to source</button>
  </aside><section className="journey-editor"><div className="eyebrow">{label(character)} / {section}</div><h1>{catalog.sections.find(s=>s.path===section)?.title}</h1><p className="intro">Edit authored values. IDs, episode order, mechanics and saved-progress links stay fixed. Times are milliseconds; board positions are canonical cell numbers.</p>
    <label className="field"><span>Find a field or line</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search within this section"/></label><fieldset disabled={busy}>{fields.map(field)}</fieldset>
    {!fields.length&&<p>No editable fields match this search.</p>}
    {episode&&<><button disabled={busy} onClick={()=>run(async()=>{const r=await api('dialogue',{draft,index:Number(section.split('/').at(-1))});setConversation(r.conversation);setNodeId(r.conversation?.entryNodeId??null);setReply('');setStatus(r.conversation?'Base dialogue compiled with the game definitions. Personalisation is not simulated.':'This episode is played by its first-day flow; select First day where available.');})}>Walk through Journey dialogue</button>{conversation&&<div className="journey-dialogue"><p>{reply}</p><p>{node?.prompt??node?.message??'Dialogue complete or game-specific interaction.'}</p>{node?.options?.map(o=><button key={o.id} onClick={()=>{setReply(o.reply??'');setNodeId(o.nextNodeId??null);}}>{o.label}</button>)}</div>}</>}
    {previewChoices.length>0&&<div className="journey-dialogue"><h2>Choice preview</h2><p>{typeof selectedData.prompt==='string'?selectedData.prompt:typeof selectedData.opening==='string'?selectedData.opening:''}</p>{previewChoices.map(c=><button key={c.id} onClick={()=>setChoice(c.id)}>{c.label}</button>)}{chosen&&<>{typeof selectedData.handoffs?.[chosen.id]==='string'&&<p>{selectedData.handoffs[chosen.id]}</p>}{['reply','openingConclusion','returnLine','resolutionLine'].map(k=>typeof chosen[k]==='string'&&<p key={k}><strong>{label(k)}: </strong>{chosen[k]}</p>)}{chosen.order&&<pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(chosen.order,null,2)}</pre>}</>}</div>}
    <details><summary>Review edits ({Object.keys(draft.edits).length})</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(draft.edits,null,2)}</pre></details>
  </section><section className="journey-art"><h2>Character artwork</h2><p className="muted">Draft image assignments. Review export includes selected images; it does not replace shipped art.</p>{Object.entries(catalog.artSlots).map(([slot,original])=><fieldset key={slot} disabled={busy} style={{marginBottom:24}}><label className="field"><span>{label(slot)}</span><select value={draft.art[slot]??original} onChange={e=>change({...draft,art:{...draft.art,[slot]:e.target.value}})}>{catalog.assets.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><img className="journey-tile" alt={`${character} ${slot} assigned art`} src={`/api/journey/assets/${draft.art[slot]??original}`}/>
    <label className="field"><span>Upload {label(slot)} image</span><input type="file" accept="image/png,image/webp,image/jpeg" onChange={e=>{const file=e.target.files[0];if(!file)return;if(file.size>1800000){setStatus('Use an image smaller than 1.8 MB');return;}run(async()=>{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});const r=await fetch('/api/journey/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data,name:file.name})});const v=await r.json();if(!r.ok)throw new Error(v.error);setCatalog({...catalog,assets:[...catalog.assets.filter(a=>a.id!==v.asset.id),v.asset]});change({...draft,art:{...draft.art,[slot]:v.asset.id}});});}}/></label>
  </fieldset>)}
    <h2>Board inspection</h2><p className="muted">Validate to refresh boards. This checks layout and references, not puzzle solvability. Misted items are marked E; hidden items V; delivery cells D.</p>{boards.filter(b=>inside(b.path,section)||inside(section,b.path)).map(b=><div key={b.path}><h3>{b.path}</h3><div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:4}}>{b.window.map(cell=>{const item=b.cells.find(c=>c.cell===cell);return <div key={cell} title={item?.definitionId} style={{border:'1px solid #abbca7',padding:5,fontSize:10,minHeight:56,overflowWrap:'anywhere',background:item?'#fff':'transparent'}}><strong>{cell} {item?.kind==='echoes'?'E':item?.kind==='veiled'?'V':b.deliveryCells.includes(cell)?'D':''}</strong><div>{item?.definitionId??'empty'}</div></div>;})}</div></div>)}
    <p className="preview-note">Review-only edits to existing content. No live publishing or player-save changes. Use New arcs for additive installable content packs.</p>
  </section></main></div>;
}
