import { SharedAdventureReview } from './shared-adventure-review';
import { LocalEventEditor } from './local-event-editor';
import { NewCompanionStudio } from './new-companion-studio';
import { CharacterStudio } from './character-studio';
import { ArcStudio } from './arc-studio';
import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
import { JourneyStudio } from './journey-studio';

const kinds = ['merge', 'order_completed', 'mist_cleared', 'hex_restored', 'structure_upgraded', 'friend_rescued', 'bond_gained', 'wisp_discovered', 'journey_completed', 'incursion_completed'];
const names = { incursion_completed: 'Complete an incursion encounter', merge: 'Merge items', order_completed: 'Complete an order', mist_cleared: 'Clear Mist', hex_restored: 'Restore a hex', structure_upgraded: 'Upgrade a structure', friend_rescued: 'Rescue a friend', bond_gained: 'Gain Bond', wisp_discovered: 'Discover a Wisp', journey_completed: 'Complete a Journey', expedition_completed: 'Complete an expedition' };
const initial = { id: 'moonlit-mist-pilot', version: 1, contentSchemaVersion: 2, title: 'Moonlit Mist pilot', minAppVersion: '1.0.0', liveEvents: [{ id: 'moonlit-mist-2026-10', version: 1, title: 'The Moonlit Mist', description: 'Silver Mist has returned to the Grove. Bring light back to the places you restored.', enabled: false, startsAt: '2026-10-01T00:00:00Z', endsAt: '2026-10-08T00:00:00Z', claimEndsAt: '2026-10-10T00:00:00Z', minHarmony: 100, rules: [{ id: 'restore', kind: 'hex_restored', points: 100, limit: 3 }, { id: 'orders', kind: 'order_completed', points: 20, limit: 30 }], tiers: [{ id: 'first-light', points: 100, free: { id: 'first-light-free', items: [{ kind: 'glow', amount: 50 }] } }, { id: 'grove-awake', points: 500, free: { id: 'grove-awake-free', items: [{ kind: 'wisp', id: 'sprout' }] } }] }] };

async function api(route, body) {
  const response = await fetch(`/api/${route}`, body === undefined ? undefined : { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  const result = await response.json();
  if (!response.ok) throw new Error(result.issues?.join('\n') || result.error || 'Request failed');
  return result;
}
function Field({ label, children }) { return <label className="field"><span>{label}</span>{children}</label>; }
function App() {
  const [pack, setPack] = useState(initial);
  const [selected, setSelected] = useState(0);
  const [message, setMessage] = useState('Draft · events are disabled until launch acceptance is complete.');
  const [issues, setIssues] = useState([]);
  const [busy, setBusy] = useState(false);
  const [catalog, setCatalog] = useState({ stagingConfigured: false });
  const [actions, setActions] = useState([]);
  const [simulation, setSimulation] = useState(null);
  const [drafts, setDrafts] = useState([]);
  const [draftName, setDraftName] = useState('');
  const event = pack.liveEvents[selected];
  useEffect(() => { api('catalog').then(setCatalog).catch((error) => setMessage(error.message)); api('drafts').then((result) => setDrafts(result.drafts)).catch((error) => setMessage(error.message)); }, []);
  const update = (patch) => { setPack((current) => ({ ...current, liveEvents: current.liveEvents.map((entry, index) => index === selected ? { ...entry, ...patch } : entry) })); setSimulation(null); };
  const perform = async (work) => { setBusy(true); setIssues([]); try { await work(); } catch (error) { setIssues([error.message]); } finally { setBusy(false); } };
  const check = async () => { const result = await api('validate', { pack }); setIssues(result.issues); setMessage(result.issues.length ? 'Resolve the validation issues before saving.' : 'Release validated against the game’s actual content catalogue.'); return result; };
  const exportPack = () => perform(async () => { const result = await check(); if (result.issues.length) return; const url = URL.createObjectURL(new Blob([JSON.stringify(result.packs[0], null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `${pack.id}.json`; link.click(); URL.revokeObjectURL(url); });
  const editRule = (index, patch) => update({ rules: event.rules.map((rule, i) => i === index ? { ...rule, ...patch } : rule) });
  const addAction = (kind) => { const next = [...actions, { id: `preview-${actions.length}`, kind, quantity: 1, context: { targetId: `preview-${actions.length}`, tags: event.rules.find(r => r.kind === kind)?.filter?.tags ?? [] } }]; setActions(next); perform(async () => setSimulation(await api('simulate', { event, actions: next }))); };
  return <div className="studio">
    <div className="draft-loader"><label>Saved draft <select value={draftName} onChange={(e) => setDraftName(e.target.value)}><option value="">Choose a saved draft</option>{drafts.map((name) => <option key={name} value={name}>{name}</option>)}</select></label><button disabled={busy || !draftName} onClick={() => perform(async () => { const draft = await api(`drafts/${encodeURIComponent(draftName)}`); if (!draft.liveEvents?.length) throw new Error('This release has no events to edit.'); setPack(draft); setSelected(0); setActions([]); setSimulation(null); setMessage(`Loaded ${draftName}`); })}>Load draft</button><button disabled={busy} onClick={() => perform(async () => setDrafts((await api('drafts')).drafts))}>Refresh drafts</button></div>
    <header><a className="brand" href="/">Katchimeras<span>Live Ops Studio</span></a><div className="toolbar"><button disabled={busy} onClick={() => perform(async () => { setPack(await api('local-event-template')); setSelected(0); setActions([]); setSimulation(null); setMessage('Two offline event templates loaded. Choose dates and unique occurrence IDs before export.'); })}>New offline events</button><a href="/shared-adventure">Shared adventure</a><a href="/characters">Characters</a><a href="/journeys">Journey authoring</a><a href="/arcs">New arc</a><button disabled={busy} onClick={() => perform(check)}>Validate</button><button disabled={busy} onClick={exportPack}>Export release</button><button className="primary" disabled={busy} onClick={() => perform(async () => { const result = await api('drafts', { pack }); setMessage(`Saved ${result.saved}`); })}>Save draft</button></div></header>
    <main>
      <aside><div className="eyebrow">Content release</div><Field label="Release ID"><input value={pack.id} onChange={(e) => setPack({ ...pack, id: e.target.value })}/></Field><nav>{pack.liveEvents.map((entry, index) => <button className={selected === index ? 'selected' : ''} key={index} onClick={() => { setSelected(index); setActions([]); setSimulation(null); }}>{entry.title}<small>{entry.rules.length} scoring rules · v{entry.version}</small></button>)}</nav><button className="text-button" onClick={() => { const copy = structuredClone(event); copy.id = `${event.id}-incursion`; copy.title = 'Grove Incursion'; copy.tiers = []; setPack({ ...pack, liveEvents: [...pack.liveEvents, copy] }); setSelected(pack.liveEvents.length); setActions([]); }}>+ Add overlapping event</button><div className="aside-note">Every event uses the same saved gameplay actions. Independent caps keep repeated play balanced.</div><button disabled={busy || !catalog.stagingConfigured} onClick={() => perform(async () => { const result = await api('stage', { pack }); setMessage(`Staged ${result.staged}. Disabled pending launch review.`); })}>Send to staging</button><small>{catalog.stagingConfigured ? 'Staging saves a disabled, immutable release.' : 'Staging connection is not configured.'}</small></aside>
      <section className="editor"><div className="eyebrow">World event / draft</div><h1>{event.title}</h1><p className="intro">Make something happen in the world.</p><div className="two"><Field label="Event title"><input value={event.title} onChange={(e) => update({ title: e.target.value })}/></Field><Field label="Instance ID"><input value={event.id} onChange={(e) => update({ id: e.target.value })}/></Field></div><Field label="Player-facing introduction"><textarea value={event.description} onChange={(e) => update({ description: e.target.value })}/></Field><div className="three">{[['startsAt','Starts (UTC)'],['endsAt','Scoring ends (UTC)'],['claimEndsAt','Claims close (UTC)']].map(([key,label]) => <Field key={key} label={label}><input type="datetime-local" value={event[key].slice(0,16)} onChange={(e) => update({ [key]: `${e.target.value}:00Z` })}/></Field>)}</div><Field label="Minimum Harmony"><input type="number" min="0" value={event.minHarmony} onChange={(e) => update({ minHarmony: Number(e.target.value) })}/></Field>
      {pack.harmonyDefinitions?.[0] ? <section><h2>World Harmony</h2><Field label="Incursion unlock threshold"><input type="number" min="0" value={pack.harmonyDefinitions[0].incursionThreshold} onChange={e => setPack({ ...pack, harmonyDefinitions: [{ ...pack.harmonyDefinitions[0], incursionThreshold: Number(e.target.value) }] })} /></Field>{Object.entries(pack.harmonyDefinitions[0].awards).map(([kind, points]) => <Field key={kind} label={names[kind] ?? kind}><input type="number" min="0" value={points} onChange={e => setPack({ ...pack, harmonyDefinitions: [{ ...pack.harmonyDefinitions[0], awards: { ...pack.harmonyDefinitions[0].awards, [kind]: Number(e.target.value) } }] })} /></Field>)}<p>Changes apply to future milestones. Previously awarded Harmony is retained.</p></section> : null}
      {event.authority === 'local' ? <LocalEventEditor event={event} update={update} /> : null}
      <div className="section-heading"><h2>What moves the event forward?</h2><button onClick={() => update({ rules: [...event.rules, { id: `rule-${event.rules.length + 1}`, kind: 'merge', points: 1, limit: 100 }] })}>Add rule</button></div><div className="rule-labels"><span>Gameplay action</span><span>Points</span><span>Event cap</span><span/></div>{event.rules.map((rule, index) => <div className="rule" key={index}><select aria-label="Gameplay action" value={rule.kind} onChange={(e) => editRule(index,{ kind:e.target.value })}>{kinds.map((kind) => <option key={kind} value={kind}>{names[kind]}</option>)}</select><input aria-label="Points per action" type="number" min="1" value={rule.points} onChange={(e) => editRule(index,{points:Number(e.target.value)})}/><input aria-label="Maximum actions" type="number" min="1" value={rule.limit} onChange={(e) => editRule(index,{limit:Number(e.target.value)})}/><button aria-label="Remove rule" onClick={() => update({rules:event.rules.filter((_,i) => i!==index)})}>×</button></div>)}
      <div className="section-heading"><h2>Reward track</h2><button onClick={() => update({ tiers: [...event.tiers, { id: `tier-${event.tiers.length + 1}`, points: (event.tiers.at(-1)?.points ?? 0) + 100, free: { id: `reward-${event.tiers.length + 1}`, items: [{ kind: 'glow', amount: 50 }] } }] })}>Add tier</button></div>{event.tiers.map((tier,index) => <div className="tier" key={index}><Field label="Threshold"><input type="number" value={tier.points} onChange={(e) => update({tiers:event.tiers.map((entry,i) => i===index?{...entry,points:Number(e.target.value)}:entry)})}/></Field><Field label="Free reward"><select value={tier.free.items[0].kind} onChange={(e) => update({tiers:event.tiers.map((entry,i) => i===index?{...entry,free:{...entry.free,items:[e.target.value==='glow'?{kind:'glow',amount:50}:{kind:e.target.value,id:e.target.value==='cosmetic'?event.keepsakes?.[0]?.id ?? '':'sprout'}]}}:entry)})}><option value="glow">Glow</option>{event.authority === 'local' ? <option value="cosmetic">Keepsake</option> : <option value="wisp">Wisp</option>}</select></Field><Field label={tier.free.items[0].kind==='glow'?'Amount':tier.free.items[0].kind==='cosmetic'?'Keepsake ID':'Wisp ID'}><input value={tier.free.items[0].amount ?? tier.free.items[0].id} onChange={(e) => update({tiers:event.tiers.map((entry,i) => i===index?{...entry,free:{...entry.free,items:[entry.free.items[0].kind==='glow'?{kind:'glow',amount:Number(e.target.value)}:{kind:entry.free.items[0].kind,id:e.target.value}]}}:entry)})}/></Field></div>)}<p className="muted">Premium purchases stay disabled until server claims and store testing are complete.</p>
      </section>
      <section className="preview"><div className="eyebrow">Playtest scoring</div><h2>A little light goes a long way.</h2><div className="score">{simulation?.progress.points ?? 0}<span>event points</span></div><p>Try an action. Preview uses the game’s scoring rules and caps.</p><div className="action-list">{[...new Set(event.rules.map((rule) => rule.kind))].map((kind) => <button disabled={busy} key={kind} onClick={() => addAction(kind)}>{names[kind]}<span>+</span></button>)}</div><button className="text-button" onClick={() => {setActions([]);setSimulation(null);}}>Reset playtest</button>{(simulation?.tiers ?? event.tiers).map((tier) => <div className="milestone" key={tier.id}><span className={tier.reached?'reached':''}>{tier.reached?'✓':'○'}</span><div>{tier.id}<small>{tier.points} points</small></div></div>)}<div className="preview-note">Preview changes no player balances and makes no purchases.</div></section>
    </main><footer role="status"><span>{busy?'Checking…':message}</span>{issues.map((issue,index) => <p className="error" key={index}>{issue}</p>)}</footer>
  </div>;
}
createRoot(document.getElementById('root')).render(window.location.pathname.startsWith('/shared-adventure') ? <SharedAdventureReview /> : window.location.pathname.startsWith('/new-companion') ? <NewCompanionStudio /> : window.location.pathname.startsWith('/characters') ? <CharacterStudio/> : window.location.pathname.startsWith('/arcs') ? <ArcStudio/> : window.location.pathname.startsWith('/journeys') ? <JourneyStudio/> : <App/>);
