import React,{useEffect,useState} from 'react';
import './journey.css';
const label=s=>s.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^./,s=>s.toUpperCase());
async function api(route,body){const r=await fetch(`/api/new-companions/${route}`,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw Error(v.error??v.issues?.join('\n'));return v;}
const sections=['tile','mission','discoveryFlow','egg','dayOne','lesson','daily'];
export function NewCompanionStudio(){
  const [catalog,setCatalog]=useState(null),[source,setSource]=useState(null),[draft,setDraft]=useState(null),[section,setSection]=useState('dayOne'),[query,setQuery]=useState(''),[status,setStatus]=useState('Loading templates…'),[busy,setBusy]=useState(false),[saved,setSaved]=useState([]),[load,setLoad]=useState(''),[pack,setPack]=useState(null);
  useEffect(()=>{let alive=true;api('catalog').then(async c=>{let d;try{d=JSON.parse(localStorage.getItem('new-companion-draft'));}catch{}const s=await api(`source/${c.characters.some(x=>x.id===d?.character)?d.character:c.characters[0].id}`);const versions=await api('drafts');if(alive){setCatalog(c);setSource(s);setDraft(c.characters.some(x=>x.id===d?.character)&&d?.kind==='new-companion'&&d.edits&&d.art&&Array.isArray(d.episodes)?d:s.draft);setSaved(versions.drafts);setStatus('Create an arrival for an existing roster character. Export installs through Content Packs.');}}).catch(e=>alive&&setStatus(e.message));return()=>{alive=false;};},[]);
  useEffect(()=>{if(draft)try{localStorage.setItem('new-companion-draft',JSON.stringify(draft));}catch{setStatus('Browser storage full. Save a version to disk.');}},[draft]);
  async function run(fn){if(busy)return;setBusy(true);try{await fn();}catch(e){setStatus(e.message);}finally{setBusy(false);}}
  function change(next){setDraft(next);setPack(null);setStatus('Draft changed · browser autosaved');}
  const update=(key,value)=>change({...draft,[key]:value});
  const edit=(key,value)=>update('edits',{...draft.edits,[key]:value});
  async function save(){const s=await api('drafts',draft);setSaved((await api('drafts')).drafts);return s.saved;}
  if(!draft||!catalog||!source)return <p role="status">{status}</p>;
  const fields=source.fields.filter(f=>f.path.startsWith(`hatchable/${section}/`)&&!['hatchable/tile/price'].includes(f.path)).filter(f=>`${f.path} ${draft.edits[f.path]??f.value}`.toLowerCase().includes(query.toLowerCase()));
  const value=path=>draft.edits[path]??source.fields.find(f=>f.path===path)?.value;
  return <div className="journey-studio"><header><a className="brand" href="/new-companion">Katchimeras<span>Create from template</span></a><div className="toolbar"><a href="/characters">Existing characters</a><a href="/arcs">New arcs</a><button disabled={busy} onClick={()=>run(async()=>setStatus(`Saved ${await save()}`))}>Save draft</button><button disabled={busy} onClick={()=>run(async()=>{const r=await api('validate',draft);setPack(r.pack);setStatus(r.issues.length?r.issues.join('\n'):'Content pack validated. Playtest the full arrival on a test profile before release.');})}>Validate companion</button><button className="primary" disabled={busy} onClick={()=>run(async()=>{const r=await fetch('/api/new-companions/bundle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});if(!r.ok){const e=await r.json();throw Error(e.error??e.issues?.join('\n'));}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`${draft.id}-${draft.releaseVersion}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Release bundle exported. Host the included images, then install manifest.json in Developer Tools → Content Packs and restart.');})}>Export installable bundle</button></div></header>
  <div className="journey-status" role="status" style={{whiteSpace:'pre-wrap'}}>{busy?'Working…':status}</div>
  <main className="journey-layout"><aside className="journey-outline"><label className="field"><span>Roster character</span><select disabled={busy} value={draft.character} onChange={e=>{const id=e.target.value;run(async()=>{await save();const next=await api(`source/${id}`);setSource(next);change(next.draft);});}}>{catalog.characters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p className="muted">Answer-based Egg · Mist rescue · first-day parcel · merge lesson · daily moment · Journey. Existing family, skins and animations are reused.</p>
  <nav aria-label="Template sections">{sections.map(s=><button key={s} className={section===s?'selected':''} onClick={()=>{setSection(s);setQuery('');}}>{label(s)}</button>)}<button className={section==='journey'?'selected':''} onClick={()=>setSection('journey')}>Journey episodes</button></nav>
  <label className="field"><span>Release ID</span><input disabled={busy} value={draft.id} onChange={e=>update('id',e.target.value)}/></label><label className="field"><span>Version</span><input disabled={busy} type="number" min="1" value={draft.releaseVersion} onChange={e=>update('releaseVersion',Number(e.target.value))}/></label>
  <label className="field"><span>Available after</span><select disabled={busy} value={draft.after} onChange={e=>update('after',e.target.value)}>{catalog.predecessors.map(id=><option key={id}>{id}</option>)}</select></label>{['q','r','price'].map(k=><label className="field" key={k}><span>{k==='price'?'Rescue cost':`Hex ${k}`}</span><input disabled={busy} type="number" value={draft[k]} onChange={e=>update(k,e.target.value===''?'':Number(e.target.value))}/></label>)}
  <details><summary>Occupied hexes</summary>{catalog.occupied.map(t=><p key={t.id}>{t.id}: {t.q}, {t.r}</p>)}</details>
  <label className="field"><span>Saved versions</span><select disabled={busy} value={load} onChange={e=>setLoad(e.target.value)}><option value="">Choose a version</option>{saved.map(f=><option key={f}>{f}</option>)}</select></label><button disabled={busy||!load} onClick={()=>run(async()=>{await save();const d=await api(`drafts/${load}`),s=await api(`source/${d.character}`);setSource(s);change(d);setStatus('Loaded version. Previous workspace saved.');})}>Load version</button>
  <button disabled={busy} onClick={()=>run(async()=>{await save();const s=await api(`source/${draft.character}`);setSource(s);change(s.draft);setStatus('Fresh template loaded. Previous draft saved.');})}>Save and start fresh</button></aside><section className="journey-editor"><div className="eyebrow">{draft.character} / {section}</div><h1>{section==='journey'?'Their next chapter':label(section)}</h1><p className="intro">Edit this new friend’s copy and objectives. The template creates stable IDs and connects the flow. Save IDs after first publication; existing packs cannot be overwritten.</p>
  {section!=='journey'?<><label className="field"><span>Find a field</span><input disabled={busy} value={query} onChange={e=>setQuery(e.target.value)}/></label><fieldset disabled={busy}>{fields.map(f=><label className="field" key={f.path}><span>{label(f.label)} <small>{f.path}</small></span>{f.options?<select disabled={busy} value={value(f.path)} onChange={e=>edit(f.path,e.target.value)}>{f.options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>:typeof f.value==='number'?<input disabled={busy} type="number" value={value(f.path)} min={f.min} max={f.max} onChange={e=>edit(f.path,e.target.value===''?'':Number(e.target.value))}/>:<textarea rows="3" value={value(f.path)} maxLength={f.max} onChange={e=>edit(f.path,e.target.value)}/>}</label>)}</fieldset></>:<><p>The hatch conversation is Day 1. These episodes follow in order; each waits for the previous episode and the delay below.</p>{draft.episodes.map((ep,i)=><fieldset disabled={busy} key={i}><h2>Episode {i+2}</h2>{['id','title','text','hours'].map(k=><label className="field" key={k}><span>{k==='hours'?'Wait after previous episode (hours)':label(k)}</span><input disabled={busy} type={k==='hours'?'number':'text'} value={ep[k]} onChange={e=>update('episodes',draft.episodes.map((v,j)=>j===i?{...v,[k]:k==='hours'?Number(e.target.value):e.target.value}:v))}/></label>)}<button disabled={draft.episodes.length===1} onClick={()=>update('episodes',draft.episodes.filter((_,j)=>j!==i))}>Remove episode</button></fieldset>)}<button disabled={busy||draft.episodes.length>=50} onClick={()=>update('episodes',[...draft.episodes,{id:`episode-${crypto.randomUUID().slice(0,8)}`,title:'A new memory',text:'There is more to discover together.',hours:0}])}>Add episode</button></>}
  {section==='dayOne'&&<div className="journey-dialogue"><h2>First conversation preview</h2><p>{value('hatchable/dayOne/opening')}</p>{source.hatchable.dayOne.choices.map((c,i)=><details key={c.id}><summary>{value(`hatchable/dayOne/choices/${i}/label`)}</summary><p>{value(`hatchable/dayOne/handoffs/${c.id}`)}</p></details>)}</div>}
  {pack&&<details><summary>Validated manifest</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(pack,null,2)}</pre></details>}
  </section><section className="journey-art"><h2>Art assignments</h2><p className="muted">Uploads become 1024px WebP files with measured bounds and checksums. Character art here is the lesson cutout; existing roster portraits and animations remain in use.</p>{draft.character==='feastle'&&<button disabled={busy} onClick={()=>run(async()=>{const art=await api('feastle-art',{});update('art',{tile:art.tile.id,cutout:art.cutout.id});})}>Use existing Feastle art</button>}
  {['tile','cutout'].map(slot=><fieldset key={slot} disabled={busy}><h3>{slot==='tile'?'Rescued hex tile':'Character cutout'}</h3>{draft.art[slot]&&<img className="journey-tile" alt={`${slot} preview`} src={`/api/new-companions/assets/${draft.art[slot]}`}/>}<label className="field"><span>Upload {slot}</span><input disabled={busy} type="file" accept="image/png,image/webp,image/jpeg" onChange={e=>{const f=e.target.files[0];if(!f)return;run(async()=>{if(f.size>1800000)throw Error('Use an image under 1.8 MB');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f);});const a=await api('assets',{data});update('art',{...draft.art,[slot]:a.id});});}}/></label></fieldset>)}
  <label className="field"><span>Asset hosting folder (HTTPS)</span><input disabled={busy} value={draft.assetBaseUrl} placeholder="https://your-cdn.example/feastle/v1" onChange={e=>update('assetBaseUrl',e.target.value)}/></label><p className="preview-note">Export includes assets and an installable manifest. Uploading here does not host or publish them. Install on a test profile, restart, then test online installation and offline play. Completely new species, skins and mechanics are outside this template.</p></section></main></div>;
}
