import { createEditorialCompanionPack, type EditorialCompanionProfile } from '@/constants/editorial-companion-pack';

const profiles = {
  flexel: {
    companionName: 'Flexel', focusName: 'strength, gym, or mobility practice', momentName: 'training moment',
    kinds: [['strength', 'Strength or resistance work'], ['mobility', 'Mobility or range-of-motion work'], ['adapted', 'Seated or adapted training'], ['recovery', 'Warm-up, recovery, or rest'], ['none', 'No training moment']],
    effects: [['capable', 'A sense of capability'], ['skill', 'A technique insight'], ['energy', 'A change in energy'], ['enjoyment', 'Enjoyment or interest'], ['no-change', 'No clear effect']],
    supports: [['plan', 'A simple plan'], ['access', 'Accessible space or equipment'], ['support', 'Coaching or company'], ['capacity', 'Enough capacity'], ['adaptation', 'An adaptation that suited me']],
    barriers: [['pain', 'Pain, injury, or symptoms'], ['energy', 'Fatigue or recovery needs'], ['access', 'Cost, access, or equipment'], ['unclear', 'Not knowing what suited me'], ['time', 'Time or other responsibilities']],
    details: [['technique', 'A technique cue'], ['resistance', 'Resistance or support used'], ['range', 'Range or position'], ['body', 'A body response'], ['stop', 'A reason to reduce or stop']],
    fit: [['well', 'It fitted well'], ['adapted', 'I adapted it'], ['shorter', 'I needed less'], ['stopped', 'I stopped when needed'], ['none', 'Training did not fit today']],
    next: [['familiar', 'A familiar movement'], ['mobility', 'Gentle mobility'], ['adapted', 'An adapted option'], ['support', 'Ask for guidance'], ['rest', 'Recovery or no session']],
    conditions: [['body', 'Pain, symptoms, or energy'], ['space', 'Space and equipment'], ['plan', 'Knowing what to do'], ['support', 'Support or supervision'], ['time', 'Available time']],
    limits: [['reduced', 'I reduced the load or range'], ['changed', 'I changed the movement'], ['stopped', 'I stopped'], ['rested', 'I chose recovery'], ['none', 'No boundary stood out']],
    learning: [['adaptation', 'Which adaptations suit me'], ['technique', 'A technique that helps'], ['dose', 'How much is enough'], ['recovery', 'What supports recovery'], ['varies', 'My capacity varies']],
    keep: [['movement', 'One useful movement'], ['adaptation', 'A helpful adaptation'], ['confidence', 'Confidence without comparison'], ['recovery', 'Room for recovery'], ['choice', 'Permission not to train']],
    adapt: [['lighter', 'Use less load or effort'], ['different', 'Choose another movement'], ['support', 'Add guidance or support'], ['less-often', 'Train less often'], ['pause', 'Pause it']],
  },
  sprintail: {
    companionName: 'Sprintail', focusName: 'running or run-walk practice', momentName: 'run or run-walk moment',
    kinds: [['run', 'A continuous run'], ['run-walk', 'Run-walk intervals'], ['short', 'A short or easy outing'], ['support', 'Preparation or recovery'], ['none', 'Not a running day']],
    effects: [['headspace', 'Headspace'], ['enjoyment', 'Enjoyment'], ['endurance', 'A sense of endurance'], ['connection', 'Connection to place or people'], ['no-change', 'No clear effect']],
    supports: [['pace', 'A sustainable pace'], ['route', 'A safe, accessible route'], ['company', 'Company or support'], ['conditions', 'Suitable conditions'], ['recovery', 'Enough recovery']],
    barriers: [['pain', 'Pain, injury, or symptoms'], ['conditions', 'Weather, light, or air quality'], ['access', 'Route or access barriers'], ['energy', 'Fatigue or recovery needs'], ['time', 'Time or responsibilities']],
    details: [['pace', 'How the pace felt'], ['interval', 'A run-walk interval'], ['route', 'A route detail'], ['body', 'A body response'], ['stop', 'A reason to slow or stop']],
    fit: [['well', 'It fitted well'], ['slower', 'I slowed down'], ['shorter', 'I made it shorter'], ['stopped', 'I stopped when needed'], ['none', 'Running did not fit today']],
    next: [['easy', 'An easy run or run-walk'], ['short', 'Something shorter'], ['company', 'Run with support'], ['route', 'Choose a suitable route'], ['rest', 'Recovery or no run']],
    conditions: [['body', 'Pain, symptoms, or energy'], ['weather', 'Weather or air quality'], ['route', 'Surface, safety, or access'], ['pace', 'Pace and expectations'], ['time', 'Available time']],
    limits: [['slowed', 'I slowed down'], ['walked', 'I changed to walking'], ['stopped', 'I stopped'], ['rested', 'I chose recovery'], ['none', 'No boundary stood out']],
    learning: [['pace', 'What sustainable feels like'], ['intervals', 'Which intervals suit me'], ['conditions', 'Which conditions help'], ['recovery', 'What recovery I need'], ['varies', 'My capacity varies']],
    keep: [['enjoyment', 'Enjoyment'], ['pace', 'A sustainable pace'], ['route', 'A route that suits me'], ['recovery', 'Room for recovery'], ['choice', 'Permission not to run']],
    adapt: [['slower', 'Go slower'], ['shorter', 'Make it shorter'], ['run-walk', 'Use run-walk intervals'], ['less-often', 'Run less often'], ['pause', 'Pause it']],
  },
  hooplet: {
    companionName: 'Hooplet', focusName: 'basketball practice or play', momentName: 'basketball moment',
    kinds: [['shoot', 'Shooting or ball skill'], ['team', 'Team or shared play'], ['adapted', 'Wheelchair or adapted basketball'], ['watch', 'Watching, learning, or visualising'], ['none', 'No basketball moment']],
    effects: [['fun', 'Fun'], ['skill', 'A skill insight'], ['connection', 'Connection or teamwork'], ['confidence', 'A little confidence'], ['no-change', 'No clear effect']],
    supports: [['court', 'Suitable court or space'], ['people', 'Welcoming people'], ['adaptation', 'An adaptation or suitable equipment'], ['drill', 'A clear drill'], ['capacity', 'Enough capacity']],
    barriers: [['access', 'Court, cost, or transport access'], ['body', 'Pain, injury, or fatigue'], ['people', 'No suitable people or session'], ['confidence', 'Confidence or belonging'], ['equipment', 'Equipment or adaptation needs']],
    details: [['shot', 'A shot or release'], ['handle', 'Ball handling'], ['decision', 'A decision or read'], ['team', 'Communication or support'], ['adaptation', 'An adaptation that mattered']],
    fit: [['well', 'It fitted well'], ['adapted', 'I adapted the activity'], ['solo', 'Solo practice suited me'], ['stopped', 'I stopped when needed'], ['none', 'Basketball did not fit today']],
    next: [['ball', 'A brief ball-skill moment'], ['shoot', 'A manageable shooting practice'], ['team', 'A welcoming shared session'], ['learn', 'Watch or learn one detail'], ['rest', 'Recovery or no practice']],
    conditions: [['body', 'Pain, fatigue, or energy'], ['access', 'Court and equipment access'], ['people', 'People and belonging'], ['pressure', 'Competition or expectations'], ['time', 'Available time']],
    limits: [['adapted', 'I adapted the play'], ['solo', 'I chose solo practice'], ['stopped', 'I stopped'], ['declined', 'I skipped competition'], ['none', 'No boundary stood out']],
    learning: [['skill', 'Which skill I enjoy'], ['practice', 'How I like to practise'], ['team', 'What good teamwork means to me'], ['access', 'What makes play accessible'], ['varies', 'My capacity varies']],
    keep: [['fun', 'Fun'], ['skill', 'One useful skill'], ['team', 'Supportive team play'], ['adaptation', 'A helpful adaptation'], ['choice', 'Freedom from competition']],
    adapt: [['smaller', 'Make practice smaller'], ['different', 'Choose another skill'], ['adapt', 'Change the setup'], ['less-pressure', 'Reduce competition pressure'], ['pause', 'Pause it']],
  },
  serveling: {
    companionName: 'Serveling', focusName: 'tennis or racket-sport practice', momentName: 'racket-sport moment',
    kinds: [['rally', 'A rally or cooperative hit'], ['skill', 'Serve or stroke practice'], ['match', 'A match or points'], ['adapted', 'Seated or adapted racket sport'], ['none', 'No racket-sport moment']],
    effects: [['fun', 'Fun'], ['focus', 'Focus'], ['skill', 'A skill insight'], ['connection', 'Connection with another player'], ['no-change', 'No clear effect']],
    supports: [['court', 'Suitable space or court'], ['partner', 'A supportive partner'], ['adaptation', 'An adaptation or equipment'], ['drill', 'A clear practice idea'], ['capacity', 'Enough capacity']],
    barriers: [['access', 'Court, cost, or transport access'], ['body', 'Pain, injury, or fatigue'], ['partner', 'No suitable partner or session'], ['pressure', 'Match or performance pressure'], ['equipment', 'Equipment or adaptation needs']],
    details: [['contact', 'Ball contact'], ['serve', 'A serve detail'], ['rally', 'A rally pattern'], ['decision', 'A decision or adjustment'], ['adaptation', 'An adaptation that mattered']],
    fit: [['well', 'It fitted well'], ['adapted', 'I adapted the activity'], ['cooperative', 'Cooperative play suited me'], ['stopped', 'I stopped when needed'], ['none', 'Racket sport did not fit today']],
    next: [['rally', 'A cooperative rally'], ['stroke', 'One manageable stroke'], ['solo', 'Solo or wall practice'], ['adapted', 'An adapted setup'], ['rest', 'Recovery or no practice']],
    conditions: [['body', 'Pain, fatigue, or energy'], ['access', 'Court and equipment access'], ['partner', 'Partner or group fit'], ['pressure', 'Scoring or expectations'], ['conditions', 'Weather or environment']],
    limits: [['adapted', 'I adapted the play'], ['cooperative', 'I chose cooperative practice'], ['stopped', 'I stopped'], ['declined', 'I skipped scoring or competition'], ['none', 'No boundary stood out']],
    learning: [['contact', 'What helps clean contact'], ['rhythm', 'What supports a rally'], ['reset', 'How I reset'], ['access', 'What makes play accessible'], ['varies', 'My capacity varies']],
    keep: [['fun', 'Fun'], ['rally', 'A satisfying rally'], ['skill', 'One useful cue'], ['adaptation', 'A helpful adaptation'], ['choice', 'Freedom from scoring']],
    adapt: [['slower', 'Slow the practice down'], ['different', 'Choose another skill'], ['adapt', 'Change the setup'], ['less-pressure', 'Remove scoring pressure'], ['pause', 'Pause it']],
  },
} satisfies Record<string, EditorialCompanionProfile>;

export const BATCH_FIVE_COMPANION_CONTENT = Object.fromEntries(
  Object.entries(profiles).map(([familyId, profile]) => [familyId, createEditorialCompanionPack(profile)]),
);
