// fal.ai / Nano Banana hex pipeline; see shared-world-discovery-v2/CHAIN-HOMES.md.
import { KINGDOM_HEX_TILE_ALPHA_BOUNDS } from './kingdom-hex-tile-bounds.gen';
export const CHAIN_HOME_ART = {
  'garden1': { alphaBounds: KINGDOM_HEX_TILE_ALPHA_BOUNDS['chain_home_garden_1_hex_tile_v1.webp'], sources: { full: require('@incubator/art-world/hex/chain_home_garden_1_hex_tile_v1.webp'), medium: require('@incubator/art-world/hex/chain_home_garden_1_hex_tile_v1_512.webp'), thumb: require('@incubator/art-world/hex/chain_home_garden_1_hex_tile_v1_256.webp') } },
  'garden2': { alphaBounds: KINGDOM_HEX_TILE_ALPHA_BOUNDS['chain_home_garden_2_hex_tile_v1.webp'], sources: { full: require('@incubator/art-world/hex/chain_home_garden_2_hex_tile_v1.webp'), medium: require('@incubator/art-world/hex/chain_home_garden_2_hex_tile_v1_512.webp'), thumb: require('@incubator/art-world/hex/chain_home_garden_2_hex_tile_v1_256.webp') } },
  'garden3': { alphaBounds: KINGDOM_HEX_TILE_ALPHA_BOUNDS['chain_home_garden_3_hex_tile_v1.webp'], sources: { full: require('@incubator/art-world/hex/chain_home_garden_3_hex_tile_v1.webp'), medium: require('@incubator/art-world/hex/chain_home_garden_3_hex_tile_v1_512.webp'), thumb: require('@incubator/art-world/hex/chain_home_garden_3_hex_tile_v1_256.webp') } },
  'storm1': { alphaBounds: KINGDOM_HEX_TILE_ALPHA_BOUNDS['chain_home_storm_1_hex_tile_v1.webp'], sources: { full: require('@incubator/art-world/hex/chain_home_storm_1_hex_tile_v1.webp'), medium: require('@incubator/art-world/hex/chain_home_storm_1_hex_tile_v1_512.webp'), thumb: require('@incubator/art-world/hex/chain_home_storm_1_hex_tile_v1_256.webp') } },
  'storm2': { alphaBounds: KINGDOM_HEX_TILE_ALPHA_BOUNDS['chain_home_storm_2_hex_tile_v1.webp'], sources: { full: require('@incubator/art-world/hex/chain_home_storm_2_hex_tile_v1.webp'), medium: require('@incubator/art-world/hex/chain_home_storm_2_hex_tile_v1_512.webp'), thumb: require('@incubator/art-world/hex/chain_home_storm_2_hex_tile_v1_256.webp') } },
  'storm3': { alphaBounds: KINGDOM_HEX_TILE_ALPHA_BOUNDS['chain_home_storm_3_hex_tile_v1.webp'], sources: { full: require('@incubator/art-world/hex/chain_home_storm_3_hex_tile_v1.webp'), medium: require('@incubator/art-world/hex/chain_home_storm_3_hex_tile_v1_512.webp'), thumb: require('@incubator/art-world/hex/chain_home_storm_3_hex_tile_v1_256.webp') } },
  'bulwark1': { alphaBounds: KINGDOM_HEX_TILE_ALPHA_BOUNDS['chain_home_bulwark_1_hex_tile_v1.webp'], sources: { full: require('@incubator/art-world/hex/chain_home_bulwark_1_hex_tile_v1.webp'), medium: require('@incubator/art-world/hex/chain_home_bulwark_1_hex_tile_v1_512.webp'), thumb: require('@incubator/art-world/hex/chain_home_bulwark_1_hex_tile_v1_256.webp') } },
  'bulwark2': { alphaBounds: KINGDOM_HEX_TILE_ALPHA_BOUNDS['chain_home_bulwark_2_hex_tile_v1.webp'], sources: { full: require('@incubator/art-world/hex/chain_home_bulwark_2_hex_tile_v1.webp'), medium: require('@incubator/art-world/hex/chain_home_bulwark_2_hex_tile_v1_512.webp'), thumb: require('@incubator/art-world/hex/chain_home_bulwark_2_hex_tile_v1_256.webp') } },
  'bulwark3': { alphaBounds: KINGDOM_HEX_TILE_ALPHA_BOUNDS['chain_home_bulwark_3_hex_tile_v1.webp'], sources: { full: require('@incubator/art-world/hex/chain_home_bulwark_3_hex_tile_v1.webp'), medium: require('@incubator/art-world/hex/chain_home_bulwark_3_hex_tile_v1_512.webp'), thumb: require('@incubator/art-world/hex/chain_home_bulwark_3_hex_tile_v1_256.webp') } },
  'dew1': { alphaBounds: KINGDOM_HEX_TILE_ALPHA_BOUNDS['chain_home_dew_1_hex_tile_v1.webp'], sources: { full: require('@incubator/art-world/hex/chain_home_dew_1_hex_tile_v1.webp'), medium: require('@incubator/art-world/hex/chain_home_dew_1_hex_tile_v1_512.webp'), thumb: require('@incubator/art-world/hex/chain_home_dew_1_hex_tile_v1_256.webp') } },
  'dew2': { alphaBounds: KINGDOM_HEX_TILE_ALPHA_BOUNDS['chain_home_dew_2_hex_tile_v1.webp'], sources: { full: require('@incubator/art-world/hex/chain_home_dew_2_hex_tile_v1.webp'), medium: require('@incubator/art-world/hex/chain_home_dew_2_hex_tile_v1_512.webp'), thumb: require('@incubator/art-world/hex/chain_home_dew_2_hex_tile_v1_256.webp') } },
  'dew3': { alphaBounds: KINGDOM_HEX_TILE_ALPHA_BOUNDS['chain_home_dew_3_hex_tile_v1.webp'], sources: { full: require('@incubator/art-world/hex/chain_home_dew_3_hex_tile_v1.webp'), medium: require('@incubator/art-world/hex/chain_home_dew_3_hex_tile_v1_512.webp'), thumb: require('@incubator/art-world/hex/chain_home_dew_3_hex_tile_v1_256.webp') } },
  'lantern1': { alphaBounds: KINGDOM_HEX_TILE_ALPHA_BOUNDS['chain_home_lantern_1_hex_tile_v1.webp'], sources: { full: require('@incubator/art-world/hex/chain_home_lantern_1_hex_tile_v1.webp'), medium: require('@incubator/art-world/hex/chain_home_lantern_1_hex_tile_v1_512.webp'), thumb: require('@incubator/art-world/hex/chain_home_lantern_1_hex_tile_v1_256.webp') } },
  'lantern2': { alphaBounds: KINGDOM_HEX_TILE_ALPHA_BOUNDS['chain_home_lantern_2_hex_tile_v1.webp'], sources: { full: require('@incubator/art-world/hex/chain_home_lantern_2_hex_tile_v1.webp'), medium: require('@incubator/art-world/hex/chain_home_lantern_2_hex_tile_v1_512.webp'), thumb: require('@incubator/art-world/hex/chain_home_lantern_2_hex_tile_v1_256.webp') } },
  'lantern3': { alphaBounds: KINGDOM_HEX_TILE_ALPHA_BOUNDS['chain_home_lantern_3_hex_tile_v1.webp'], sources: { full: require('@incubator/art-world/hex/chain_home_lantern_3_hex_tile_v1.webp'), medium: require('@incubator/art-world/hex/chain_home_lantern_3_hex_tile_v1_512.webp'), thumb: require('@incubator/art-world/hex/chain_home_lantern_3_hex_tile_v1_256.webp') } },
} as const;
