// Generated by build-combat-v2-art.py; original sprites in art-source/katchimeras/combat-v2.
export const COMBAT_ITEM_ART = {
  'nature:bulwark:1': require('@incubator/art-merge-world/items/nature-bulwark-1.webp'),
  'nature:bulwark:2': require('@incubator/art-merge-world/items/nature-bulwark-2.webp'),
  'nature:bulwark:3': require('@incubator/art-merge-world/items/nature-bulwark-3.webp'),
  'nature:bulwark:4': require('@incubator/art-merge-world/items/nature-bulwark-4.webp'),
  'nature:bulwark:5': require('@incubator/art-merge-world/items/nature-bulwark-5.webp'),
  'nature:dew:1': require('@incubator/art-merge-world/items/nature-dew-1.webp'),
  'nature:dew:2': require('@incubator/art-merge-world/items/nature-dew-2.webp'),
  'nature:dew:3': require('@incubator/art-merge-world/items/nature-dew-3.webp'),
  'nature:dew:4': require('@incubator/art-merge-world/items/nature-dew-4.webp'),
  'nature:dew:5': require('@incubator/art-merge-world/items/nature-dew-5.webp'),
  'nature:lantern:1': require('@incubator/art-merge-world/items/nature-lantern-1.webp'),
  'nature:lantern:2': require('@incubator/art-merge-world/items/nature-lantern-2.webp'),
  'nature:lantern:3': require('@incubator/art-merge-world/items/nature-lantern-3.webp'),
  'nature:lantern:4': require('@incubator/art-merge-world/items/nature-lantern-4.webp'),
  'nature:lantern:5': require('@incubator/art-merge-world/items/nature-lantern-5.webp'),
};
export const COMBAT_GENERATOR_ART = {
  'ward-planter': require('@incubator/art-merge-world/generators/ward-planter.webp'),
  'dew-well': require('@incubator/art-merge-world/generators/dew-well.webp'),
  'lantern-post': require('@incubator/art-merge-world/generators/lantern-post.webp'),
};
export const COMBAT_ENEMY_ART = {
  'gunner': require('@incubator/art-cutouts/dark-wisps/gunner.webp'),
  'bomber': require('@incubator/art-cutouts/dark-wisps/bomber.webp'),
  'burrower': require('@incubator/art-cutouts/dark-wisps/burrower.webp'),
  'mirror': require('@incubator/art-cutouts/dark-wisps/mirror.webp'),
  'bramble-sentinel': require('@incubator/art-cutouts/dark-wisps/bramble-sentinel.webp'),
  'stormglass-matron': require('@incubator/art-cutouts/dark-wisps/stormglass-matron.webp'),
};
