// Generated by scripts/generate-hatchling-lod.py. Do not hand edit.
import type { ImageSourcePropType } from 'react-native';
import type { HomeVisualKey } from '@/types/home';
export { CREATURE_HATCHLING_ALPHA_BOUNDS, CREATURE_HATCHLING_ALPHA_THRESHOLD } from '@/constants/creature-hatchling-alpha-bounds.gen';
export type { CreatureHatchlingAlphaBounds } from '@/constants/creature-hatchling-alpha-bounds.gen';

export type CreatureHatchlingLod = 'full' | 'medium' | 'thumb';

export const CREATURE_HATCHLING_SOURCES: Record<CreatureHatchlingLod, Partial<Record<HomeVisualKey, ImageSourcePropType>>> = {
  full: {
    bedrotte: require('@incubator/art-hatchlings/bedrotte.png'),
    cheerlet: require('@incubator/art-hatchlings/cheerlet.png'),
    feastle: require('@incubator/art-hatchlings/feastle.png'),
    flickerbun: require('@incubator/art-hatchlings/flickerbun.png'),
    gatherglow: require('@incubator/art-hatchlings/gatherglow.png'),
    mossprout: require('@incubator/art-hatchlings/base-hatchling-v2.png'),
    pagelet: require('@incubator/art-hatchlings/pagelet.png'),
    relicoon: require('@incubator/art-hatchlings/relicoon.png'),
    shellio: require('@incubator/art-hatchlings/shellio.png'),
    skylo: require('@incubator/art-hatchlings/skylo.png'),
    steppling: require('@incubator/art-hatchlings/steppling.png'),
    tasklet: require('@incubator/art-hatchlings/tasklet.png'),
    vesperitt: require('@incubator/art-hatchlings/vesperitt.png'),
  },
  medium: {
    bedrotte: require('@incubator/art-hatchlings-lod/bedrotte_512.webp'),
    cheerlet: require('@incubator/art-hatchlings-lod/cheerlet_512.webp'),
    feastle: require('@incubator/art-hatchlings-lod/feastle_512.webp'),
    flickerbun: require('@incubator/art-hatchlings-lod/flickerbun_512.webp'),
    gatherglow: require('@incubator/art-hatchlings-lod/gatherglow_512.webp'),
    mossprout: require('@incubator/art-hatchlings-lod/mossprout_512.webp'),
    pagelet: require('@incubator/art-hatchlings-lod/pagelet_512.webp'),
    relicoon: require('@incubator/art-hatchlings-lod/relicoon_512.webp'),
    shellio: require('@incubator/art-hatchlings-lod/shellio_512.webp'),
    skylo: require('@incubator/art-hatchlings-lod/skylo_512.webp'),
    steppling: require('@incubator/art-hatchlings-lod/steppling_512.webp'),
    tasklet: require('@incubator/art-hatchlings-lod/tasklet_512.webp'),
    vesperitt: require('@incubator/art-hatchlings-lod/vesperitt_512.webp'),
  },
  thumb: {
    bedrotte: require('@incubator/art-hatchlings-lod/bedrotte_256.webp'),
    cheerlet: require('@incubator/art-hatchlings-lod/cheerlet_256.webp'),
    feastle: require('@incubator/art-hatchlings-lod/feastle_256.webp'),
    flickerbun: require('@incubator/art-hatchlings-lod/flickerbun_256.webp'),
    gatherglow: require('@incubator/art-hatchlings-lod/gatherglow_256.webp'),
    mossprout: require('@incubator/art-hatchlings-lod/mossprout_256.webp'),
    pagelet: require('@incubator/art-hatchlings-lod/pagelet_256.webp'),
    relicoon: require('@incubator/art-hatchlings-lod/relicoon_256.webp'),
    shellio: require('@incubator/art-hatchlings-lod/shellio_256.webp'),
    skylo: require('@incubator/art-hatchlings-lod/skylo_256.webp'),
    steppling: require('@incubator/art-hatchlings-lod/steppling_256.webp'),
    tasklet: require('@incubator/art-hatchlings-lod/tasklet_256.webp'),
    vesperitt: require('@incubator/art-hatchlings-lod/vesperitt_256.webp'),
  },
};
