// Generated by scripts/generate-katchimera-idle.py. Do not edit by hand.
import type { ImageSourcePropType } from 'react-native';

import type { HomeVisualKey } from '@/types/home';

const CREATURE_IDLE_ANIMATION_SOURCES: Partial<Record<HomeVisualKey, ImageSourcePropType>> = {
  'baristabbit': require('@incubator/art-animations/baristabbit-idle.webp'),
  'feastle': require('@incubator/art-animations/feastle-idle.webp'),
  'mossprout': require('@incubator/art-animations/mossprout-idle.webp'),
  'steppling': require('@incubator/art-animations/steppling-idle.webp'),
};

const CREATURE_IDLE_FALLBACK_SOURCES: Partial<Record<HomeVisualKey, ImageSourcePropType>> = {
  'baristabbit': require('@incubator/art-cutouts/baristabbit.png'),
  'feastle': require('@incubator/art-cutouts/feastle.png'),
  'mossprout': require('@incubator/art-cutouts/mossprout-standing.png'),
  'steppling': require('@incubator/art-cutouts/steppling-standing.png'),
};

export function resolveCreatureIdleAnimationSource(
  visualKey: HomeVisualKey,
): ImageSourcePropType | null {
  return CREATURE_IDLE_ANIMATION_SOURCES[visualKey] ?? null;
}

export function resolveCreatureIdleFallbackSource(
  visualKey: HomeVisualKey,
): ImageSourcePropType | null {
  return CREATURE_IDLE_FALLBACK_SOURCES[visualKey] ?? null;
}
