import type { ImageSourcePropType } from 'react-native';
import type { DarkWispLook } from './dark-wisp-looks';

// Generated by build-combat-wisp-lods.py.
export const DARK_WISP_LODS: Readonly<Record<DarkWispLook, { 128: ImageSourcePropType; 256: ImageSourcePropType }>> = {
  'bomber': { 128: require('@incubator/art-cutouts/dark-wisps/bomber-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/bomber-256.webp') },
  'bramble-sentinel': { 128: require('@incubator/art-cutouts/dark-wisps/bramble-sentinel-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/bramble-sentinel-256.webp') },
  'bulwark': { 128: require('@incubator/art-cutouts/dark-wisps/bulwark-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/bulwark-256.webp') },
  'burrower': { 128: require('@incubator/art-cutouts/dark-wisps/burrower-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/burrower-256.webp') },
  'caller': { 128: require('@incubator/art-cutouts/dark-wisps/caller-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/caller-256.webp') },
  'crawler': { 128: require('@incubator/art-cutouts/dark-wisps/crawler-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/crawler-256.webp') },
  'creeper': { 128: require('@incubator/art-cutouts/dark-wisps/creeper-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/creeper-256.webp') },
  'dasher': { 128: require('@incubator/art-cutouts/dark-wisps/dasher-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/dasher-256.webp') },
  'forgotten': { 128: require('@incubator/art-cutouts/dark-wisps/forgotten-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/forgotten-256.webp') },
  'frost': { 128: require('@incubator/art-cutouts/dark-wisps/frost-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/frost-256.webp') },
  'gunner': { 128: require('@incubator/art-cutouts/dark-wisps/gunner-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/gunner-256.webp') },
  'hollow': { 128: require('@incubator/art-cutouts/dark-wisps/hollow-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/hollow-256.webp') },
  'keeper': { 128: require('@incubator/art-cutouts/dark-wisps/keeper-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/keeper-256.webp') },
  'mender': { 128: require('@incubator/art-cutouts/dark-wisps/mender-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/mender-256.webp') },
  'mirror': { 128: require('@incubator/art-cutouts/dark-wisps/mirror-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/mirror-256.webp') },
  'mistling': { 128: require('@incubator/art-cutouts/dark-wisps/mistling-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/mistling-256.webp') },
  'nibbler': { 128: require('@incubator/art-cutouts/dark-wisps/nibbler-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/nibbler-256.webp') },
  'overgrowth': { 128: require('@incubator/art-cutouts/dark-wisps/overgrowth-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/overgrowth-256.webp') },
  'shrouder': { 128: require('@incubator/art-cutouts/dark-wisps/shrouder-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/shrouder-256.webp') },
  'snatcher': { 128: require('@incubator/art-cutouts/dark-wisps/snatcher-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/snatcher-256.webp') },
  'snuffer': { 128: require('@incubator/art-cutouts/dark-wisps/snuffer-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/snuffer-256.webp') },
  'splitter': { 128: require('@incubator/art-cutouts/dark-wisps/splitter-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/splitter-256.webp') },
  'stormglass-matron': { 128: require('@incubator/art-cutouts/dark-wisps/stormglass-matron-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/stormglass-matron-256.webp') },
  'thief': { 128: require('@incubator/art-cutouts/dark-wisps/thief-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/thief-256.webp') },
  'warden': { 128: require('@incubator/art-cutouts/dark-wisps/warden-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/warden-256.webp') },
  'weaver': { 128: require('@incubator/art-cutouts/dark-wisps/weaver-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/weaver-256.webp') },
};
