/* This file is generated by scripts/generate-egg-avatar-catalog.cjs. Do not edit.
 * Runtime imports contain optimized WebPs only; archival PNG masters stay tooling-only. */

export const EGG_AVATAR_READY_ASSETS = {
  body: {
    'classic': {
      fullSource: require('@incubator/art-egg-avatars/bases/classic.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/classic.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/classic.webp'),
    },
    'moss': {
      fullSource: require('@incubator/art-egg-avatars/bases/moss.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/moss.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/moss.webp'),
    },
    'tide': {
      fullSource: require('@incubator/art-egg-avatars/bases/tide.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/tide.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/tide.webp'),
    },
    'sunset': {
      fullSource: require('@incubator/art-egg-avatars/bases/sunset.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/sunset.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/sunset.webp'),
    },
    'starglow': {
      fullSource: require('@incubator/art-egg-avatars/bases/starglow.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/starglow.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/starglow.webp'),
    },
    'frost': {
      fullSource: require('@incubator/art-egg-avatars/bases/frost.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/frost.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/frost.webp'),
    },
    'ember': {
      fullSource: require('@incubator/art-egg-avatars/bases/ember.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/ember.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/ember.webp'),
    },
    'barista': {
      fullSource: require('@incubator/art-egg-avatars/bases/barista.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/barista.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/barista.webp'),
    },
    'robot': {
      fullSource: require('@incubator/art-egg-avatars/bases/robot.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/robot.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/robot.webp'),
    },
    'pumpkin': {
      fullSource: require('@incubator/art-egg-avatars/bases/pumpkin.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/pumpkin.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/pumpkin.webp'),
    },
    'honeycomb': {
      fullSource: require('@incubator/art-egg-avatars/bases/honeycomb.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/honeycomb.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/honeycomb.webp'),
    },
    'strawberry-cream': {
      fullSource: require('@incubator/art-egg-avatars/bases/strawberry-cream.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/strawberry-cream.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/strawberry-cream.webp'),
    },
    'blueberry-swirl': {
      fullSource: require('@incubator/art-egg-avatars/bases/blueberry-swirl.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/blueberry-swirl.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/blueberry-swirl.webp'),
    },
    'matcha-marble': {
      fullSource: require('@incubator/art-egg-avatars/bases/matcha-marble.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/matcha-marble.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/matcha-marble.webp'),
    },
    'wizard-robes': {
      fullSource: require('@incubator/art-egg-avatars/bases/wizard-robes.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/wizard-robes.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/wizard-robes.webp'),
    },
    'watermelon': {
      fullSource: require('@incubator/art-egg-avatars/bases/watermelon.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/watermelon.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/watermelon.webp'),
    },
    'porcelain-blue': {
      fullSource: require('@incubator/art-egg-avatars/bases/porcelain-blue.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/porcelain-blue.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/porcelain-blue.webp'),
    },
    'kintsugi': {
      fullSource: require('@incubator/art-egg-avatars/bases/kintsugi.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/kintsugi.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/kintsugi.webp'),
    },
    'football-kit': {
      fullSource: require('@incubator/art-egg-avatars/bases/football-kit.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/football-kit.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/football-kit.webp'),
    },
    'rose-quartz': {
      fullSource: require('@incubator/art-egg-avatars/bases/rose-quartz.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/rose-quartz.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/rose-quartz.webp'),
    },
    'cloud-puff': {
      fullSource: require('@incubator/art-egg-avatars/bases/cloud-puff.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/cloud-puff.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/cloud-puff.webp'),
    },
    'sunny-raincoat': {
      fullSource: require('@incubator/art-egg-avatars/bases/sunny-raincoat.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/sunny-raincoat.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/sunny-raincoat.webp'),
    },
    'aurora-shell': {
      fullSource: require('@incubator/art-egg-avatars/bases/aurora-shell.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/aurora-shell.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/aurora-shell.webp'),
    },
    'meadow-bloom': {
      fullSource: require('@incubator/art-egg-avatars/bases/meadow-bloom.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/meadow-bloom.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/meadow-bloom.webp'),
    },
    'toadstool-speckle': {
      fullSource: require('@incubator/art-egg-avatars/bases/toadstool-speckle.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/toadstool-speckle.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/toadstool-speckle.webp'),
    },
    'cactus-bud': {
      fullSource: require('@incubator/art-egg-avatars/bases/cactus-bud.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/cactus-bud.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/cactus-bud.webp'),
    },
    'coral-cove': {
      fullSource: require('@incubator/art-egg-avatars/bases/coral-cove.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/coral-cove.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/coral-cove.webp'),
    },
    'honeybee-stripe': {
      fullSource: require('@incubator/art-egg-avatars/bases/honeybee-stripe.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/honeybee-stripe.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/honeybee-stripe.webp'),
    },
    'knight-tunic': {
      fullSource: require('@incubator/art-egg-avatars/bases/knight-tunic.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/knight-tunic.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/knight-tunic.webp'),
    },
    'astronaut-suit': {
      fullSource: require('@incubator/art-egg-avatars/bases/astronaut-suit.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/astronaut-suit.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/astronaut-suit.webp'),
    },
    'dragon-scale': {
      fullSource: require('@incubator/art-egg-avatars/bases/dragon-scale.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/dragon-scale.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/dragon-scale.webp'),
    },
    'axolotl-frill': {
      fullSource: require('@incubator/art-egg-avatars/bases/axolotl-frill.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/axolotl-frill.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/axolotl-frill.webp'),
    },
    'penguin-tux': {
      fullSource: require('@incubator/art-egg-avatars/bases/penguin-tux.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/penguin-tux.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/penguin-tux.webp'),
    },
    'calico-patch': {
      fullSource: require('@incubator/art-egg-avatars/bases/calico-patch.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/calico-patch.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/calico-patch.webp'),
    },
    'explorer-vest': {
      fullSource: require('@incubator/art-egg-avatars/bases/explorer-vest.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/explorer-vest.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/explorer-vest.webp'),
    },
    'cozy-quilt': {
      fullSource: require('@incubator/art-egg-avatars/bases/cozy-quilt.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/cozy-quilt.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/cozy-quilt.webp'),
    },
    'royal-robe': {
      fullSource: require('@incubator/art-egg-avatars/bases/royal-robe.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/royal-robe.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/royal-robe.webp'),
    },
    'party-outfit': {
      fullSource: require('@incubator/art-egg-avatars/bases/party-outfit.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/party-outfit.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/party-outfit.webp'),
    },
    'disco-egg': {
      fullSource: require('@incubator/art-egg-avatars/bases/disco-egg.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/disco-egg.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/disco-egg.webp'),
    },
    'storybook-ink': {
      fullSource: require('@incubator/art-egg-avatars/bases/storybook-ink.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/storybook-ink.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/storybook-ink.webp'),
    },
    'sailor-uniform': {
      fullSource: require('@incubator/art-egg-avatars/bases/sailor-uniform.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/sailor-uniform.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/sailor-uniform.webp'),
    },
    'chef-apron': {
      fullSource: require('@incubator/art-egg-avatars/bases/chef-apron.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/chef-apron.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/chef-apron.webp'),
    },
    'superhero-suit': {
      fullSource: require('@incubator/art-egg-avatars/bases/superhero-suit.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/superhero-suit.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/superhero-suit.webp'),
    },
    'cozy-pajamas': {
      fullSource: require('@incubator/art-egg-avatars/bases/cozy-pajamas.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/cozy-pajamas.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/cozy-pajamas.webp'),
    },
    'garden-overalls': {
      fullSource: require('@incubator/art-egg-avatars/bases/garden-overalls.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/garden-overalls.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/garden-overalls.webp'),
    },
    'detective-coat': {
      fullSource: require('@incubator/art-egg-avatars/bases/detective-coat.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/detective-coat.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/detective-coat.webp'),
    },
    'pirate-coat': {
      fullSource: require('@incubator/art-egg-avatars/bases/pirate-coat.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/pirate-coat.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/pirate-coat.webp'),
    },
    'ballet-wrap': {
      fullSource: require('@incubator/art-egg-avatars/bases/ballet-wrap.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/ballet-wrap.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/ballet-wrap.webp'),
    },
    'racing-suit': {
      fullSource: require('@incubator/art-egg-avatars/bases/racing-suit.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/racing-suit.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/racing-suit.webp'),
    },
    'artist-smock': {
      fullSource: require('@incubator/art-egg-avatars/bases/artist-smock.webp'),
      highSource: require('@incubator/art-egg-avatars/bases/high/artist-smock.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/bases/thumbnails/artist-smock.webp'),
    },
  },
  face: {
    'classic-smile': {
      fullSource: require('@incubator/art-egg-avatars/faces/classic-smile.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/classic-smile.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/classic-smile.webp'),
    },
    'happy-squint': {
      fullSource: require('@incubator/art-egg-avatars/faces/happy-squint.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/happy-squint.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/happy-squint.webp'),
    },
    'sleepy': {
      fullSource: require('@incubator/art-egg-avatars/faces/sleepy.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/sleepy.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/sleepy.webp'),
    },
    'curious': {
      fullSource: require('@incubator/art-egg-avatars/faces/curious.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/curious.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/curious.webp'),
    },
    'determined': {
      fullSource: require('@incubator/art-egg-avatars/faces/determined.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/determined.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/determined.webp'),
    },
    'gentle-smile': {
      fullSource: require('@incubator/art-egg-avatars/faces/gentle-smile.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/gentle-smile.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/gentle-smile.webp'),
    },
    'big-grin': {
      fullSource: require('@incubator/art-egg-avatars/faces/big-grin.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/big-grin.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/big-grin.webp'),
    },
    'single-wink': {
      fullSource: require('@incubator/art-egg-avatars/faces/single-wink.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/single-wink.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/single-wink.webp'),
    },
    'heart-eyes': {
      fullSource: require('@incubator/art-egg-avatars/faces/heart-eyes.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/heart-eyes.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/heart-eyes.webp'),
    },
    'starry-eyed': {
      fullSource: require('@incubator/art-egg-avatars/faces/starry-eyed.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/starry-eyed.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/starry-eyed.webp'),
    },
    'sparkle-awe': {
      fullSource: require('@incubator/art-egg-avatars/faces/sparkle-awe.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/sparkle-awe.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/sparkle-awe.webp'),
    },
    'shy-glance': {
      fullSource: require('@incubator/art-egg-avatars/faces/shy-glance.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/shy-glance.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/shy-glance.webp'),
    },
    'bashful-smile': {
      fullSource: require('@incubator/art-egg-avatars/faces/bashful-smile.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/bashful-smile.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/bashful-smile.webp'),
    },
    'belly-laugh': {
      fullSource: require('@incubator/art-egg-avatars/faces/belly-laugh.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/belly-laugh.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/belly-laugh.webp'),
    },
    'tiny-giggle': {
      fullSource: require('@incubator/art-egg-avatars/faces/tiny-giggle.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/tiny-giggle.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/tiny-giggle.webp'),
    },
    'cute-pout': {
      fullSource: require('@incubator/art-egg-avatars/faces/cute-pout.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/cute-pout.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/cute-pout.webp'),
    },
    'grumpy-cute': {
      fullSource: require('@incubator/art-egg-avatars/faces/grumpy-cute.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/grumpy-cute.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/grumpy-cute.webp'),
    },
    'little-worried': {
      fullSource: require('@incubator/art-egg-avatars/faces/little-worried.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/little-worried.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/little-worried.webp'),
    },
    'happy-tears': {
      fullSource: require('@incubator/art-egg-avatars/faces/happy-tears.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/happy-tears.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/happy-tears.webp'),
    },
    'soft-sad': {
      fullSource: require('@incubator/art-egg-avatars/faces/soft-sad.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/soft-sad.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/soft-sad.webp'),
    },
    'big-surprise': {
      fullSource: require('@incubator/art-egg-avatars/faces/big-surprise.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/big-surprise.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/big-surprise.webp'),
    },
    'dizzy-swirls': {
      fullSource: require('@incubator/art-egg-avatars/faces/dizzy-swirls.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/dizzy-swirls.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/dizzy-swirls.webp'),
    },
    'mischief': {
      fullSource: require('@incubator/art-egg-avatars/faces/mischief.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/mischief.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/mischief.webp'),
    },
    'smug-smirk': {
      fullSource: require('@incubator/art-egg-avatars/faces/smug-smirk.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/smug-smirk.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/smug-smirk.webp'),
    },
    'laser-focus': {
      fullSource: require('@incubator/art-egg-avatars/faces/laser-focus.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/laser-focus.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/laser-focus.webp'),
    },
    'daydream': {
      fullSource: require('@incubator/art-egg-avatars/faces/daydream.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/daydream.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/daydream.webp'),
    },
    'sleepy-yawn': {
      fullSource: require('@incubator/art-egg-avatars/faces/sleepy-yawn.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/sleepy-yawn.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/sleepy-yawn.webp'),
    },
    'tongue-out': {
      fullSource: require('@incubator/art-egg-avatars/faces/tongue-out.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/tongue-out.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/tongue-out.webp'),
    },
    'kissy-face': {
      fullSource: require('@incubator/art-egg-avatars/faces/kissy-face.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/kissy-face.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/kissy-face.webp'),
    },
    'heroic-glint': {
      fullSource: require('@incubator/art-egg-avatars/faces/heroic-glint.webp'),
      highSource: require('@incubator/art-egg-avatars/faces/high/heroic-glint.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/faces/thumbnails/heroic-glint.webp'),
    },
  },
  hat: {
    'moss-sprout': {
      fullSource: require('@incubator/art-egg-avatars/hats/moss-sprout.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/moss-sprout.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/moss-sprout.webp'),
    },
    'barista-beret': {
      fullSource: require('@incubator/art-egg-avatars/hats/barista-beret.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/barista-beret.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/barista-beret.webp'),
    },
    'pumpkin-vine-crown': {
      fullSource: require('@incubator/art-egg-avatars/hats/pumpkin-vine-crown.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/pumpkin-vine-crown.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/pumpkin-vine-crown.webp'),
    },
    'cozy-beanie': {
      fullSource: require('@incubator/art-egg-avatars/hats/cozy-beanie.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/cozy-beanie.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/cozy-beanie.webp'),
    },
    'stargazer-hat': {
      fullSource: require('@incubator/art-egg-avatars/hats/stargazer-hat.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/stargazer-hat.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/stargazer-hat.webp'),
    },
    'tiny-golden-crown': {
      fullSource: require('@incubator/art-egg-avatars/hats/tiny-golden-crown.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/tiny-golden-crown.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/tiny-golden-crown.webp'),
    },
    'acorn-cap': {
      fullSource: require('@incubator/art-egg-avatars/hats/acorn-cap.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/acorn-cap.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/acorn-cap.webp'),
    },
    'daisy-crown': {
      fullSource: require('@incubator/art-egg-avatars/hats/daisy-crown.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/daisy-crown.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/daisy-crown.webp'),
    },
    'mushroom-cap': {
      fullSource: require('@incubator/art-egg-avatars/hats/mushroom-cap.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/mushroom-cap.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/mushroom-cap.webp'),
    },
    'cloud-cap': {
      fullSource: require('@incubator/art-egg-avatars/hats/cloud-cap.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/cloud-cap.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/cloud-cap.webp'),
    },
    'floppy-sunhat': {
      fullSource: require('@incubator/art-egg-avatars/hats/floppy-sunhat.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/floppy-sunhat.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/floppy-sunhat.webp'),
    },
    'party-cone': {
      fullSource: require('@incubator/art-egg-avatars/hats/party-cone.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/party-cone.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/party-cone.webp'),
    },
    'chef-toque': {
      fullSource: require('@incubator/art-egg-avatars/hats/chef-toque.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/chef-toque.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/chef-toque.webp'),
    },
    'sailor-cap': {
      fullSource: require('@incubator/art-egg-avatars/hats/sailor-cap.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/sailor-cap.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/sailor-cap.webp'),
    },
    'explorer-cap': {
      fullSource: require('@incubator/art-egg-avatars/hats/explorer-cap.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/explorer-cap.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/explorer-cap.webp'),
    },
    'detective-deerstalker': {
      fullSource: require('@incubator/art-egg-avatars/hats/detective-deerstalker.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/detective-deerstalker.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/detective-deerstalker.webp'),
    },
    'moon-bonnet': {
      fullSource: require('@incubator/art-egg-avatars/hats/moon-bonnet.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/moon-bonnet.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/moon-bonnet.webp'),
    },
    'pancake-stack': {
      fullSource: require('@incubator/art-egg-avatars/hats/pancake-stack.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/pancake-stack.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/pancake-stack.webp'),
    },
    'strawberry-topper': {
      fullSource: require('@incubator/art-egg-avatars/hats/strawberry-topper.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/strawberry-topper.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/strawberry-topper.webp'),
    },
    'blueberry-cap': {
      fullSource: require('@incubator/art-egg-avatars/hats/blueberry-cap.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/blueberry-cap.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/blueberry-cap.webp'),
    },
    'watermelon-visor': {
      fullSource: require('@incubator/art-egg-avatars/hats/watermelon-visor.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/watermelon-visor.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/watermelon-visor.webp'),
    },
    'duckling-cap': {
      fullSource: require('@incubator/art-egg-avatars/hats/duckling-cap.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/duckling-cap.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/duckling-cap.webp'),
    },
    'frog-hood': {
      fullSource: require('@incubator/art-egg-avatars/hats/frog-hood.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/frog-hood.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/frog-hood.webp'),
    },
    'cat-ear-headband': {
      fullSource: require('@incubator/art-egg-avatars/hats/cat-ear-headband.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/cat-ear-headband.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/cat-ear-headband.webp'),
    },
    'bunny-ears': {
      fullSource: require('@incubator/art-egg-avatars/hats/bunny-ears.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/bunny-ears.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/bunny-ears.webp'),
    },
    'bear-hood': {
      fullSource: require('@incubator/art-egg-avatars/hats/bear-hood.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/bear-hood.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/bear-hood.webp'),
    },
    'dragon-horns': {
      fullSource: require('@incubator/art-egg-avatars/hats/dragon-horns.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/dragon-horns.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/dragon-horns.webp'),
    },
    'dino-spikes': {
      fullSource: require('@incubator/art-egg-avatars/hats/dino-spikes.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/dino-spikes.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/dino-spikes.webp'),
    },
    'astronaut-helmet': {
      fullSource: require('@incubator/art-egg-avatars/hats/astronaut-helmet.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/astronaut-helmet.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/astronaut-helmet.webp'),
    },
    'knight-circlet': {
      fullSource: require('@incubator/art-egg-avatars/hats/knight-circlet.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/knight-circlet.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/knight-circlet.webp'),
    },
    'pirate-tricorn': {
      fullSource: require('@incubator/art-egg-avatars/hats/pirate-tricorn.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/pirate-tricorn.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/pirate-tricorn.webp'),
    },
    'graduation-cap': {
      fullSource: require('@incubator/art-egg-avatars/hats/graduation-cap.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/graduation-cap.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/graduation-cap.webp'),
    },
    'cozy-headphones': {
      fullSource: require('@incubator/art-egg-avatars/hats/cozy-headphones.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/cozy-headphones.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/cozy-headphones.webp'),
    },
    'fluffy-earmuffs': {
      fullSource: require('@incubator/art-egg-avatars/hats/fluffy-earmuffs.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/fluffy-earmuffs.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/fluffy-earmuffs.webp'),
    },
    'soft-halo': {
      fullSource: require('@incubator/art-egg-avatars/hats/soft-halo.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/soft-halo.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/soft-halo.webp'),
    },
    'woodland-antlers': {
      fullSource: require('@incubator/art-egg-avatars/hats/woodland-antlers.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/woodland-antlers.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/woodland-antlers.webp'),
    },
    'snowflake-tiara': {
      fullSource: require('@incubator/art-egg-avatars/hats/snowflake-tiara.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/snowflake-tiara.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/snowflake-tiara.webp'),
    },
    'rainbow-arch': {
      fullSource: require('@incubator/art-egg-avatars/hats/rainbow-arch.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/rainbow-arch.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/rainbow-arch.webp'),
    },
    'blossom-crown': {
      fullSource: require('@incubator/art-egg-avatars/hats/blossom-crown.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/blossom-crown.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/blossom-crown.webp'),
    },
    'sleepy-nightcap': {
      fullSource: require('@incubator/art-egg-avatars/hats/sleepy-nightcap.webp'),
      highSource: require('@incubator/art-egg-avatars/hats/high/sleepy-nightcap.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/hats/thumbnails/sleepy-nightcap.webp'),
    },
  },
  held: {
    'warm-lantern': {
      fullSource: require('@incubator/art-egg-avatars/held/warm-lantern.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/warm-lantern.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/warm-lantern.webp'),
    },
    'daisy-posy': {
      fullSource: require('@incubator/art-egg-avatars/held/daisy-posy.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/daisy-posy.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/daisy-posy.webp'),
    },
    'tiny-storybook': {
      fullSource: require('@incubator/art-egg-avatars/held/tiny-storybook.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/tiny-storybook.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/tiny-storybook.webp'),
    },
    'star-wand': {
      fullSource: require('@incubator/art-egg-avatars/held/star-wand.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/star-wand.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/star-wand.webp'),
    },
    'cozy-mug': {
      fullSource: require('@incubator/art-egg-avatars/held/cozy-mug.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/cozy-mug.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/cozy-mug.webp'),
    },
    'adventure-pennant': {
      fullSource: require('@incubator/art-egg-avatars/held/adventure-pennant.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/adventure-pennant.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/adventure-pennant.webp'),
    },
    'tiny-umbrella': {
      fullSource: require('@incubator/art-egg-avatars/held/tiny-umbrella.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/tiny-umbrella.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/tiny-umbrella.webp'),
    },
    'watering-can': {
      fullSource: require('@incubator/art-egg-avatars/held/watering-can.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/watering-can.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/watering-can.webp'),
    },
    'magnifying-glass': {
      fullSource: require('@incubator/art-egg-avatars/held/magnifying-glass.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/magnifying-glass.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/magnifying-glass.webp'),
    },
    'berry-lollipop': {
      fullSource: require('@incubator/art-egg-avatars/held/berry-lollipop.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/berry-lollipop.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/berry-lollipop.webp'),
    },
    'paintbrush': {
      fullSource: require('@incubator/art-egg-avatars/held/paintbrush.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/paintbrush.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/paintbrush.webp'),
    },
    'toy-sword': {
      fullSource: require('@incubator/art-egg-avatars/held/toy-sword.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/toy-sword.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/toy-sword.webp'),
    },
    'little-guitar': {
      fullSource: require('@incubator/art-egg-avatars/held/little-guitar.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/little-guitar.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/little-guitar.webp'),
    },
    'seashell': {
      fullSource: require('@incubator/art-egg-avatars/held/seashell.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/seashell.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/seashell.webp'),
    },
    'potion-bottle': {
      fullSource: require('@incubator/art-egg-avatars/held/potion-bottle.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/potion-bottle.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/potion-bottle.webp'),
    },
    'snow-globe': {
      fullSource: require('@incubator/art-egg-avatars/held/snow-globe.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/snow-globe.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/snow-globe.webp'),
    },
    'plush-bunny': {
      fullSource: require('@incubator/art-egg-avatars/held/plush-bunny.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/plush-bunny.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/plush-bunny.webp'),
    },
    'picnic-basket': {
      fullSource: require('@incubator/art-egg-avatars/held/picnic-basket.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/picnic-basket.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/picnic-basket.webp'),
    },
    'telescope': {
      fullSource: require('@incubator/art-egg-avatars/held/telescope.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/telescope.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/telescope.webp'),
    },
    'flower-balloon': {
      fullSource: require('@incubator/art-egg-avatars/held/flower-balloon.webp'),
      highSource: require('@incubator/art-egg-avatars/held/high/flower-balloon.webp'),
      thumbnailSource: require('@incubator/art-egg-avatars/held/thumbnails/flower-balloon.webp'),
    },
  },
} as const;
