import type { ImageSourcePropType } from 'react-native';
import { type HeartwoodBuildingId, type HeartwoodBuildingLook, heartwoodBuildingLook } from '@/constants/heartwood-buildings';

/**
 * Each building's three looks, in the Wisp Lantern's style (it stands on the patch beside them). Generated by
 * `scripts/generate-heartwood-buildings.py`: a later look is made from the one before, so a building stays itself as
 * it grows. Sources and prompts are kept in `art-source/katchimeras/heartwood-buildings-v2`.
 */
export const HEARTWOOD_BUILDING_ART: Record<HeartwoodBuildingId, readonly [ImageSourcePropType, ImageSourcePropType, ImageSourcePropType]> = {
  'dew-spring': [
    require('@incubator/art-world/heartwood-buildings/dew_spring_1.webp'),
    require('@incubator/art-world/heartwood-buildings/dew_spring_2.webp'),
    require('@incubator/art-world/heartwood-buildings/dew_spring_3.webp'),
  ],
  'seed-nursery': [
    require('@incubator/art-world/heartwood-buildings/seed_nursery_1.webp'),
    require('@incubator/art-world/heartwood-buildings/seed_nursery_2.webp'),
    require('@incubator/art-world/heartwood-buildings/seed_nursery_3.webp'),
  ],
  'root-cellar': [
    require('@incubator/art-world/heartwood-buildings/root_cellar_1.webp'),
    require('@incubator/art-world/heartwood-buildings/root_cellar_2.webp'),
    require('@incubator/art-world/heartwood-buildings/root_cellar_3.webp'),
  ],
  'garden-stall': [
    require('@incubator/art-world/heartwood-buildings/garden_stall_1.webp'),
    require('@incubator/art-world/heartwood-buildings/garden_stall_2.webp'),
    require('@incubator/art-world/heartwood-buildings/garden_stall_3.webp'),
  ],
};

/** The picture of a building at a level (an unbuilt one shows its first look). */
export function heartwoodBuildingArt(id: HeartwoodBuildingId, level: number): ImageSourcePropType {
  return HEARTWOOD_BUILDING_ART[id][heartwoodBuildingLook(level) as HeartwoodBuildingLook];
}
