// Generated by scripts/generate-exploration-background.py. Do not hand edit.

export const TODAY_KATCHIMERA_EXPLORATION_BACKGROUND_KEYS = [
  'bedrotte',
  'cheerlet',
  'feastle',
  'flickerbun',
  'mossprout',
  'pagelet',
  'relicoon',
  'skylo',
  'steppling',
  'tasklet'
] as const;

export type TodayKatchimeraExplorationBackgroundKey =
  (typeof TODAY_KATCHIMERA_EXPLORATION_BACKGROUND_KEYS)[number];

export type TodayExplorationBackgroundKey =
  | 'home'
  | TodayKatchimeraExplorationBackgroundKey;
