/* This file is generated by scripts/generate-today-full-spread.py. */
import type { ImageSourcePropType } from 'react-native';

import type { HomeVisualKey } from '@/types/home';

export type BundledTodayFullSpreadScene = {
  id: string;
  source: ImageSourcePropType;
};

export const TODAY_FULL_SPREAD_SCENE_SOURCES: Partial<
  Record<HomeVisualKey, BundledTodayFullSpreadScene>
> = {
};
