"""Generate density tiers for the authored wisp cutouts and their Metro source map."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[3]
ART = ROOT / 'art/assets/images/katchimeras/cutouts/dark-wisps'
lines = ["import type { ImageSourcePropType } from 'react-native';", "import type { DarkWispLook } from './dark-wisp-looks';", "", "// Generated by build-combat-wisp-lods.py.", "export const DARK_WISP_LODS: Readonly<Record<DarkWispLook, { 128: ImageSourcePropType; 256: ImageSourcePropType }>> = {"]
for source in sorted(ART.glob('*.webp')):
    if source.stem.endswith(('-128', '-256')):
        continue
    with Image.open(source) as image:
        for edge in (128, 256):
            image.resize((edge, edge), Image.Resampling.LANCZOS).save(ART / f'{source.stem}-{edge}.webp', quality=90)
    lines.append(f"  '{source.stem}': {{ 128: require('@incubator/art-cutouts/dark-wisps/{source.stem}-128.webp'), 256: require('@incubator/art-cutouts/dark-wisps/{source.stem}-256.webp') }},")
lines.append('};')
(ROOT / 'apps/katchimeras/constants/dark-wisp-lods.gen.ts').write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f'Generated {len(lines) - 6} wisp resolution sets')
