"""Package approved combat sprites with alpha; emit static Metro mappings."""
from pathlib import Path
import json
from PIL import Image

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / 'art-source/katchimeras/combat-v2'
ART = ROOT / 'art/assets/images/katchimeras'
APP = ROOT / 'apps/katchimeras/constants'
ENEMIES = ['gunner', 'bomber', 'burrower', 'mirror', 'bramble-sentinel', 'stormglass-matron']
GENERATORS = ['ward-planter', 'dew-well', 'lantern-post']
manifest = []
for path in sorted(SOURCE.glob('*.png')):
    name = path.stem
    folder = 'cutouts/dark-wisps' if name in ENEMIES else 'merge-world/generators' if name in GENERATORS else 'merge-world/items'
    target = ART / folder / f'{name}.webp'
    image = Image.open(path).convert('RGBA')
    if image.getchannel('A').getextrema()[0] == 255:
        raise ValueError(f'{path.name} has no transparent background')
    image.thumbnail((384, 384), Image.Resampling.LANCZOS)
    canvas = Image.new('RGBA', (384, 384))
    canvas.alpha_composite(image, ((384-image.width)//2, (384-image.height)//2))
    canvas.save(target, quality=91, method=6)
    manifest.append({'id': name, 'path': str(target.relative_to(ROOT)).replace('\\', '/'), 'bytes': target.stat().st_size})

lines = ["// Generated by build-combat-v2-art.py; original sprites in art-source/katchimeras/combat-v2.", 'export const COMBAT_ITEM_ART = {']
for chain in ['bulwark', 'dew', 'lantern']:
    for tier in range(1, 6):
        lines.append(f"  'nature:{chain}:{tier}': require('@incubator/art-merge-world/items/nature-{chain}-{tier}.webp'),")
lines += ['};', 'export const COMBAT_GENERATOR_ART = {']
for name in GENERATORS:
    lines.append(f"  '{name}': require('@incubator/art-merge-world/generators/{name}.webp'),")
lines += ['};', 'export const COMBAT_ENEMY_ART = {']
for name in ENEMIES:
    lines.append(f"  '{name}': require('@incubator/art-cutouts/dark-wisps/{name}.webp'),")
lines += ['};', '']
(APP / 'combat-art.gen.ts').write_text('\n'.join(lines), encoding='utf-8')
(SOURCE / 'runtime-manifest.json').write_text(json.dumps(manifest, indent=2) + '\n', encoding='utf-8')
print(f'Packaged {len(manifest)} sprites ({sum(x["bytes"] for x in manifest)} bytes)')
