// Generated by scripts/generate-note-route-schema.ts. Do not edit by hand.
#if canImport(FoundationModels)
import FoundationModels

@available(iOS 26.0, *)
enum JournalNoteRouteCatalog {
  static let schemaVersion = "4"
  static let promptTaxonomy = """
went_somewhere.park: Places, trips and time away from home: Park or green space. Examples: “I went to park or green space”.
went_somewhere.city: Places, trips and time away from home: City or town. Examples: “I went to city or town”.
went_somewhere.beach: Places, trips and time away from home: Beach or coast. Examples: “I went to beach or coast”.
went_somewhere.forest: Places, trips and time away from home: Forest or trail. Examples: “I went to forest or trail”.
went_somewhere.garden: Places, trips and time away from home: Garden. Examples: “I went to garden”.
went_somewhere.museum: A real visit to a museum, gallery, exhibition venue, or cultural collection. Examples: “I went to the Natural History Museum”; “Visited an art gallery”. Not: I looked at a painting online.
went_somewhere.cafe: Places, trips and time away from home: Cafe. Examples: “I went to a cafe”; “Stopped at a coffee shop”.
went_somewhere.restaurant: Places, trips and time away from home: Restaurant. Examples: “We went to a restaurant”; “Dinner at a diner”.
went_somewhere.street: Places, trips and time away from home: Street or neighbourhood. Examples: “I went to street or neighbourhood”.
went_somewhere.home: Places, trips and time away from home: Home. Examples: “I went to home”.
went_somewhere.travel: A day out, destination visit, or travel where the place is the main memory. Examples: “We took a day trip to York”.
went_somewhere.other_place: Places, trips and time away from home: Somewhere else. Examples: “I went to somewhere else”.
food.meal: Meals, snacks, coffee and drinks: A meal. Examples: “I had ramen for dinner”; “We ate lunch together”.
food.snack: Meals, snacks, coffee and drinks: A snack. Examples: “I had a snack”; “Ate some crisps”.
food.dessert: Meals, snacks, coffee and drinks: Dessert. Examples: “I ate birthday cake”; “We had dessert”. Not: It was my birthday.
food.coffee: Meals, snacks, coffee and drinks: Coffee. Examples: “I had a coffee”; “Drank a latte”.
food.tea: Meals, snacks, coffee and drinks: Tea. Examples: “I drank tea”; “Had a cup of tea”.
food.drink: Meals, snacks, coffee and drinks: Another drink. Examples: “I had a cocktail”; “Drank some juice”.
food.cooking: Meals, snacks, coffee and drinks: Cooking or baking. Examples: “I cooked dinner”; “I baked my son’s birthday cake”. Not: It was my son’s birthday.
food.other_food: Meals, snacks, coffee and drinks: Something else. Examples: “I had something else”.
studio.book: Books, films, games, music and art: Book or audiobook. Examples: “I read a book”; “I listened to an audiobook”.
studio.film: Books, films, games, music and art: Film. Examples: “I watched a movie”; “I saw a film at the cinema”. Not: I filmed a video.
studio.show: Books, films, games, music and art: TV show or series. Examples: “I watched a TV show”; “I finished a series”.
studio.game: Books, films, games, music and art: Video game. Examples: “I played a video game”; “Finished a console game”.
studio.music: Books, films, games, music and art: Music or album. Examples: “I listened to an album”; “I discovered a song”.
studio.podcast: Books, films, games, music and art: Podcast. Examples: “I listened to a podcast”.
studio.art: Art or an exhibition as the work being experienced, when a physical venue visit is not the main memory. Examples: “I saw an inspiring sculpture”; “The exhibition stayed with me”.
studio.other_media: Books, films, games, music and art: News, live sport or other. Examples: “I watched the football match”; “I watched the news”; “I watched an online video”.
movement.walk: Walks, workouts, sport and travel: Walk. Examples: “I went for a walk”; “I took a long stroll”.
movement.run: Walks, workouts, sport and travel: Run. Examples: “I went for a run”; “I jogged this morning”.
movement.cycle: Walks, workouts, sport and travel: Cycle. Examples: “I went cycling”; “I rode my bike”.
movement.workout: Walks, workouts, sport and travel: Workout or gym. Examples: “I worked out at the gym”; “I did a fitness class”.
movement.sport: Walks, workouts, sport and travel: Sport. Examples: “I played football”; “I had tennis practice”. Not: I watched the football match.
movement.hike: Walks, workouts, sport and travel: Hike. Examples: “I went for a hike”; “We hiked a trail”.
movement.errands: Walks, workouts, sport and travel: Errands. Examples: “I ran errands”; “I went shopping”.
movement.commute: Walks, workouts, sport and travel: Commute or transit. Examples: “I commuted by train”; “I drove to work”.
movement.travel: Physical movement between destinations when the journey or travelling is the main activity. Examples: “I spent the day travelling”; “I flew to London”.
movement.mixed: Walks, workouts, sport and travel: Mixed activity. Examples: “I did a mix of walking and cycling”.
people.partner: Company, connection or time by yourself: Partner. Examples: “I spent time with my partner”; “Dinner with my wife”.
people.my_child: Company, connection or time by yourself: My child. Examples: “I played with my son”; “Spent time with my daughter”. Not: It was my son’s birthday.
people.family: Company, connection or time by yourself: Family. Examples: “I visited my family”; “Family time at home”.
people.friends: Company, connection or time by yourself: Friends. Examples: “I met my friends”; “Caught up with a friend”.
people.group: Company, connection or time by yourself: A group or gathering. Examples: “I went to a community gathering”; “Spent time with a group”.
people.someone_new: Company, connection or time by yourself: Someone new. Examples: “I met someone new”; “I was introduced to a new person”.
people.pet: Company, connection or time by yourself: A pet. Examples: “I played with my dog”; “I cuddled my cat”.
people.solo: Company, connection or time by yourself: Me / time by myself. Examples: “I spent time by myself”; “I had some time alone”.
people.someone_else: Company, connection or time by yourself: Someone else. Examples: “I spoke with a colleague”; “I spent time with someone”.
work.focus: Work, learning and creative progress: Focused work. Examples: “I did focused work”; “I concentrated on a task”.
work.office: Work, learning and creative progress: Office or workday. Examples: “I had a day at the office”; “It was a busy workday”.
work.learning: Work, learning and creative progress: Studying or learning. Examples: “I studied for an exam”; “I learned something new”.
work.planning: Work, learning and creative progress: Planning. Examples: “I planned my week”; “I made a project plan”.
work.creative: Work, learning and creative progress: Creative project. Examples: “I worked on a creative project”; “I made a painting”.
work.admin: Work, learning and creative progress: Personal admin. Examples: “I sorted some paperwork”; “I did personal admin”.
work.progress: Work, learning and creative progress: Achievement or progress. Examples: “I made progress on my project”; “I finished an important task”.
work.other_work: Work, learning and creative progress: Something else. Examples: “I did something else”.
big_event.birthday: A birthday event or celebration belonging to the user or another person. Examples: “It’s my birthday”; “It was my son’s birthday”; “We went to Sarah’s birthday party”. Not: I ate birthday cake; I baked a birthday cake.
big_event.anniversary: Milestones and days worth remembering: Anniversary. Examples: “It was our anniversary”; “We celebrated an anniversary”.
big_event.firstTime: Milestones and days worth remembering: A first. Examples: “It was my first day at school”; “I tried skiing for the first time”.
big_event.holiday: Milestones and days worth remembering: Holiday. Examples: “We celebrated Christmas”; “It was Eid”.
big_event.trip: A memorable trip or holiday treated as a life event rather than ordinary travel. Examples: “We started our holiday in Spain”; “Our family trip began today”.
big_event.achievement: Milestones and days worth remembering: Achievement. Examples: “I won an award”; “I passed my exam”.
big_event.baby: Milestones and days worth remembering: New baby. Examples: “Our baby was born”; “We welcomed a new baby”.
big_event.wedding: Milestones and days worth remembering: Wedding. Examples: “We got married”; “It was our wedding”.
big_event.graduation: Milestones and days worth remembering: Graduation. Examples: “I graduated today”; “It was my graduation”.
big_event.newHome: Milestones and days worth remembering: New home. Examples: “We moved into our new home”; “I bought a new house”.
big_event.newJob: Milestones and days worth remembering: New job. Examples: “I started a new job”; “I changed careers”.
big_event.reunion: Milestones and days worth remembering: Reunion. Examples: “We had a family reunion”; “I went to a school reunion”.
big_event.milestone: Milestones and days worth remembering: Another milestone. Examples: “I reached an important milestone”; “A major life change happened”.
general.highlight: Highlights, hard moments or anything else: A highlight. Examples: “That was the highlight of my day”; “The best moment today”.
general.difficult: Highlights, hard moments or anything else: A difficult moment. Examples: “I had a difficult day”; “That was a hard moment”.
general.gratitude: Highlights, hard moments or anything else: Something I’m grateful for. Examples: “I’m grateful for today”; “I felt thankful”.
general.new: Highlights, hard moments or anything else: Something new. Examples: “I discovered something new”; “Something new happened”.
general.rest: Highlights, hard moments or anything else: Rest or recovery. Examples: “I took time to rest”; “I had a recovery day”.
general.ordinary: Highlights, hard moments or anything else: An ordinary moment. Examples: “It was an ordinary quiet moment”; “Just part of my normal day”.
general.other: A meaningful generic note that genuinely matches no more specific journal destination. Examples: “A thought I wanted to remember”. Not: Any note clearly matching another destination.
"""
}

@available(iOS 26.0, *)
@Generable
struct NoteRouteDecision {
  @Guide(description: "The single best atomic journal route, or ambiguous only when no route clearly leads", .anyOf(["went_somewhere.park", "went_somewhere.city", "went_somewhere.beach", "went_somewhere.forest", "went_somewhere.garden", "went_somewhere.museum", "went_somewhere.cafe", "went_somewhere.restaurant", "went_somewhere.street", "went_somewhere.home", "went_somewhere.travel", "went_somewhere.other_place", "food.meal", "food.snack", "food.dessert", "food.coffee", "food.tea", "food.drink", "food.cooking", "food.other_food", "studio.book", "studio.film", "studio.show", "studio.game", "studio.music", "studio.podcast", "studio.art", "studio.other_media", "movement.walk", "movement.run", "movement.cycle", "movement.workout", "movement.sport", "movement.hike", "movement.errands", "movement.commute", "movement.travel", "movement.mixed", "people.partner", "people.my_child", "people.family", "people.friends", "people.group", "people.someone_new", "people.pet", "people.solo", "people.someone_else", "work.focus", "work.office", "work.learning", "work.planning", "work.creative", "work.admin", "work.progress", "work.other_work", "big_event.birthday", "big_event.anniversary", "big_event.firstTime", "big_event.holiday", "big_event.trip", "big_event.achievement", "big_event.baby", "big_event.wedding", "big_event.graduation", "big_event.newHome", "big_event.newJob", "big_event.reunion", "big_event.milestone", "general.highlight", "general.difficult", "general.gratitude", "general.new", "general.rest", "general.ordinary", "general.other", "ambiguous"]))
  let routeKey: String

  @Guide(description: "The second plausible atomic journal route, or empty when there is no close alternative", .anyOf(["", "went_somewhere.park", "went_somewhere.city", "went_somewhere.beach", "went_somewhere.forest", "went_somewhere.garden", "went_somewhere.museum", "went_somewhere.cafe", "went_somewhere.restaurant", "went_somewhere.street", "went_somewhere.home", "went_somewhere.travel", "went_somewhere.other_place", "food.meal", "food.snack", "food.dessert", "food.coffee", "food.tea", "food.drink", "food.cooking", "food.other_food", "studio.book", "studio.film", "studio.show", "studio.game", "studio.music", "studio.podcast", "studio.art", "studio.other_media", "movement.walk", "movement.run", "movement.cycle", "movement.workout", "movement.sport", "movement.hike", "movement.errands", "movement.commute", "movement.travel", "movement.mixed", "people.partner", "people.my_child", "people.family", "people.friends", "people.group", "people.someone_new", "people.pet", "people.solo", "people.someone_else", "work.focus", "work.office", "work.learning", "work.planning", "work.creative", "work.admin", "work.progress", "work.other_work", "big_event.birthday", "big_event.anniversary", "big_event.firstTime", "big_event.holiday", "big_event.trip", "big_event.achievement", "big_event.baby", "big_event.wedding", "big_event.graduation", "big_event.newHome", "big_event.newJob", "big_event.reunion", "big_event.milestone", "general.highlight", "general.difficult", "general.gratitude", "general.new", "general.rest", "general.ordinary", "general.other", "ambiguous"]))
  let alternativeRouteKey: String

  @Guide(description: "Confidence that routeKey is the best destination", .range(0.0...1.0))
  let routeConfidence: Double

  @Guide(description: "Confidence in alternativeRouteKey, or zero when it is empty", .range(0.0...1.0))
  let alternativeRouteConfidence: Double
}

@available(iOS 26.0, *)
@Generable
struct NoteRead {
  @Guide(description: "A short warm 2-4 word title for the moment under 24 characters, with no punctuation, emoji, or quotes")
  let title: String

  @Guide(description: "The dominant feeling of the note", .anyOf(["calm", "energy", "together", "meaningful"]))
  let feeling: String

  @Guide(description: "The consumed media kind; other covers watched sport, news, podcasts, livestreams, and other formats; otherwise none", .anyOf(["none", "book", "film", "show", "game", "music", "art", "other"]))
  let mediaKind: String

  @Guide(description: "The mentioned work's full official title when confidently known, otherwise empty")
  let mediaTitle: String

  @Guide(description: "The work's author, director, or artist when confidently known, otherwise empty")
  let mediaCreator: String

  @Guide(description: "A short dish or drink name when the note is about eating or drinking, otherwise empty")
  let food: String

  @Guide(description: "The single best atomic journal route, or ambiguous only when no route clearly leads", .anyOf(["went_somewhere.park", "went_somewhere.city", "went_somewhere.beach", "went_somewhere.forest", "went_somewhere.garden", "went_somewhere.museum", "went_somewhere.cafe", "went_somewhere.restaurant", "went_somewhere.street", "went_somewhere.home", "went_somewhere.travel", "went_somewhere.other_place", "food.meal", "food.snack", "food.dessert", "food.coffee", "food.tea", "food.drink", "food.cooking", "food.other_food", "studio.book", "studio.film", "studio.show", "studio.game", "studio.music", "studio.podcast", "studio.art", "studio.other_media", "movement.walk", "movement.run", "movement.cycle", "movement.workout", "movement.sport", "movement.hike", "movement.errands", "movement.commute", "movement.travel", "movement.mixed", "people.partner", "people.my_child", "people.family", "people.friends", "people.group", "people.someone_new", "people.pet", "people.solo", "people.someone_else", "work.focus", "work.office", "work.learning", "work.planning", "work.creative", "work.admin", "work.progress", "work.other_work", "big_event.birthday", "big_event.anniversary", "big_event.firstTime", "big_event.holiday", "big_event.trip", "big_event.achievement", "big_event.baby", "big_event.wedding", "big_event.graduation", "big_event.newHome", "big_event.newJob", "big_event.reunion", "big_event.milestone", "general.highlight", "general.difficult", "general.gratitude", "general.new", "general.rest", "general.ordinary", "general.other", "ambiguous"]))
  let routeKey: String

  @Guide(description: "The second plausible atomic journal route, or empty when there is no close alternative", .anyOf(["", "went_somewhere.park", "went_somewhere.city", "went_somewhere.beach", "went_somewhere.forest", "went_somewhere.garden", "went_somewhere.museum", "went_somewhere.cafe", "went_somewhere.restaurant", "went_somewhere.street", "went_somewhere.home", "went_somewhere.travel", "went_somewhere.other_place", "food.meal", "food.snack", "food.dessert", "food.coffee", "food.tea", "food.drink", "food.cooking", "food.other_food", "studio.book", "studio.film", "studio.show", "studio.game", "studio.music", "studio.podcast", "studio.art", "studio.other_media", "movement.walk", "movement.run", "movement.cycle", "movement.workout", "movement.sport", "movement.hike", "movement.errands", "movement.commute", "movement.travel", "movement.mixed", "people.partner", "people.my_child", "people.family", "people.friends", "people.group", "people.someone_new", "people.pet", "people.solo", "people.someone_else", "work.focus", "work.office", "work.learning", "work.planning", "work.creative", "work.admin", "work.progress", "work.other_work", "big_event.birthday", "big_event.anniversary", "big_event.firstTime", "big_event.holiday", "big_event.trip", "big_event.achievement", "big_event.baby", "big_event.wedding", "big_event.graduation", "big_event.newHome", "big_event.newJob", "big_event.reunion", "big_event.milestone", "general.highlight", "general.difficult", "general.gratitude", "general.new", "general.rest", "general.ordinary", "general.other", "ambiguous"]))
  let alternativeRouteKey: String

  @Guide(description: "Confidence that routeKey is the best destination", .range(0.0...1.0))
  let routeConfidence: Double

  @Guide(description: "Confidence in alternativeRouteKey, or zero when it is empty", .range(0.0...1.0))
  let alternativeRouteConfidence: Double

  @Guide(description: "A concise specific name or detail explicitly supported by the note, otherwise empty")
  let specific: String

  @Guide(description: "An allowed context option ID explicitly supported by the note, otherwise empty")
  let context: String

  @Guide(description: "An allowed journal feeling option ID explicitly supported by the note, otherwise empty")
  let journalFeeling: String
}
#endif
