create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.todos enable row level security;

create policy "Public can read todos"
on public.todos
for select
to anon, authenticated
using (true);
