create schema if not exists private;

create table public.economy_live_config (
  id text primary key,
  version integer not null check (version > 0),
  catalog_version integer not null check (catalog_version > 0),
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  enabled boolean not null default false,
  min_app_version text,
  starts_at timestamptz,
  ends_at timestamptz,
  updated_at timestamptz not null default now()
);

create table public.economy_campaigns (
  id text primary key,
  kind text not null check (kind in ('shop', 'visitor', 'season', 'plus', 'bundle')),
  priority integer not null default 0,
  enabled boolean not null default false,
  starts_at timestamptz,
  ends_at timestamptz,
  min_catalog_version integer not null default 1,
  min_app_version text,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.economy_reward_rules (
  event_type text not null,
  rule_version integer not null check (rule_version > 0),
  essence_delta integer not null check (essence_delta > 0),
  enabled boolean not null default false,
  starts_at timestamptz,
  ends_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  primary key (event_type, rule_version)
);

create table public.economy_offers (
  id text primary key,
  campaign_id text references public.economy_campaigns(id) on delete cascade,
  collectible_type text not null check (collectible_type in ('wisp', 'avatar')),
  collectible_id text not null,
  currency text not null check (currency in ('essence', 'cash')),
  price integer not null check (price >= 0),
  enabled boolean not null default false,
  starts_at timestamptz,
  ends_at timestamptz,
  per_user_limit integer not null default 1 check (per_user_limit > 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.economy_collectible_grants (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  collectible_type text not null check (collectible_type in ('wisp', 'avatar')),
  collectible_id text not null,
  quantity integer not null default 1 check (quantity > 0),
  source text not null,
  source_key text not null,
  provenance jsonb not null default '{}'::jsonb,
  granted_at timestamptz not null default now(),
  revoked_at timestamptz,
  unique (user_id, collectible_type, collectible_id, source_key)
);

create table public.economy_essence_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  delta integer not null check (delta <> 0),
  reason text not null,
  source_type text not null,
  source_id_hash text,
  rule_version integer not null default 1 check (rule_version > 0),
  idempotency_key text not null,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, idempotency_key)
);

create table public.economy_event_receipts (
  user_id uuid not null references auth.users(id) on delete cascade,
  client_event_id text not null,
  event_type text not null,
  local_date date not null,
  source_id_hash text not null,
  occurred_at timestamptz not null,
  rule_version integer not null default 1,
  created_at timestamptz not null default now(),
  primary key (user_id, client_event_id)
);

create table public.economy_offer_claims (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  offer_id text not null references public.economy_offers(id),
  quantity integer not null default 1 check (quantity > 0),
  claimed_at timestamptz not null default now(),
  unique (user_id, offer_id)
);

create table public.economy_subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  revenuecat_app_user_id text not null,
  entitlement_id text not null default 'plus',
  product_id text,
  active boolean not null default false,
  will_renew boolean,
  environment text check (environment in ('SANDBOX', 'PRODUCTION')),
  original_purchase_at timestamptz,
  expires_at timestamptz,
  last_event_at timestamptz,
  updated_at timestamptz not null default now()
);

create table public.revenuecat_webhook_events (
  event_id text primary key,
  event_type text not null,
  app_user_id text,
  event_timestamp_ms bigint not null,
  environment text,
  payload jsonb not null,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  processing_error text
);

create table public.economy_visitor_claims (
  user_id uuid not null references auth.users(id) on delete cascade,
  claim_index integer not null check (claim_index >= 0),
  campaign_id text not null references public.economy_campaigns(id),
  earned_at_captured_days integer not null check (earned_at_captured_days > 0),
  choices text[] not null check (cardinality(choices) between 0 and 3),
  chosen_wisp_id text,
  created_at timestamptz not null default now(),
  claimed_at timestamptz,
  primary key (user_id, claim_index),
  check (chosen_wisp_id is null or chosen_wisp_id = any(choices))
);

create index economy_grants_user_item_idx on public.economy_collectible_grants (user_id, collectible_type, collectible_id) where revoked_at is null;
create index economy_ledger_user_created_idx on public.economy_essence_ledger (user_id, created_at desc);
create index economy_campaign_window_idx on public.economy_campaigns (enabled, starts_at, ends_at);
create index revenuecat_user_event_idx on public.revenuecat_webhook_events (app_user_id, event_timestamp_ms desc);

alter table public.economy_live_config enable row level security;
alter table public.economy_campaigns enable row level security;
alter table public.economy_reward_rules enable row level security;
alter table public.economy_offers enable row level security;
alter table public.economy_collectible_grants enable row level security;
alter table public.economy_essence_ledger enable row level security;
alter table public.economy_event_receipts enable row level security;
alter table public.economy_offer_claims enable row level security;
alter table public.economy_subscriptions enable row level security;
alter table public.revenuecat_webhook_events enable row level security;
alter table public.economy_visitor_claims enable row level security;

create policy "Authenticated users read current economy config" on public.economy_live_config
  for select to authenticated using (enabled and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at > now()));
create policy "Authenticated users read active campaigns" on public.economy_campaigns
  for select to authenticated using (enabled and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at > now()));
create policy "Authenticated users read active reward rules" on public.economy_reward_rules
  for select to authenticated using (enabled and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at > now()));
create policy "Authenticated users read active offers" on public.economy_offers
  for select to authenticated using (enabled and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at > now()));
create policy "Users read own collectible grants" on public.economy_collectible_grants
  for select to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = user_id);
create policy "Users read own essence ledger" on public.economy_essence_ledger
  for select to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = user_id);
create policy "Users read own event receipts" on public.economy_event_receipts
  for select to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = user_id);
create policy "Users read own offer claims" on public.economy_offer_claims
  for select to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = user_id);
create policy "Users read own subscription" on public.economy_subscriptions
  for select to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = user_id);
create policy "Users read own visitor claims" on public.economy_visitor_claims
  for select to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create or replace function private.economy_grant_v1(
  target_user_id uuid,
  target_type text,
  target_id text,
  target_source text,
  target_source_key text,
  target_quantity integer default 1,
  target_provenance jsonb default '{}'::jsonb
) returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if target_user_id is null or target_quantity < 1 then raise exception 'Invalid grant'; end if;
  insert into public.economy_collectible_grants (user_id, collectible_type, collectible_id, quantity, source, source_key, provenance)
  values (target_user_id, target_type, target_id, target_quantity, target_source, target_source_key, target_provenance)
  on conflict (user_id, collectible_type, collectible_id, source_key) do nothing;
end;
$$;

create or replace function private.ensure_visitor_offer_v1()
returns public.economy_visitor_claims
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_campaign public.economy_campaigns%rowtype;
  v_captured integer;
  v_claim_index integer;
  v_pool text[];
  v_choices text[];
  v_row public.economy_visitor_claims%rowtype;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  select * into v_campaign from public.economy_campaigns
  where kind = 'visitor' and enabled and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at > now())
  order by priority desc, id limit 1;
  if v_campaign.id is null then return null; end if;
  select count(*)::integer into v_captured from public.streak_days where user_id = v_user_id and state = 'captured';
  v_claim_index := floor(v_captured / greatest(1, coalesce((v_campaign.config->>'daysPerClaim')::integer, 7)))::integer - 1;
  if v_claim_index < 0 then return null; end if;
  select * into v_row from public.economy_visitor_claims where user_id = v_user_id and claim_index = v_claim_index;
  if v_row.user_id is not null then return v_row; end if;
  select coalesce(array_agg(value), '{}'::text[]) into v_pool from jsonb_array_elements_text(coalesce(v_campaign.config->'pool', '[]'::jsonb)) value;
  select coalesce(array_agg(candidate order by digest), '{}'::text[]) into v_choices from (
    select candidate, md5(v_user_id::text || ':' || v_claim_index::text || ':' || candidate) digest
    from unnest(v_pool) candidate
    where not exists (
      select 1 from public.economy_collectible_grants grant_row
      where grant_row.user_id = v_user_id and grant_row.collectible_type = 'wisp' and grant_row.collectible_id = candidate and grant_row.revoked_at is null
    ) order by digest limit greatest(1, least(coalesce((v_campaign.config->>'choiceCount')::integer, 3), 3))
  ) ranked;
  insert into public.economy_visitor_claims (user_id, claim_index, campaign_id, earned_at_captured_days, choices)
  values (v_user_id, v_claim_index, v_campaign.id, (v_claim_index + 1) * coalesce((v_campaign.config->>'daysPerClaim')::integer, 7), v_choices)
  returning * into v_row;
  return v_row;
end;
$$;

create or replace function private.purchase_economy_offer_v1(target_offer_id text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_offer public.economy_offers%rowtype;
  v_balance integer;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  select * into v_offer from public.economy_offers where id = target_offer_id and enabled
    and currency = 'essence' and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at > now()) for update;
  if v_offer.id is null then raise exception 'Invalid offer'; end if;
  if exists (select 1 from public.economy_offer_claims where user_id = v_user_id and offer_id = v_offer.id) then return jsonb_build_object('ok', true, 'idempotent', true); end if;
  select coalesce(sum(delta), 0)::integer into v_balance from public.economy_essence_ledger where user_id = v_user_id;
  if v_balance < v_offer.price then raise exception 'Insufficient Essence'; end if;
  insert into public.economy_essence_ledger (user_id, delta, reason, source_type, rule_version, idempotency_key)
  values (v_user_id, -v_offer.price, 'offer_purchase', 'offer', 1, 'offer:' || v_offer.id);
  insert into public.economy_offer_claims (user_id, offer_id) values (v_user_id, v_offer.id);
  perform private.economy_grant_v1(v_user_id, v_offer.collectible_type, v_offer.collectible_id, 'essence_shop', 'offer:' || v_offer.id);
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function private.register_economy_event_v1(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_client_event_id text := payload->>'client_event_id';
  v_event_type text := payload->>'event_type';
  v_local_date date := (payload->>'local_date')::date;
  v_source_hash text := payload->>'source_id_hash';
  v_occurred_at timestamptz := (payload->>'occurred_at')::timestamptz;
  v_rule public.economy_reward_rules%rowtype;
  v_inserted integer;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if v_client_event_id is null or v_event_type is null or v_source_hash is null or v_occurred_at is null then raise exception 'Invalid economy event'; end if;
  if v_event_type not in ('photo', 'voice', 'reflection', 'place', 'new_place', 'food_or_studio', 'big_moment', 'weekly_recap', 'quest') then raise exception 'Unsupported economy event'; end if;
  select * into v_rule from public.economy_reward_rules where event_type = v_event_type and enabled
    and (starts_at is null or starts_at <= v_occurred_at) and (ends_at is null or ends_at > v_occurred_at)
    order by rule_version desc limit 1;
  if v_rule.event_type is null then return jsonb_build_object('credited', false, 'reason', 'rule_disabled'); end if;
  insert into public.economy_event_receipts (user_id, client_event_id, event_type, local_date, source_id_hash, occurred_at, rule_version)
  values (v_user_id, v_client_event_id, v_event_type, v_local_date, v_source_hash, v_occurred_at, v_rule.rule_version)
  on conflict do nothing;
  get diagnostics v_inserted = row_count;
  if v_inserted = 0 then return jsonb_build_object('credited', false, 'reason', 'duplicate'); end if;
  insert into public.economy_essence_ledger (user_id, delta, reason, source_type, source_id_hash, rule_version, idempotency_key, occurred_at)
  values (v_user_id, v_rule.essence_delta, 'captured_life', v_event_type, v_source_hash, v_rule.rule_version, 'event:' || v_client_event_id, v_occurred_at);
  return jsonb_build_object('credited', true, 'delta', v_rule.essence_delta, 'ruleVersion', v_rule.rule_version);
end;
$$;

create or replace function private.migrate_legacy_economy_v1(opening_balance integer, purchased_avatar_ids text[], equipped_avatar_ids text[])
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_enabled boolean;
  v_id text;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  select coalesce((payload->'flags'->>'legacyMigration')::boolean, false) into v_enabled
  from public.economy_live_config where id = 'default' and enabled;
  if not v_enabled then raise exception 'Legacy migration disabled'; end if;
  if cardinality(coalesce(purchased_avatar_ids, '{}'::text[])) > 250 or cardinality(coalesce(equipped_avatar_ids, '{}'::text[])) > 4 then raise exception 'Migration payload too large'; end if;
  if greatest(0, least(coalesce(opening_balance, 0), 20000)) > 0 then
    insert into public.economy_essence_ledger (user_id, delta, reason, source_type, rule_version, idempotency_key)
    values (v_user_id, greatest(0, least(opening_balance, 20000)), 'legacy_opening_balance', 'migration', 1, 'legacy:opening-balance')
    on conflict (user_id, idempotency_key) do nothing;
  end if;
  foreach v_id in array coalesce(purchased_avatar_ids, '{}'::text[]) loop
    if v_id ~ '^(body|face|hat|held):[a-z0-9-]+$' then perform private.economy_grant_v1(v_user_id, 'avatar', v_id, 'avatar_essence', 'legacy:purchase:' || v_id); end if;
  end loop;
  foreach v_id in array coalesce(equipped_avatar_ids, '{}'::text[]) loop
    if v_id ~ '^(body|face|hat|held):[a-z0-9-]+$' then perform private.economy_grant_v1(v_user_id, 'avatar', v_id, 'avatar_grandfathered', 'legacy:equipped:' || split_part(v_id, ':', 1)); end if;
  end loop;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function private.choose_visitor_wisp_v1(target_wisp_id text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_claim public.economy_visitor_claims%rowtype;
begin
  v_claim := private.ensure_visitor_offer_v1();
  if v_claim.user_id is null or v_claim.claimed_at is not null or not target_wisp_id = any(v_claim.choices) then raise exception 'Not eligible'; end if;
  update public.economy_visitor_claims set chosen_wisp_id = target_wisp_id, claimed_at = now()
  where user_id = v_user_id and claim_index = v_claim.claim_index and claimed_at is null;
  perform private.economy_grant_v1(v_user_id, 'wisp', target_wisp_id, 'visitor', 'visitor:' || v_claim.campaign_id || ':' || v_claim.claim_index);
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function private.claim_monthly_plus_wisp_v1()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_wisp_id text;
  v_period text := to_char(now() at time zone 'UTC', 'YYYY-MM');
begin
  if not exists (select 1 from public.economy_subscriptions where user_id = v_user_id and entitlement_id = 'plus' and active and (expires_at is null or expires_at > now())) then raise exception 'Plus required'; end if;
  select config->>'monthlyClaimWispId' into v_wisp_id from public.economy_campaigns
  where kind = 'plus' and enabled and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at > now()) order by priority desc limit 1;
  if v_wisp_id is null then raise exception 'No active Plus claim'; end if;
  perform private.economy_grant_v1(v_user_id, 'wisp', v_wisp_id, 'plus_claim', 'plus:' || v_period);
  return jsonb_build_object('ok', true, 'wispId', v_wisp_id);
end;
$$;

create or replace function public.get_economy_snapshot_v1()
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_config jsonb;
  v_visitor public.economy_visitor_claims%rowtype;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  v_visitor := private.ensure_visitor_offer_v1();
  select payload into v_config from public.economy_live_config where id = 'default' and enabled
    and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at > now());
  return jsonb_build_object(
    'config', v_config,
    'snapshot', jsonb_build_object(
      'configVersion', coalesce((v_config->>'version')::integer, 1),
      'serverTime', now(),
      'essenceBalance', (select coalesce(sum(delta), 0) from public.economy_essence_ledger where user_id = v_user_id),
      'activePlus', exists (select 1 from public.economy_subscriptions where user_id = v_user_id and active and (expires_at is null or expires_at > now())),
      'inventory', coalesce((select jsonb_agg(jsonb_build_object('collectibleType', collectible_type, 'collectibleId', collectible_id, 'quantity', quantity, 'source', source, 'grantedAt', granted_at)) from public.economy_collectible_grants where user_id = v_user_id and revoked_at is null), '[]'::jsonb),
      'activeCampaignIds', coalesce((select jsonb_agg(id order by priority desc, id) from public.economy_campaigns where enabled and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at > now())), '[]'::jsonb),
      'visitorOffer', case when v_visitor.user_id is null or v_visitor.claimed_at is not null then null else jsonb_build_object('claimIndex', v_visitor.claim_index, 'choices', v_visitor.choices, 'earnedAtCapturedDays', v_visitor.earned_at_captured_days) end,
      'synced', true
    )
  );
end;
$$;

create or replace function public.purchase_economy_offer_v1(offer_id text) returns jsonb language sql security invoker set search_path = '' as $$ select private.purchase_economy_offer_v1(offer_id); $$;
create or replace function public.register_economy_event_v1(payload jsonb) returns jsonb language sql security invoker set search_path = '' as $$ select private.register_economy_event_v1(payload); $$;
create or replace function public.migrate_legacy_economy_v1(opening_balance integer, purchased_avatar_ids text[], equipped_avatar_ids text[]) returns jsonb language sql security invoker set search_path = '' as $$ select private.migrate_legacy_economy_v1(opening_balance, purchased_avatar_ids, equipped_avatar_ids); $$;
create or replace function public.choose_visitor_wisp_v1(chosen_wisp_id text) returns jsonb language sql security invoker set search_path = '' as $$ select private.choose_visitor_wisp_v1(chosen_wisp_id); $$;
create or replace function public.claim_monthly_plus_wisp_v1() returns jsonb language sql security invoker set search_path = '' as $$ select private.claim_monthly_plus_wisp_v1(); $$;
create or replace function public.reconcile_revenuecat_v1() returns jsonb language sql security invoker set search_path = '' as $$ select public.get_economy_snapshot_v1(); $$;

revoke all on function public.get_economy_snapshot_v1() from public;
revoke all on function public.purchase_economy_offer_v1(text) from public;
revoke all on function public.register_economy_event_v1(jsonb) from public;
revoke all on function public.migrate_legacy_economy_v1(integer, text[], text[]) from public;
revoke all on function public.choose_visitor_wisp_v1(text) from public;
revoke all on function public.claim_monthly_plus_wisp_v1() from public;
revoke all on function public.reconcile_revenuecat_v1() from public;
grant execute on function public.get_economy_snapshot_v1() to authenticated;
grant execute on function public.purchase_economy_offer_v1(text) to authenticated;
grant execute on function public.register_economy_event_v1(jsonb) to authenticated;
grant execute on function public.migrate_legacy_economy_v1(integer, text[], text[]) to authenticated;
grant execute on function public.choose_visitor_wisp_v1(text) to authenticated;
grant execute on function public.claim_monthly_plus_wisp_v1() to authenticated;
grant execute on function public.reconcile_revenuecat_v1() to authenticated;
revoke all on function private.economy_grant_v1(uuid, text, text, text, text, integer, jsonb) from public;
revoke all on function private.ensure_visitor_offer_v1() from public;
revoke all on function private.purchase_economy_offer_v1(text) from public;
revoke all on function private.register_economy_event_v1(jsonb) from public;
revoke all on function private.migrate_legacy_economy_v1(integer, text[], text[]) from public;
revoke all on function private.choose_visitor_wisp_v1(text) from public;
revoke all on function private.claim_monthly_plus_wisp_v1() from public;
grant usage on schema private to authenticated;
grant execute on function private.ensure_visitor_offer_v1() to authenticated;
grant execute on function private.purchase_economy_offer_v1(text) to authenticated;
grant execute on function private.register_economy_event_v1(jsonb) to authenticated;
grant execute on function private.migrate_legacy_economy_v1(integer, text[], text[]) to authenticated;
grant execute on function private.choose_visitor_wisp_v1(text) to authenticated;
grant execute on function private.claim_monthly_plus_wisp_v1() to authenticated;

insert into public.economy_live_config (id, version, catalog_version, enabled, payload)
values ('default', 1, 3, false, '{"version":1,"catalogVersion":3,"flags":{"economySync":false,"wispShop":false,"visitorChoice":false,"plus":false,"gifting":false,"seasonalTrack":false,"legacyMigration":false},"essence":{"purchasable":false,"duplicateConversion":{"common":25,"rare":50,"epic":90,"legendary":160},"rewards":{"photo":5,"voice":8,"reflection":4,"place":6,"newPlaceBonus":4,"foodOrStudio":5,"bigMoment":15,"weeklyRecap":25,"quest":12}},"shop":{"offers":[]},"visitor":{"daysPerClaim":7,"choiceCount":3,"ownedPoolFallbackEssence":150,"pool":[],"enabled":false},"plus":{"entitlementId":"plus","offeringId":"default","products":["katchimeras_plus_monthly","katchimeras_plus_annual"],"monthlyClaimWispId":"opal","enabled":false}}'::jsonb)
on conflict (id) do nothing;

insert into public.economy_campaigns (id, kind, enabled, config) values
  ('visitor-pilot', 'visitor', false, '{"daysPerClaim":7,"choiceCount":3,"ownedPoolFallbackEssence":150,"pool":["dewdrop","bubble","nimbus","clover","pebble","crystal"]}'::jsonb),
  ('plus-monthly-pilot', 'plus', false, '{"monthlyClaimWispId":"opal"}'::jsonb),
  ('shop-pilot', 'shop', false, '{}'::jsonb)
on conflict (id) do nothing;

insert into public.economy_reward_rules (event_type, rule_version, essence_delta, enabled) values
  ('photo', 1, 5, false),
  ('voice', 1, 8, false),
  ('reflection', 1, 4, false),
  ('place', 1, 6, false),
  ('new_place', 1, 4, false),
  ('food_or_studio', 1, 5, false),
  ('big_moment', 1, 15, false),
  ('weekly_recap', 1, 25, false),
  ('quest', 1, 12, false)
on conflict (event_type, rule_version) do nothing;

insert into public.economy_offers (id, campaign_id, collectible_type, collectible_id, currency, price, enabled)
values ('pilot-orbit', 'shop-pilot', 'wisp', 'orbit', 'essence', 400, false)
on conflict (id) do nothing;
