create table public.economy_gem_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  delta integer not null check (delta <> 0),
  reason text not null,
  source_type text not null,
  idempotency_key text not null,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, idempotency_key)
);

create table public.economy_season_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  season_id text not null references public.economy_campaigns(id) on delete cascade,
  xp integer not null default 0 check (xp >= 0),
  premium boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (user_id, season_id)
);

create table public.economy_season_event_receipts (
  user_id uuid not null references auth.users(id) on delete cascade,
  season_id text not null references public.economy_campaigns(id) on delete cascade,
  client_event_id text not null,
  event_type text not null,
  local_date date not null,
  source_id_hash text not null,
  occurred_at timestamptz not null,
  created_at timestamptz not null default now(),
  primary key (user_id, season_id, client_event_id)
);

create table public.economy_season_claims (
  user_id uuid not null references auth.users(id) on delete cascade,
  season_id text not null references public.economy_campaigns(id) on delete cascade,
  tier_id text not null,
  track text not null check (track in ('free', 'premium')),
  reward jsonb not null check (jsonb_typeof(reward) = 'object'),
  claimed_at timestamptz not null default now(),
  primary key (user_id, season_id, tier_id, track)
);

create index economy_gems_user_created_idx on public.economy_gem_ledger (user_id, created_at desc);
create index economy_season_events_user_date_idx on public.economy_season_event_receipts (user_id, local_date desc);

alter table public.economy_gem_ledger enable row level security;
alter table public.economy_season_progress enable row level security;
alter table public.economy_season_event_receipts enable row level security;
alter table public.economy_season_claims enable row level security;

create policy "Users read their own Gem ledger" on public.economy_gem_ledger
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users read their own season progress" on public.economy_season_progress
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users read their own season event receipts" on public.economy_season_event_receipts
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users read their own season claims" on public.economy_season_claims
  for select to authenticated using ((select auth.uid()) = user_id);

create or replace function private.register_season_event_v1(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_season_id text := payload->>'season_id';
  v_client_event_id text := payload->>'client_event_id';
  v_event_type text := payload->>'event_type';
  v_source_hash text := payload->>'source_hash';
  v_local_date date := (payload->>'local_date')::date;
  v_occurred_at timestamptz := (payload->>'occurred_at')::timestamptz;
  v_xp integer;
  v_inserted integer;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if v_client_event_id is null or length(v_client_event_id) > 160 or v_source_hash is null or length(v_source_hash) > 128 then
    raise exception 'Invalid season event';
  end if;
  if v_local_date < current_date - 7 or v_local_date > current_date + 1 then raise exception 'Invalid season event date'; end if;
  if not exists (
    select 1 from public.economy_campaigns campaign
    where campaign.id = v_season_id and campaign.kind = 'season' and campaign.enabled
      and (campaign.starts_at is null or campaign.starts_at <= now())
      and (campaign.ends_at is null or campaign.ends_at > now())
  ) then return jsonb_build_object('credited', false, 'reason', 'season_disabled'); end if;

  v_xp := case v_event_type
    when 'capture' then 10 when 'companion_interaction' then 5 when 'merge' then 1
    when 'order_served' then 10 when 'goal_completed' then 20 when 'hatch' then 30
    when 'wisp_discovered' then 15 else null end;
  if v_xp is null then raise exception 'Unsupported season event'; end if;

  insert into public.economy_season_event_receipts
    (user_id, season_id, client_event_id, event_type, local_date, source_id_hash, occurred_at)
  values (v_user_id, v_season_id, v_client_event_id, v_event_type, v_local_date, v_source_hash, v_occurred_at)
  on conflict do nothing;
  get diagnostics v_inserted = row_count;
  if v_inserted = 0 then return jsonb_build_object('credited', false, 'reason', 'duplicate'); end if;

  insert into public.economy_season_progress (user_id, season_id, xp)
  values (v_user_id, v_season_id, v_xp)
  on conflict (user_id, season_id) do update set
    xp = public.economy_season_progress.xp + excluded.xp,
    updated_at = now();
  return jsonb_build_object('credited', true, 'xp', v_xp);
end;
$$;

create or replace function private.claim_season_reward_v1(target_season_id text, target_tier_id text, target_track text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_campaign public.economy_campaigns%rowtype;
  v_progress public.economy_season_progress%rowtype;
  v_tier jsonb;
  v_reward jsonb;
  v_required_xp integer;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if target_track not in ('free', 'premium') then raise exception 'Invalid season track'; end if;
  select * into v_campaign from public.economy_campaigns
    where id = target_season_id and kind = 'season' and enabled
      and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at > now());
  if v_campaign.id is null then return jsonb_build_object('ok', false, 'reason', 'season_disabled'); end if;
  select * into v_progress from public.economy_season_progress where user_id = v_user_id and season_id = target_season_id;
  select value into v_tier from jsonb_array_elements(coalesce(v_campaign.config->'tiers', '[]'::jsonb)) where value->>'id' = target_tier_id limit 1;
  if v_tier is null then return jsonb_build_object('ok', false, 'reason', 'invalid_tier'); end if;
  v_required_xp := coalesce((v_tier->>'xp')::integer, 0);
  if coalesce(v_progress.xp, 0) < v_required_xp then return jsonb_build_object('ok', false, 'reason', 'not_eligible'); end if;
  if target_track = 'premium' and not coalesce(v_progress.premium, false) then return jsonb_build_object('ok', false, 'reason', 'premium_required'); end if;
  v_reward := case target_track when 'free' then v_tier->'freeReward' else v_tier->'premiumReward' end;
  if v_reward is null then return jsonb_build_object('ok', false, 'reason', 'no_reward'); end if;

  insert into public.economy_season_claims (user_id, season_id, tier_id, track, reward)
  values (v_user_id, target_season_id, target_tier_id, target_track, v_reward)
  on conflict do nothing;
  if not found then return jsonb_build_object('ok', false, 'reason', 'already_claimed'); end if;

  if v_reward->>'kind' = 'gems' then
    insert into public.economy_gem_ledger (user_id, delta, reason, source_type, idempotency_key)
    values (v_user_id, (v_reward->>'amount')::integer, 'season_reward', 'season', 'season:' || target_season_id || ':' || target_tier_id || ':' || target_track);
  elsif v_reward->>'kind' = 'wisp' then
    insert into public.economy_collectible_grants (user_id, collectible_type, collectible_id, quantity, source, source_key)
    values (v_user_id, 'wisp', v_reward->>'wispId', 1, 'season', 'season:' || target_season_id || ':' || target_tier_id || ':' || target_track)
    on conflict do nothing;
  end if;
  return jsonb_build_object('ok', true, 'reward', v_reward);
end;
$$;

create or replace function public.register_season_event_v1(payload jsonb)
returns jsonb language sql security invoker set search_path = ''
as $$ select private.register_season_event_v1(payload); $$;

create or replace function public.claim_season_reward_v1(season_id text, tier_id text, track text)
returns jsonb language sql security invoker set search_path = ''
as $$ select private.claim_season_reward_v1(season_id, tier_id, track); $$;

create or replace function public.get_gem_balance_v1()
returns integer language sql stable security invoker set search_path = ''
as $$ select coalesce(sum(delta), 0)::integer from public.economy_gem_ledger where user_id = (select auth.uid()); $$;

revoke all on function public.register_season_event_v1(jsonb) from public, anon;
revoke all on function public.claim_season_reward_v1(text, text, text) from public, anon;
grant execute on function public.register_season_event_v1(jsonb) to authenticated;
grant execute on function public.claim_season_reward_v1(text, text, text) to authenticated;
revoke all on function public.get_gem_balance_v1() from public, anon;
grant execute on function public.get_gem_balance_v1() to authenticated;
revoke execute on function private.register_season_event_v1(jsonb) from public, anon;
revoke execute on function private.claim_season_reward_v1(text, text, text) from public, anon;
grant execute on function private.register_season_event_v1(jsonb) to authenticated;
grant execute on function private.claim_season_reward_v1(text, text, text) to authenticated;

insert into public.economy_campaigns (id, kind, priority, enabled, starts_at, ends_at, min_catalog_version, config)
values (
  'season-zero-little-adventures', 'season', 10, false,
  '2026-08-01T00:00:00Z', '2026-09-01T00:00:00Z', 3,
  '{"name":"Season of Little Adventures","tiers":[{"id":"tier-1","xp":100,"freeReward":{"kind":"merge_energy","amount":25},"premiumReward":{"kind":"gems","amount":20}},{"id":"tier-2","xp":250,"freeReward":{"kind":"coins","amount":150},"premiumReward":{"kind":"wisp","wispId":"leaflet"}},{"id":"tier-3","xp":500,"freeReward":{"kind":"wisp","wispId":"sprout"},"premiumReward":{"kind":"cosmetic","cosmeticId":"egg-hat-little-adventurer"}},{"id":"tier-4","xp":800,"freeReward":{"kind":"gems","amount":25},"premiumReward":{"kind":"cosmetic","cosmeticId":"hatch-effect-wandering-light"}}]}'::jsonb
)
on conflict (id) do update set config = excluded.config, enabled = false;
