import type { EncounterSpawner } from '@/types/encounter';

/** Generated by `npm run encounters:budgets`. Do not edit. */
export const ENCOUNTER_BUDGETS: Readonly<Record<string, { resolve: number; refill: EncounterSpawner | null }>> = {
  "island-campaign:wanderling-trail:restoration:1:w2ji9k": {"resolve":9,"refill":{"id":"refill","generatorId":"wild-garden","cell":33,"charges":6,"drops":["adventure:trail:1"],"recharge":{"kind":"merges","every":3,"amount":1}}},
};
