import { createEditorialCompanionPack, type EditorialCompanionProfile } from '@/constants/editorial-companion-pack';

const profiles = {
  dawnle: {
    companionName: 'Dawnle', focusName: 'the beginning of your day', momentName: 'morning-start moment',
    kinds: [['woke', 'Waking and orienting'], ['care', 'Caring for myself or someone else'], ['prepare', 'Following a prepared cue'], ['rush', 'Responding to immediate demands'], ['different', 'My day began at another time']],
    effects: [['steadier', 'A steadier start'], ['clearer', 'A clearer first step'], ['energy', 'A little more energy'], ['connection', 'Care or connection'], ['no-change', 'No clear effect']],
    supports: [['prepared', 'Something prepared earlier'], ['light', 'Comfortable light'], ['time', 'Enough time'], ['simple', 'A simple first step'], ['support', 'Help or shared care']],
    barriers: [['sleep', 'Sleep or fatigue'], ['demands', 'Immediate demands'], ['pain', 'Pain, illness, or low capacity'], ['unclear', 'No clear first step'], ['timing', 'My day began differently']],
    details: [['light', 'The light or weather'], ['body', 'How my body felt'], ['cue', 'A useful cue'], ['demand', 'What needed attention first'], ['none', 'Nothing stood out']],
    fit: [['well', 'It fitted well'], ['smaller', 'I needed a smaller start'], ['adapted', 'I adapted it'], ['different-time', 'My morning began later'], ['none', 'It did not fit today']],
    next: [['prepare', 'Prepare one small thing'], ['light', 'Find comfortable light'], ['simple', 'Choose one first step'], ['care', 'Begin with care'], ['none', 'No plan for now']],
    conditions: [['sleep', 'Sleep and fatigue'], ['responsibility', 'Work or caring duties'], ['environment', 'Light, noise, or space'], ['body', 'Pain, health, or energy'], ['timing', 'When my day needed to begin']],
    limits: [['rested', 'I rested longer'], ['reduced', 'I made the start smaller'], ['asked', 'I asked for help'], ['changed-time', 'I began at another time'], ['none', 'No boundary stood out']],
    learning: [['cue', 'Which cues help'], ['pace', 'The pace I need'], ['prepare', 'What is worth preparing'], ['capacity', 'How capacity changes the start'], ['varies', 'My mornings vary']],
    keep: [['cue', 'One useful cue'], ['kindness', 'A kinder pace'], ['clarity', 'A clear first step'], ['adaptation', 'Permission to adapt'], ['timing', 'A rhythm that fits my life']],
    adapt: [['smaller', 'Make it smaller'], ['later', 'Allow a later start'], ['different-cue', 'Try another cue'], ['less-often', 'Use it less often'], ['pause', 'Pause it']],
  },
  quietome: {
    companionName: 'Quietome', focusName: 'reflection and chosen quiet', momentName: 'reflection or quiet moment',
    kinds: [['pause', 'A pause with less input'], ['write', 'Writing or recording'], ['walk', 'Quiet movement or travel'], ['question', 'Time with a question'], ['none', 'No quiet moment']],
    effects: [['clearer', 'Something became clearer'], ['noticed', 'I noticed what was present'], ['rest', 'Less input felt restful'], ['unsettled', 'Something felt unsettled'], ['no-change', 'No clear effect']],
    supports: [['privacy', 'Enough privacy'], ['time', 'A little unclaimed time'], ['place', 'A suitable place'], ['prompt', 'A useful prompt'], ['company', 'Knowing support was available']],
    barriers: [['input', 'Too much input'], ['time', 'No unclaimed time'], ['unsafe', 'Being alone did not feel good'], ['rumination', 'Thoughts started circling'], ['pressure', 'Pressure to find an answer']],
    details: [['feeling', 'A feeling'], ['need', 'A need'], ['question', 'A question'], ['pattern', 'A repeating pattern'], ['nothing', 'Nothing asked for attention']],
    fit: [['well', 'It fitted well'], ['brief', 'A brief pause was enough'], ['company', 'I needed company instead'], ['stopped', 'I stopped when it became unhelpful'], ['none', 'It did not fit today']],
    next: [['line', 'One honest line'], ['pause', 'A brief low-input pause'], ['movement', 'Quiet movement'], ['talk', 'Reflection with someone safe'], ['none', 'No plan for now']],
    conditions: [['privacy', 'Privacy'], ['safety', 'Feeling emotionally safe'], ['time', 'Enough time'], ['body', 'My energy or nervous system'], ['question', 'Having a live question']],
    limits: [['stopped', 'I stopped circling'], ['reached', 'I reached for support'], ['changed', 'I changed the setting'], ['input', 'I chose helpful input'], ['none', 'No boundary stood out']],
    learning: [['timing', 'When quiet helps'], ['amount', 'How much is enough'], ['method', 'How I reflect best'], ['support', 'When I need another person'], ['varies', 'It varies']],
    keep: [['line', 'One honest line'], ['question', 'An open question'], ['pause', 'A chosen pause'], ['boundary', 'A boundary around input'], ['support', 'Permission to seek support']],
    adapt: [['shorter', 'Make it shorter'], ['guided', 'Use a gentle prompt'], ['shared', 'Reflect with someone'], ['more-input', 'Add grounding input'], ['pause', 'Pause it']],
  },
  vesperitt: {
    companionName: 'Vesperitt', focusName: 'your life after dark', momentName: 'late-night moment',
    kinds: [['creative', 'Making or learning'], ['work', 'Work, study, or caring'], ['people', 'Time with people'], ['rest', 'Entertainment or quiet'], ['awake', 'Awake without choosing it']],
    effects: [['worthwhile', 'It felt worthwhile'], ['connection', 'Connection'], ['space', 'Private or creative space'], ['cost', 'A next-day cost'], ['unclear', 'No clear effect']],
    supports: [['choice', 'Choosing what the night was for'], ['boundary', 'A clear stopping cue'], ['company', 'Good company'], ['comfort', 'Comfort or quiet'], ['flexibility', 'No early demand afterward']],
    barriers: [['work', 'Work or caring ran late'], ['sleep', 'I could not sleep'], ['scroll', 'Unplanned scrolling or autoplay'], ['stress', 'Stress or a busy mind'], ['timing', 'This schedule is part of my life']],
    details: [['activity', 'What I chose to do'], ['transition', 'When the night changed direction'], ['feeling', 'How the time felt'], ['stop', 'A stopping cue'], ['morning', 'The next-day effect']],
    fit: [['chosen', 'It felt chosen'], ['mixed', 'It was a mixture'], ['drifted', 'It drifted'], ['unavoidable', 'It was not really optional'], ['not-late', 'There was no late night']],
    next: [['protect', 'Protect chosen night time'], ['boundary', 'Choose a stopping cue'], ['support', 'Reduce an unavoidable pressure'], ['rest', 'Make room for rest'], ['none', 'No plan for now']],
    conditions: [['schedule', 'Work, care, or my natural schedule'], ['sleep', 'Sleep and wakefulness'], ['device', 'Devices or autoplay'], ['people', 'Other people'], ['stress', 'Stress or mental load']],
    limits: [['stopped', 'I stopped when I meant to'], ['changed', 'I changed activity'], ['rested', 'I chose rest'], ['accepted', 'I accepted an unavoidable night'], ['none', 'No boundary stood out']],
    learning: [['value', 'Which nights feel worthwhile'], ['drift', 'What creates drift'], ['stop', 'What helps me stop'], ['cost', 'What affects the next day'], ['varies', 'My nights vary']],
    keep: [['chosen', 'Chosen after-dark time'], ['ritual', 'A useful ritual'], ['boundary', 'A kind boundary'], ['honesty', 'An honest view of the trade-off'], ['flexibility', 'Room for different schedules']],
    adapt: [['smaller', 'Make the change smaller'], ['timing', 'Change the timing'], ['support', 'Add practical support'], ['less-judgement', 'Remove judgement'], ['pause', 'Pause it']],
  },
  cheerlet: {
    companionName: 'Cheerlet', focusName: 'noticing progress and change', momentName: 'progress or chapter moment',
    kinds: [['effort', 'Effort I want to recognise'], ['movement', 'Something moved forward'], ['beginning', 'A beginning'], ['ending', 'An ending or letting go'], ['survival', 'Getting through something hard']],
    effects: [['credit', 'A fairer sense of credit'], ['meaning', 'A sense of meaning'], ['connection', 'Connection or gratitude'], ['mixed', 'Mixed feelings'], ['no-change', 'No clear effect']],
    supports: [['record', 'Recording it before it passed'], ['person', 'Someone noticed with me'], ['specific', 'Naming the concrete change'], ['private', 'Keeping it private'], ['rest', 'Pausing before the next thing']],
    barriers: [['next', 'The next demand arrived'], ['small', 'It seemed too small'], ['comparison', 'Comparison erased it'], ['awkward', 'Acknowledgement felt awkward'], ['mixed', 'The change brought mixed feelings']],
    details: [['action', 'What I actually did'], ['effort', 'What it took'], ['support', 'What or who helped'], ['change', 'What is different now'], ['feeling', 'How the change feels']],
    fit: [['genuine', 'It felt genuine'], ['private', 'Private notice was enough'], ['mixed', 'The feeling was mixed'], ['too-much', 'Celebration felt too much'], ['none', 'Nothing needed marking']],
    next: [['credit', 'Name one piece of effort'], ['save', 'Save one small memory'], ['thank', 'Acknowledge support'], ['rest', 'Pause before the next demand'], ['none', 'No plan for now']],
    conditions: [['evidence', 'Seeing concrete evidence'], ['person', 'Someone else noticing'], ['space', 'Having space to pause'], ['values', 'Knowing why it mattered'], ['comparison', 'Freedom from comparison']],
    limits: [['private', 'I kept it private'], ['small', 'I kept the acknowledgement small'], ['mixed', 'I allowed mixed feelings'], ['declined', 'I did not celebrate'], ['none', 'No boundary stood out']],
    learning: [['progress', 'What progress looks like for me'], ['credit', 'What I tend to overlook'], ['support', 'How support contributes'], ['chapters', 'How I experience change'], ['varies', 'It varies']],
    keep: [['evidence', 'A concrete trace'], ['credit', 'Fair credit for effort'], ['gratitude', 'Gratitude without debt'], ['memory', 'A chapter memory'], ['permission', 'Permission not to perform joy']],
    adapt: [['private', 'Keep it more private'], ['smaller', 'Make it smaller'], ['specific', 'Make it more concrete'], ['less-often', 'Do it less often'], ['pause', 'Pause it']],
  },
} satisfies Record<string, EditorialCompanionProfile>;

export const BATCH_FOUR_COMPANION_CONTENT = Object.fromEntries(
  Object.entries(profiles).map(([familyId, profile]) => [familyId, createEditorialCompanionPack(profile)]),
);
