import { createEditorialCompanionPack, type EditorialCompanionProfile } from '@/constants/editorial-companion-pack';

const profiles = {
  pagelet: {
    companionName: 'Pagelet', focusName: 'reading or learning', momentName: 'reading or learning moment',
    kinds: [['book', 'A book or article'], ['audio', 'Audio or read-aloud material'], ['question', 'Following a question'], ['practice', 'Practising or reviewing'], ['none', 'No learning moment']],
    effects: [['understanding', 'More understanding'], ['curiosity', 'A new question'], ['enjoyment', 'Enjoyment'], ['useful', 'Something useful'], ['no-change', 'No clear effect']],
    supports: [['format', 'A format that suited me'], ['time', 'Enough time'], ['interest', 'Real interest'], ['small', 'A small amount'], ['support', 'Tools or another person']],
    barriers: [['attention', 'Attention or fatigue'], ['access', 'Format or accessibility'], ['time', 'Not enough time'], ['difficulty', 'The material was difficult'], ['interest', 'It did not hold my interest']],
    details: [['idea', 'An idea'], ['question', 'A question'], ['phrase', 'A phrase or example'], ['skill', 'A skill or method'], ['none', 'Nothing stayed']],
    fit: [['well', 'It fitted well'], ['smaller', 'I needed less'], ['different-format', 'I needed another format'], ['stopped', 'I stopped when needed'], ['none', 'It did not fit today']],
    next: [['short', 'Something short'], ['audio', 'Audio or read-aloud'], ['return', 'Return to familiar material'], ['question', 'Follow one question'], ['none', 'No plan for now']],
    conditions: [['quiet', 'Quiet'], ['interest', 'Interest'], ['format', 'The right format'], ['company', 'Learning with someone'], ['energy', 'Available energy']],
    limits: [['stopped', 'I stopped reading'], ['changed', 'I changed format'], ['skipped', 'I skipped a section'], ['asked', 'I asked for help'], ['none', 'No limit stood out']],
    learning: [['format', 'Which formats suit me'], ['pace', 'The pace I need'], ['interests', 'What holds my interest'], ['questions', 'Which questions matter'], ['varies', 'It varies']],
    keep: [['idea', 'One useful idea'], ['question', 'A live question'], ['format', 'An accessible format'], ['rhythm', 'A small rhythm'], ['freedom', 'Permission not to finish']],
    adapt: [['shorter', 'Make it shorter'], ['format', 'Change format'], ['topic', 'Change topic'], ['less-often', 'Do it less often'], ['pause', 'Pause it']],
  },
  flickerbun: {
    companionName: 'Flickerbun', focusName: 'watching screen stories', momentName: 'watching moment',
    kinds: [['film', 'A film'], ['episode', 'An episode'], ['short', 'A short video'], ['shared', 'Watching with someone'], ['none', 'No watching moment']],
    effects: [['enjoyment', 'Enjoyment'], ['rest', 'A sense of rest'], ['thought', 'Something to think about'], ['connection', 'Connection'], ['no-change', 'No clear effect']],
    supports: [['choice', 'Choosing before browsing'], ['attention', 'Fewer interruptions'], ['access', 'Subtitles or another access tool'], ['company', 'Good company'], ['time', 'Enough time']],
    barriers: [['browsing', 'Too much browsing'], ['fatigue', 'Fatigue'], ['interruptions', 'Interruptions'], ['access', 'Access or sensory needs'], ['not-interested', 'Nothing appealed']],
    details: [['scene', 'A scene'], ['character', 'A character'], ['idea', 'An idea'], ['craft', 'A visual or sound detail'], ['none', 'Nothing stayed']],
    fit: [['well', 'It fitted well'], ['too-long', 'It went on too long'], ['stopped', 'I stopped when I wanted'], ['mixed', 'It felt mixed'], ['none', 'I did not watch']],
    next: [['chosen', 'One thing chosen in advance'], ['familiar', 'Something familiar'], ['new', 'Something different'], ['shared', 'Something shared'], ['none', 'No plan for now']],
    conditions: [['time', 'Enough time'], ['comfort', 'A comfortable setup'], ['access', 'Useful access settings'], ['company', 'Company'], ['mood', 'The right mood']],
    limits: [['stop', 'I stopped part-way'], ['one', 'I stopped after one'], ['changed', 'I chose something else'], ['space', 'I chose no screen time'], ['none', 'No boundary stood out']],
    learning: [['taste', 'What I genuinely enjoy'], ['length', 'The length that suits me'], ['attention', 'What holds my attention'], ['company', 'When sharing helps'], ['varies', 'It varies']],
    keep: [['story', 'A story that mattered'], ['scene', 'A memorable scene'], ['choice', 'Choosing deliberately'], ['access', 'A setup that works'], ['flexibility', 'Freedom to stop']],
    adapt: [['shorter', 'Choose something shorter'], ['access', 'Change the setup'], ['less', 'Watch less often'], ['different', 'Choose another kind of story'], ['pause', 'Pause it']],
  },
  relicoon: {
    companionName: 'Relicoon', focusName: 'history and culture', momentName: 'history or culture moment',
    kinds: [['object', 'An object or artwork'], ['place', 'A historic place'], ['story', 'A person or community story'], ['source', 'A book, label, or recording'], ['none', 'No culture moment']],
    effects: [['context', 'More context'], ['question', 'A new question'], ['connection', 'A sense of connection'], ['challenge', 'It challenged an assumption'], ['no-change', 'No clear effect']],
    supports: [['source', 'A clear source'], ['context', 'Helpful context'], ['access', 'Accessible material or venue'], ['time', 'Time to look closely'], ['guide', 'A guide or another person']],
    barriers: [['access', 'Cost, location, or access'], ['context', 'Too little context'], ['trust', 'Unclear or conflicting sources'], ['time', 'Not enough time'], ['energy', 'Limited energy']],
    details: [['maker', 'Who made or used it'], ['material', 'A material or technique'], ['date', 'A time or change'], ['perspective', 'Whose perspective was present'], ['absence', 'Whose perspective was missing']],
    fit: [['well', 'It fitted well'], ['brief', 'A brief look was enough'], ['difficult', 'The material was difficult'], ['stopped', 'I stopped when needed'], ['none', 'It did not fit']],
    next: [['nearby', 'Notice local history'], ['object', 'Follow one object'], ['voice', 'Seek another perspective'], ['visit', 'Plan an accessible visit'], ['none', 'No plan for now']],
    conditions: [['context', 'Good context'], ['source', 'A trustworthy source'], ['place', 'Being in the place'], ['conversation', 'Discussion'], ['time', 'Time to reflect']],
    limits: [['uncertain', 'I left a claim uncertain'], ['source', 'I questioned a source'], ['perspective', 'I sought another perspective'], ['stopped', 'I stopped with difficult material'], ['none', 'No limit stood out']],
    learning: [['sources', 'How sources shape stories'], ['perspective', 'Whose perspective is centred'], ['change', 'How places and meanings change'], ['connection', 'What connects to the present'], ['uncertainty', 'What remains uncertain']],
    keep: [['question', 'A question worth following'], ['story', 'A human story'], ['place', 'A place that mattered'], ['perspective', 'A missing or new perspective'], ['care', 'Care with uncertainty']],
    adapt: [['closer', 'Keep it local'], ['free', 'Use free resources'], ['shorter', 'Make it shorter'], ['different-source', 'Try another source'], ['pause', 'Pause it']],
  },
  encora: {
    companionName: 'Encora', focusName: 'listening to or making music', momentName: 'music moment',
    kinds: [['listen', 'Listening'], ['make', 'Making or practising'], ['live', 'Live or shared music'], ['memory', 'Music tied to a memory'], ['none', 'No music moment']],
    effects: [['mood', 'It met or shifted my mood'], ['energy', 'It changed my energy'], ['attention', 'It held my attention'], ['connection', 'It supported connection'], ['no-change', 'No clear effect']],
    supports: [['choice', 'Choosing intentionally'], ['access', 'A comfortable volume or access tool'], ['time', 'Enough time'], ['instrument', 'An instrument or setup ready'], ['company', 'Company']],
    barriers: [['noise', 'Noise or sensory load'], ['hearing', 'Hearing or access needs'], ['time', 'Not enough time'], ['pressure', 'Pressure to perform'], ['interest', 'Nothing fitted the mood']],
    details: [['rhythm', 'Rhythm'], ['voice', 'A voice or instrument'], ['lyric', 'A lyric or idea'], ['texture', 'A sound texture'], ['silence', 'A pause or silence']],
    fit: [['well', 'It fitted well'], ['quieter', 'I needed it quieter'], ['shorter', 'I needed less time'], ['stopped', 'I stopped when needed'], ['none', 'It did not fit']],
    next: [['favourite', 'A familiar favourite'], ['new', 'Something unfamiliar'], ['make', 'A little making or practice'], ['shared', 'A shared music moment'], ['quiet', 'Quiet instead']],
    conditions: [['volume', 'Comfortable volume'], ['attention', 'Full attention'], ['movement', 'Movement'], ['company', 'Company'], ['privacy', 'Privacy to make music']],
    limits: [['volume', 'I changed the volume'], ['stopped', 'I stopped listening'], ['pressure', 'I released performance pressure'], ['quiet', 'I chose quiet'], ['none', 'No boundary stood out']],
    learning: [['mood', 'How music meets my mood'], ['sound', 'Which sounds suit me'], ['practice', 'How I like to practise'], ['connection', 'How music connects me'], ['varies', 'It varies']],
    keep: [['song', 'A song that mattered'], ['sound', 'A sound I discovered'], ['practice', 'A gentle practice'], ['people', 'A shared moment'], ['choice', 'The freedom to choose quiet']],
    adapt: [['quieter', 'Make it quieter'], ['shorter', 'Make it shorter'], ['different', 'Try different music'], ['less-pressure', 'Remove performance pressure'], ['pause', 'Pause it']],
  },
} satisfies Record<string, EditorialCompanionProfile>;

export const BATCH_THREE_COMPANION_CONTENT = Object.fromEntries(
  Object.entries(profiles).map(([familyId, profile]) => [familyId, createEditorialCompanionPack(profile)]),
);
