type Variant = { id: string; title: string; hint: string };

const variants = (
  title: string,
  original: string,
  secondTitle: string,
  second: string,
  thirdTitle: string,
  third: string,
): readonly Variant[] => [
  { id: 'original', title, hint: original },
  { id: 'alternate', title: secondTitle, hint: second },
  { id: 'return', title: thirdTitle, hint: third },
];

export const BATCH_ONE_QUEST_VARIANTS: Readonly<Record<string, readonly Variant[]>> = {
  'quest-rest-restored-detail': variants('What restored you?', 'Note one real rest or recovery action and what, if anything, changed afterwards.', 'Try a different kind of rest', 'After a real rest or wind-down moment, note what you tried and whether it helped enough.', 'Compare a recovery moment', 'Note what you did to recover and how its effect compared with a recent attempt.'),
  'quest-bedrotte-rest-note': variants('Name what restored you', 'Keep a short note about something that helped you slow down or recover today.', 'Name what did not help enough', 'Keep an honest note about a rest attempt that did not restore you as hoped.', 'Notice a small recovery', 'Keep a note about one small comfort, pause, or reduced demand and its effect.'),
  'quest-rest-wind-down': variants('Make one gentle landing', 'Try one small wind-down ritual, then note whether it helped the day feel finished.', 'Change the ending cue', 'Try a different small cue for ending the day, then note how it felt.', 'Return to a familiar ritual', 'Repeat a familiar wind-down ritual and note whether it suited tonight.'),
  'quest-rest-boundary': variants('Leave one thing for tomorrow', 'Let one non-urgent thing wait and note the boundary you chose.', 'Choose a stopping point', 'Stop one task at a chosen point and note what helped or tested that boundary.', 'Protect a quieter edge', 'Create one small period of reduced availability and note what happened.'),
  'quest-rest-recovery-checkin': variants('Check what restored you', 'After a demanding stretch, note what changed your energy—even if the answer is “not enough yet.”', 'Check what you needed', 'After a demanding stretch, note the kind of rest you needed and whether it was available.', 'Read the recovery conditions', 'Note what made recovery easier or harder after a demanding period.'),
  'quest-rest-weekly-review': variants('Read the week’s recovery pattern', 'Review what restored you, what drained you, and one kind rest choice for next week.', 'Review your stopping points', 'Look back at when you could stop and when you could not, then choose one useful support.', 'Review what rest meant', 'Compare two rest moments and note what you want to keep, change, or pause.'),
  'quest-early-night': variants('Prepare for rest when planned', 'Begin getting ready for rest at a time that fits tonight, then note what made that possible or difficult.', 'Try a gentler preparation', 'Choose one small way to prepare for rest, then note whether it suited tonight.', 'Compare the stopping cue', 'Use a familiar cue to begin winding down, then note whether it helped this time.'),

  'quest-tasklet-progress-detail': variants('What moved forward?', 'Note one real task action and what it changed, clarified, or made possible next.', 'What became clearer?', 'Note one decision, question, or smaller step that made real work clearer.', 'What did you stop?', 'Note one task you paused, reduced, delegated, or dropped and why that was useful.'),
  'quest-tasklet-focus': variants('Protect one focus block', 'After a real period of focused work or study, note what received your attention.', 'Use a smaller focus block', 'Complete a short period of focused work, then note whether its size fitted your energy.', 'Compare the conditions', 'After focused work, note which condition helped or interrupted your attention.'),
  'quest-tasklet-next-action': variants('Name the next visible step', 'Write the smallest concrete action that could move your current goal.', 'Name the next question', 'Write one question whose answer would make the work clearer.', 'Prepare the return point', 'Write the first action, decision, or setup that will help you return later.'),
  'quest-tasklet-clear-three': variants('Clear up to three small things', 'Finish one to three useful loose ends, then note what you chose and why.', 'Close one useful loop', 'Finish one small loose end that was taking up attention, then note it.', 'Choose what can wait', 'Clear one small thing and deliberately defer another, then note both choices.'),
  'quest-tasklet-tomorrow-first': variants('Choose tomorrow’s first move', 'Write the first meaningful action you want to begin with tomorrow.', 'Make returning easier', 'Prepare one item, file, or note that will make the next work session easier to start.', 'Leave a clear marker', 'Before stopping, note where you finished and the next decision or action.'),
  'quest-tasklet-weekly-review': variants('Review the week’s direction', 'Note what moved, what changed, and one priority worth carrying forward.', 'Review the working conditions', 'Note which conditions supported the work and which limit needs respecting next week.', 'Review what to release', 'Name one thing to continue, one to reshape, and one that can stop or wait.'),
  'quest-goal-note': variants('Keep one useful movement', 'Note one real action, decision, or ending that changed a goal today.', 'Keep one useful decision', 'Note one decision that clarified, reduced, delegated, or stopped part of a goal.', 'Keep the return point', 'Note where a goal stands now and the smallest useful place to return.'),

  'quest-mossprout-living-detail': variants('Notice one living detail', 'Note one specific living, seasonal, or sensory detail from a real nearby-nature moment.', 'Notice from indoors', 'From a window or with a plant, note one specific natural detail you could see, hear, or feel.', 'Look again nearby', 'Return to a familiar place or view and note one detail that changed or became visible.'),
  'quest-mossprout-green-photo': variants('A nearby patch of green', 'Photograph ordinary nearby greenery you could realistically notice again.', 'Green from where you are', 'Photograph a plant or green view that is accessible from where you are.', 'Return to the same green', 'Photograph familiar nearby greenery and frame one visible detail differently.'),
  'quest-mossprout-nature-note': variants('Keep a nearby-nature note', 'Note a plant, animal, sound, texture, weather, or seasonal detail you genuinely noticed.', 'Keep an indoor nature note', 'Note one detail from a houseplant, window view, weather sound, or natural light.', 'Follow one sensory detail', 'Note one colour, movement, sound, texture, or temperature from a nature moment.'),
  'quest-mossprout-return': variants('Return and look again', 'Return to a familiar place, plant, or view and note one change or missed detail.', 'Compare light and weather', 'Look again at a familiar place or view and note how light or weather changed it.', 'Compare living details', 'Return to a familiar nature spot and note what was growing, moving, or absent.'),
  'quest-mossprout-weekly-review': variants('Read the week in nature', 'Review the nature moments available to you, what you noticed, and one thread worth keeping.', 'Read the season nearby', 'Review two signs of seasonal change and where they were accessible to you.', 'Review access and attention', 'Note what made nature easier to notice and how you want to adapt next week.'),

  'quest-gatherglow-reach-out': variants('Choose one small reach-out', 'Send a genuine message if it feels right, then note what was within your control.', 'Reply with care', 'Reply to a message when you have capacity, then note what helped the response feel genuine.', 'Choose not to reach out', 'If space is kinder today, note the boundary you chose instead of sending a message.'),
  'quest-gatherglow-shared-moment': variants('Keep a shared moment', 'Capture a moment that felt genuinely shared without including another person’s private information.', 'Keep a quiet connection', 'Capture a simple sign of quiet company, shared attention, or mutual presence.', 'Keep what felt mutual', 'Capture a detail that represents shared effort, ease, or respected boundaries.'),
  'quest-gatherglow-deeper-checkin': variants('Make room for a genuine check-in', 'Have a conversation that feels safe and genuine, then note what supported it.', 'Listen with attention', 'Give a safe conversation your attention, then note what helped you stay present.', 'Respect the limit', 'Notice and respect one conversational boundary, then note how it affected the interaction.'),
  'quest-gatherglow-weekly-review': variants('Read the week’s connections', 'Review when connection felt mutual, when you needed space, and one quality worth tending.', 'Review your social energy', 'Note which interactions fitted your energy and where a boundary would help next week.', 'Review belonging', 'Recall one moment of belonging or its absence, then choose a kind next direction.'),
};
