type Variant = { id: string; title: string; hint: string };
const v = (title: string, first: string, secondTitle: string, second: string, thirdTitle: string, third: string): readonly Variant[] => [
  { id: 'original', title, hint: first },
  { id: 'alternate', title: secondTitle, hint: second },
  { id: 'return', title: thirdTitle, hint: third },
];

export const BATCH_TWO_QUEST_VARIANTS: Readonly<Record<string, readonly Variant[]>> = {
  'quest-feastle-meal-photo': v('A meal worth noticing', 'Photograph a meal or snack that felt caring, enjoyable, shared, or simply available when needed.', 'Keep one food detail', 'Photograph one ingredient, texture, arrangement, or serving detail you genuinely noticed.', 'Keep an everyday meal', 'Photograph an ordinary meal or snack that fitted your time, access, and energy.'),
  'quest-feastle-meal-note': v('What made the meal matter', 'Note what made a real meal or snack easy, comforting, connecting, interesting, or enough for the moment.', 'What made food easier?', 'Note one practical condition that helped a real food moment happen.', 'What did not meet the need?', 'Note a real food moment that was limited or difficult and what support would have helped.'),
  'quest-feastle-new-flavour': v('Make room for a new flavour', 'Try or prepare one unfamiliar flavour, then tag the cuisine or ingredient you explored.', 'Change one familiar detail', 'Try a different ingredient, seasoning, texture, or preparation in a familiar food and tag it.', 'Learn before tasting', 'Explore the origin or context of an unfamiliar ingredient or cuisine, then tag what you learned about.'),
  'quest-feastle-weekly-review': v('Read the week’s table', 'Review which food moments felt easiest or most meaningful and choose one worth repeating.', 'Review access and ease', 'Note what made food easier or harder this week and one realistic support to keep.', 'Review enjoyment without rules', 'Recall one enjoyable, comforting, or interesting food moment without rating the food as good or bad.'),

  'quest-coffee-ritual-pause': v('Pause for the first sip', 'Capture a coffee, tea, water, or other drink moment you chose to notice.', 'Keep a different drink pause', 'Capture a drink or refill that created a brief deliberate pause.', 'Keep the setting', 'Capture the place or object that helped a drink moment feel like a pause.'),
  'quest-coffee-ritual-note': v('Name what the pause was for', 'Note whether a real drink ritual helped you begin, pause, connect, feel comforted, or did very little.', 'Notice the cue', 'Note what prompted a real drink pause and whether the timing suited you.', 'Notice when you skipped it', 'If you skipped or changed the ritual, note why that choice fitted the day.'),
  'quest-coffee-ritual-redesign': v('Redesign one small ritual', 'Change one cue, setting, drink, or boundary and note how the pause felt.', 'Make the ritual smaller', 'Try a shorter or simpler version of the ritual and note whether it still created a pause.', 'Change the timing', 'Try the ritual at a different time and note whether it fitted your needs better.'),
  'quest-coffee-ritual-weekly-review': v('Read the week’s pauses', 'Review when the ritual became a real pause and which version is worth repeating.', 'Review the purpose', 'Compare when the ritual supported beginning, rest, comfort, or connection.', 'Review the fit', 'Note which drinks, times, or settings suited you and what you want to change.'),

  'quest-errandimp-close-loop': v('Close one loose loop', 'Finish one useful practical task and note what is now settled.', 'Clarify one loose loop', 'If completion is not possible, identify and record the next concrete step.', 'Let one loop wait', 'Deliberately defer or drop one non-urgent task and note why.'),
  'quest-errandimp-reset-note': v('Reset one useful space', 'Do a small household reset and note what became easier to use.', 'Reset one tiny area', 'Choose one drawer, surface, bag, or digital space and note the useful change.', 'Adapt the reset', 'Make one space work better for your actual access or routine and note what you changed.'),
  'quest-errandimp-maintenance': v('Handle one useful task', 'Complete one maintenance or admin action and note the concrete result.', 'Ask for practical help', 'Delegate or request help with one practical task and note the next state.', 'Prepare instead of finishing', 'Prepare one form, item, question, or document needed for a later task.'),
  'quest-errandimp-weekly-review': v('Clear the week’s practical fog', 'Review what was closed, what still matters, and what can consciously wait.', 'Review the constraints', 'Note which practical limits were outside your control and one support that would help.', 'Review the load', 'Choose one task to continue, one to share, and one to defer or drop.'),

  'quest-skylo-city-photo': v('Catch one local detail', 'Photograph an accessible local detail that makes a street, building, route, or view distinct.', 'Catch a detail from where you are', 'Photograph a local view or design detail from indoors, transport, or a familiar route.', 'Look again locally', 'Photograph a familiar local detail from a different safe position or time.'),
  'quest-skylo-local-stop': v('Choose one local stop', 'Visit an accessible local place and keep its name and one detail you noticed.', 'Return to a familiar stop', 'Visit a familiar local place and keep one detail that felt different this time.', 'Use a public or free stop', 'Visit an accessible public or low-cost local place and keep one useful detail.'),
  'quest-skylo-neighbourhood-note': v('Know one local area better', 'Notice a nearby area in a safe, accessible way and keep one specific detail.', 'Read an everyday route', 'On a familiar journey, note one design, history, movement, or use detail.', 'Explore without travelling farther', 'Use a view, map, local story, or short route to learn one thing nearby.'),
  'quest-skylo-weekly-review': v('Map the week’s local moments', 'Review the places, routes, views, and details you noticed and choose one curiosity to keep.', 'Review access and safety', 'Note where local curiosity fitted your access and where a different approach would help.', 'Review a familiar place', 'Compare two moments in one local place and note what changed or became clearer.'),
};
