// Generated by scripts/generate-hatchling-lod.py. Do not hand edit.
import type { ImageSourcePropType } from 'react-native';
import type { HomeVisualKey } from '@/types/home';
export { CREATURE_HATCHLING_ALPHA_BOUNDS, CREATURE_HATCHLING_ALPHA_THRESHOLD } from '@/constants/creature-hatchling-alpha-bounds.gen';
export type { CreatureHatchlingAlphaBounds } from '@/constants/creature-hatchling-alpha-bounds.gen';

export type CreatureHatchlingLod = 'full' | 'medium' | 'thumb';

export const CREATURE_HATCHLING_SOURCES: Record<CreatureHatchlingLod, Partial<Record<HomeVisualKey, ImageSourcePropType>>> = {
  full: {
    bedrotte: require('../assets/images/katchimeras/hatchlings/bedrotte.png'),
    cheerlet: require('../assets/images/katchimeras/hatchlings/cheerlet.png'),
    feastle: require('../assets/images/katchimeras/hatchlings/feastle.png'),
    flickerbun: require('../assets/images/katchimeras/hatchlings/flickerbun.png'),
    gatherglow: require('../assets/images/katchimeras/hatchlings/gatherglow.png'),
    mossprout: require('../assets/images/katchimeras/hatchlings/base-hatchling-v2.png'),
    pagelet: require('../assets/images/katchimeras/hatchlings/pagelet.png'),
    relicoon: require('../assets/images/katchimeras/hatchlings/relicoon.png'),
    shellio: require('../assets/images/katchimeras/hatchlings/shellio.png'),
    skylo: require('../assets/images/katchimeras/hatchlings/skylo.png'),
    steppling: require('../assets/images/katchimeras/hatchlings/steppling.png'),
    tasklet: require('../assets/images/katchimeras/hatchlings/tasklet.png'),
    vesperitt: require('../assets/images/katchimeras/hatchlings/vesperitt.png'),
  },
  medium: {
    bedrotte: require('../assets/images/katchimeras/hatchlings_lod/bedrotte_512.webp'),
    cheerlet: require('../assets/images/katchimeras/hatchlings_lod/cheerlet_512.webp'),
    feastle: require('../assets/images/katchimeras/hatchlings_lod/feastle_512.webp'),
    flickerbun: require('../assets/images/katchimeras/hatchlings_lod/flickerbun_512.webp'),
    gatherglow: require('../assets/images/katchimeras/hatchlings_lod/gatherglow_512.webp'),
    mossprout: require('../assets/images/katchimeras/hatchlings_lod/mossprout_512.webp'),
    pagelet: require('../assets/images/katchimeras/hatchlings_lod/pagelet_512.webp'),
    relicoon: require('../assets/images/katchimeras/hatchlings_lod/relicoon_512.webp'),
    shellio: require('../assets/images/katchimeras/hatchlings_lod/shellio_512.webp'),
    skylo: require('../assets/images/katchimeras/hatchlings_lod/skylo_512.webp'),
    steppling: require('../assets/images/katchimeras/hatchlings_lod/steppling_512.webp'),
    tasklet: require('../assets/images/katchimeras/hatchlings_lod/tasklet_512.webp'),
    vesperitt: require('../assets/images/katchimeras/hatchlings_lod/vesperitt_512.webp'),
  },
  thumb: {
    bedrotte: require('../assets/images/katchimeras/hatchlings_lod/bedrotte_256.webp'),
    cheerlet: require('../assets/images/katchimeras/hatchlings_lod/cheerlet_256.webp'),
    feastle: require('../assets/images/katchimeras/hatchlings_lod/feastle_256.webp'),
    flickerbun: require('../assets/images/katchimeras/hatchlings_lod/flickerbun_256.webp'),
    gatherglow: require('../assets/images/katchimeras/hatchlings_lod/gatherglow_256.webp'),
    mossprout: require('../assets/images/katchimeras/hatchlings_lod/mossprout_256.webp'),
    pagelet: require('../assets/images/katchimeras/hatchlings_lod/pagelet_256.webp'),
    relicoon: require('../assets/images/katchimeras/hatchlings_lod/relicoon_256.webp'),
    shellio: require('../assets/images/katchimeras/hatchlings_lod/shellio_256.webp'),
    skylo: require('../assets/images/katchimeras/hatchlings_lod/skylo_256.webp'),
    steppling: require('../assets/images/katchimeras/hatchlings_lod/steppling_256.webp'),
    tasklet: require('../assets/images/katchimeras/hatchlings_lod/tasklet_256.webp'),
    vesperitt: require('../assets/images/katchimeras/hatchlings_lod/vesperitt_256.webp'),
  },
};
