import { createAudioPlayer, type AudioPlayer } from 'expo-audio';
import * as Haptics from 'expo-haptics';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Pressable, StyleSheet, useWindowDimensions, View } from 'react-native';
import { ThemedText } from '@/components/themed-text';
import { Lantern } from '@/constants/theme';
import { useDisposableTimers } from '@/hooks/use-disposable-timers';
import { acquireLifecycleResource } from '@/utils/lifecycle-performance';
import { createPattern } from '@/utils/quests/experiences/pattern-memory';
import type { QuestResult } from '@/utils/quests/experiences/types';
import { ExperienceAction, ExperienceResult, QuestExperiencePreview, experienceStyles, useQuestAppActive } from './quest-experience-ui';

const TONES = [
  'data:audio/wav;base64,UklGRhQBAABXQVZFZm10IBAAAAABAAEAoA8AAEAfAAACABAAZGF0YfAAAAAAAFsPcxp3Hnkapg/vADvyYOcg43rmavA8/kIM1RZCG4EYbA+AAi317+pg5pTo1fDe/HgJWBP6F0cW0Q6rA8/3WO6u6e7qoPHn+wAHBRCoFNAT2Q1uBBv6k/EC7X/txfJW++EE5AxVEScRiAzMBAz8l/RS8D7wQPQs+x4D/QkLDlMO5ArDBKH9XveT8yTzC/Zm+7kBWAfUCl4L9AhYBNT+4fm+9ib2HvgC/LcA+gS4B1EIvwaMA6X/GPzJ+Tz5c/r9/BgA6wLABDUFTARjAhIA/v2r/Fv8Av1T/t3/LwH1ARQCowHhABoAjv9c/3v/w/8=',
  'data:audio/wav;base64,UklGRhQBAABXQVZFZm10IBAAAAABAAEAoA8AAEAfAAACABAAZGF0YfAAAAAAAOYR+hxQHfYS4QFp8Ozkf+N77Gn8XA0kGYwb4hMgBcf01OiK5fLrhvkwCTMVQRkKFKUHu/jF7A/oJ+xf93sFSRGLFn0TbQks/J/w7uoH7ff1UgKHDYsTTxJ3Cgj/QfQH7n3uSfXG/wwKYRCYEMoKQQGP9znxb/BO9eL98QYvDXIOcQrPAnD6Y/TC8vj1rPxPBBQK+gt7Ca0Dz/xm91b1NPcl/DgCMAdRCf0H3wOa/iX6Dfju+Ef8uwCeBJQGDgZqA8b/hPzH+gz7C/3i/3cC5QPJA1wCTABt/mX9cf1g/rD/0QBhAUsBxQAqAMz/x/8=',
  'data:audio/wav;base64,UklGRhQBAABXQVZFZm10IBAAAAABAAEAoA8AAEAfAAACABAAZGF0YfAAAAAAALUVuR4lFiMB2Otc4t7pzv2iEoUcChYtA9ruo+Qi6u77sw8uGp0V4QS28Qfnt+pl+u0MvxfiFEAGY/R+6ZbrMflZCkEV4RNIB9z2AOy57FX4/ge+Ep8S+QcZ+YPuGO7O9+EFPhAkEVYIFPv+8Kzvm/cIBMsNeA9fCMr8Z/Nu8br3dgJuC6QNGQg2/rb1U/Mn+DEBLwmvC4YHVf/j91X13/g5ABYHowmsBiUA5vlp99v5kv8rBYgHjwWkALj7h/kW+zv/dANpBTcE0gBR/ab7ivw1//kBTQOpArAArf68/TD+f/++AD8B7QA+AMX/wf8=',
  'data:audio/wav;base64,UklGRhQBAABXQVZFZm10IBAAAAABAAEAoA8AAEAfAAACABAAZGF0YfAAAAAAALIYlx0sC0zwNeK/6wQF5xkZGs8FVO3x473wRQkSGhwW4gBg63TmqPWrDEoZ1RGO/GrqkelP+igPrxd6DfH4ZOoV7Yb+uBBoFTwJIPY069DwKQJjEaISSAUn9LvskPQeBTkRiw/GAQTz0e4m+FQHVRBTDNb+r/JM8Wr7wwjWDicJjPwU8wD0OP5vCeQMMwb3+hj0v/Z2AGUJqAqcAxn6m/Ve+RECughNCH8B6/l197f7AgOJB/0F9P9f+n75p/1IA/YF4gMJ/1z7jPsU/+8CKAQeAsH+xPx2/ez/CAJGAtEAGP9z/hb/JgCvAHoADwA=',
];
type Config = { phraseLengths: number[]; phrases: number; targetScore: number; bpm: number; hitWindowMs: number; tier: number };
type Mode = 'sound' | 'haptic' | 'visual';
type Props = { config: Config; seed: string; onAttemptStart: (config: Record<string, unknown>) => string; onAttemptCancel: (id: string) => void; onComplete: (id: string, result: QuestResult) => void; onRunningChange: (running: boolean, id?: string | null) => void };
const COLORS = [Lantern.ember300, Lantern.auroraTeal, Lantern.auroraViolet, Lantern.auroraRose];
export function RhythmQuest({ config, seed, onAttemptStart, onAttemptCancel, onComplete, onRunningChange }: Props) {
  const { height, width } = useWindowDimensions();
  const players = useMemo(() => TONES.map((tone) => createAudioPlayer(tone)), []); const [mode, setMode] = useState<Mode>('sound'); const [started, setStarted] = useState(false); const [phrase, setPhrase] = useState(0); const [input, setInput] = useState<number[]>([]); const [playing, setPlaying] = useState(false); const [active, setActive] = useState<number | null>(null); const [correct, setCorrect] = useState(0); const [timed, setTimed] = useState(0); const attempt = useRef<string | null>(null); const startedAt = useRef(0); const inputStarted = useRef(0); const timers = useDisposableTimers('rhythm'); const beatMs = 60_000 / config.bpm; const length = config.phraseLengths[phrase] ?? 0; const pattern = useMemo(() => createPattern(`${seed}:rhythm:${phrase}`, length), [length, phrase, seed]); const totalBeats = config.phraseLengths.reduce((sum, value) => sum + value, 0); const complete = phrase >= config.phrases; const sequenceAccuracy = totalBeats ? correct / totalBeats : 0; const timingAccuracy = totalBeats ? timed / totalBeats : 0; const score = (sequenceAccuracy + timingAccuracy) / 2; const success = complete && score >= config.targetScore; const appActive = useQuestAppActive();
  const padSize = Math.max(104, Math.min(136, (Math.min(width, 360) - 40) / 2, (height - 310) / 2));
  const pulse = useCallback((pad: number) => { setActive(pad); timers.schedule(() => setActive(null), Math.min(180, beatMs * 0.45)); if (mode === 'sound') { const player: AudioPlayer = players[pad]; void player.seekTo(0).then(() => player.play()).catch(() => undefined); } if (mode !== 'visual' && process.env.EXPO_OS === 'ios') void Haptics.selectionAsync(); }, [beatMs, mode, players, timers]);
  const playPhrase = useCallback(() => { timers.cancelAll(); setPlaying(true); pattern.forEach((pad, index) => timers.schedule(() => pulse(pad), index * beatMs)); timers.schedule(() => { setPlaying(false); inputStarted.current = 0; }, pattern.length * beatMs); }, [beatMs, pattern, pulse, timers]);
  useEffect(() => {
    const releases = players.map(() => acquireLifecycleResource('audio_player', 'rhythm'));
    return () => { players.forEach((player) => player.remove()); releases.forEach((release) => release()); };
  }, [players]);
  useEffect(() => { if (!appActive) { timers.cancelAll(); setPlaying(false); setActive(null); return; } if (started && !complete) playPhrase(); }, [appActive, phrase, started]); // eslint-disable-line react-hooks/exhaustive-deps
  const start = () => { attempt.current = onAttemptStart(config); startedAt.current = Date.now(); setStarted(true); onRunningChange(true, attempt.current); };
  const reset = () => { if (attempt.current) onAttemptCancel(attempt.current); onRunningChange(false); setStarted(false); setPhrase(0); setInput([]); setCorrect(0); setTimed(0); };
  const tap = (pad: number) => { if (playing || complete) return; const index = input.length; const now = Date.now(); if (!inputStarted.current) inputStarted.current = now; pulse(pad); if (pattern[index] === pad) setCorrect((value) => value + 1); const expected = inputStarted.current + index * beatMs; if (Math.abs(now - expected) <= config.hitWindowMs) setTimed((value) => value + 1); const next = [...input, pad]; if (next.length >= pattern.length) { setInput([]); timers.schedule(() => setPhrase((value) => value + 1), 350); } else setInput(next); };
  if (!started) return <QuestExperiencePreview eyebrow="Encora" title="Echo Encora’s rhythm" body="Listen and watch, then tap the same pads back in time." icon="music.note" actionLabel="Begin rhythm" onAction={start}><View style={styles.modes}>{(['sound','haptic','visual'] as Mode[]).map((value) => <Pressable key={value} accessibilityRole="button" accessibilityState={{ selected: mode === value }} onPress={() => setMode(value)} style={[styles.mode, mode === value && styles.modeSelected]}><ThemedText numberOfLines={1} style={styles.modeText} lightColor={Lantern.moon50} darkColor={Lantern.moon50}>{value === 'sound' ? 'Sound' : value === 'haptic' ? 'Haptics' : 'Visual'}</ThemedText></Pressable>)}</View></QuestExperiencePreview>;
  if (complete && attempt.current) return <ExperienceResult success={success} title={success ? 'You caught Encora’s echo' : 'The beat drifted'} body={`Sequence ${Math.round(sequenceAccuracy * 100)}% · timing ${Math.round(timingAccuracy * 100)}%.`} metric={`${Math.round(score * 100)}%`} onRetry={reset} onComplete={() => success ? onComplete(attempt.current!, { kind: 'rhythm', success: true, sequenceAccuracy, timingAccuracy, score, durationMs: Date.now() - startedAt.current }) : reset()} />;
  return <View style={experienceStyles.root}><View style={styles.topControls}><ThemedText style={styles.progress} lightColor={Lantern.moon500} darkColor={Lantern.moon500}>PHRASE {phrase + 1} OF {config.phrases} · {config.bpm} BPM</ThemedText><ModePicker mode={mode} onChange={setMode} /></View><View style={[styles.grid, { maxWidth: padSize * 2 + 12 }]}>{COLORS.map((color, index) => <Pressable key={color} accessibilityRole="button" accessibilityLabel={`Rhythm pad ${index + 1}`} disabled={playing} onPress={() => tap(index)} style={[styles.pad, { borderColor: color, backgroundColor: active === index ? color : `${color}33`, height: padSize, width: padSize }]}><ThemedText style={styles.symbol} lightColor={Lantern.moon50} darkColor={Lantern.moon50}>{['●','▲','■','✦'][index]}</ThemedText></Pressable>)}</View><View style={experienceStyles.center}><ThemedText style={styles.status} lightColor={Lantern.moon50} darkColor={Lantern.moon50}>{playing ? 'Listen…' : `Echo it · ${input.length}/${pattern.length}`}</ThemedText>{!playing ? <ExperienceAction label="Replay phrase" quiet onPress={playPhrase} /> : null}</View></View>;
}

function ModePicker({ mode, onChange }: { mode: Mode; onChange: (mode: Mode) => void }) {
  return <View accessibilityRole="radiogroup" style={styles.modes}>{(['sound', 'haptic', 'visual'] as Mode[]).map((value) => <Pressable key={value} accessibilityRole="radio" accessibilityState={{ checked: mode === value }} onPress={() => onChange(value)} style={[styles.mode, mode === value && styles.modeSelected]}><ThemedText numberOfLines={1} style={styles.modeText} lightColor={Lantern.moon50} darkColor={Lantern.moon50}>{value === 'sound' ? 'Sound' : value === 'haptic' ? 'Haptics' : 'Visual'}</ThemedText></Pressable>)}</View>;
}

const styles = StyleSheet.create({ topControls: { gap: 8 }, modes: { alignSelf: 'center', flexDirection: 'row', gap: 7, maxWidth: 300, width: '100%' }, mode: { alignItems: 'center', borderColor: 'rgba(201,194,232,0.16)', borderCurve: 'continuous', borderRadius: 13, borderWidth: 1, flex: 1, minHeight: 38, justifyContent: 'center', paddingHorizontal: 5 }, modeSelected: { backgroundColor: 'rgba(255,195,107,0.12)', borderColor: Lantern.ember300 }, modeText: { fontSize: 11.5, fontWeight: '800' }, progress: { fontSize: 11.5, fontVariant: ['tabular-nums'], fontWeight: '900', letterSpacing: 0.8, textAlign: 'center' }, grid: { alignSelf: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, pad: { alignItems: 'center', borderCurve: 'continuous', borderRadius: 26, borderWidth: 2, justifyContent: 'center' }, symbol: { fontSize: 27, fontWeight: '900' }, status: { fontSize: 20, fontWeight: '900' } });
