// Generated by egg-snap-environment.py; geometry is owned by combat-stage-template.json.
export const ACTIVE_COMBAT_STAGE = "mossprout-duel-toy-v6" as const;
export const COMBAT_STAGE_SOURCES = { full: require("@incubator/art-world/backgrounds/duel-stages/mossprout-duel-toy-v6-full.webp"), medium: require("@incubator/art-world/backgrounds/duel-stages/mossprout-duel-toy-v6-medium.webp") };
