create schema if not exists private;

create table public.streak_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  activation_date date not null default current_date,
  timezone text not null default 'UTC',
  current_streak integer not null default 0 check (current_streak >= 0),
  longest_streak integer not null default 0 check (longest_streak >= 0),
  lifetime_captured_days integer not null default 0 check (lifetime_captured_days >= 0),
  repairs_available integer not null default 0 check (repairs_available between 0 and 2),
  repairs_capacity integer not null default 2 check (repairs_capacity between 1 and 10),
  repair_earning_progress integer not null default 0 check (repair_earning_progress between 0 and 6),
  repairable_date date,
  declined_repair_date date,
  history_imported_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.streak_days (
  user_id uuid not null references auth.users(id) on delete cascade,
  local_date date not null,
  state text not null check (state in ('captured', 'missed', 'repaired')),
  first_capture_at timestamptz,
  qualifying_capture_type text,
  first_source_id_hash text,
  timezone text not null,
  repaired_at timestamptz,
  repair_source text check (repair_source in ('earned', 'support', 'migration')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, local_date)
);

create table public.streak_capture_receipts (
  user_id uuid not null references auth.users(id) on delete cascade,
  client_event_id text not null,
  local_date date not null,
  capture_type text not null,
  source_id_hash text not null,
  occurred_at timestamptz not null,
  timezone text not null,
  is_history boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (user_id, client_event_id)
);

create table public.streak_repair_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_date date,
  delta integer not null check (delta in (-1, 1)),
  reason text not null check (reason in ('seven_captured_days', 'repair_used', 'support_adjustment')),
  created_at timestamptz not null default now()
);

create table public.streak_milestones (
  user_id uuid not null references auth.users(id) on delete cascade,
  milestone_days integer not null check (milestone_days in (3, 7, 14, 30, 50, 100, 365)),
  essence_reward integer not null check (essence_reward >= 0),
  reached_at timestamptz not null default now(),
  seen_at timestamptz,
  primary key (user_id, milestone_days)
);

create table public.streak_analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null,
  platform text,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index streak_days_user_date_idx on public.streak_days (user_id, local_date desc);
create index streak_receipts_user_date_idx on public.streak_capture_receipts (user_id, local_date desc);
create index streak_analytics_user_created_idx on public.streak_analytics_events (user_id, created_at desc);

alter table public.streak_profiles enable row level security;
alter table public.streak_days enable row level security;
alter table public.streak_capture_receipts enable row level security;
alter table public.streak_repair_ledger enable row level security;
alter table public.streak_milestones enable row level security;
alter table public.streak_analytics_events enable row level security;

create policy "Users read their streak profile" on public.streak_profiles
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users read their streak days" on public.streak_days
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users read their streak receipts" on public.streak_capture_receipts
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users read their repair ledger" on public.streak_repair_ledger
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users read their streak milestones" on public.streak_milestones
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users insert their streak analytics" on public.streak_analytics_events
  for insert to authenticated with check ((select auth.uid()) = user_id);

create or replace function private.register_daily_capture_v1(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_event_id text := payload->>'client_event_id';
  v_local_date date := (payload->>'local_date')::date;
  v_occurred_at timestamptz := (payload->>'occurred_at')::timestamptz;
  v_timezone text := coalesce(nullif(payload->>'timezone', ''), 'UTC');
  v_capture_type text := payload->>'capture_type';
  v_source_hash text := payload->>'source_id_hash';
  v_is_history boolean := coalesce((payload->>'is_history')::boolean, false);
  v_first_capture boolean := false;
  v_current integer := 0;
  v_longest integer := 0;
  v_lifetime integer := 0;
  v_progress integer := 0;
  v_repairs integer := 0;
  v_capacity integer := 2;
  v_end_date date;
  v_reward integer;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if v_event_id is null or v_capture_type is null or v_source_hash is null then
    raise exception 'Invalid capture payload';
  end if;
  perform now() at time zone v_timezone;

  insert into public.streak_profiles (user_id, activation_date, timezone)
  values (v_user_id, v_local_date, v_timezone)
  on conflict (user_id) do update set
    activation_date = least(streak_profiles.activation_date, excluded.activation_date),
    timezone = excluded.timezone,
    updated_at = now();

  insert into public.streak_capture_receipts (
    user_id, client_event_id, local_date, capture_type, source_id_hash,
    occurred_at, timezone, is_history
  ) values (
    v_user_id, v_event_id, v_local_date, v_capture_type, v_source_hash,
    v_occurred_at, v_timezone, v_is_history
  ) on conflict do nothing;

  v_first_capture := not exists (
    select 1 from public.streak_days
    where user_id = v_user_id and local_date = v_local_date and state in ('captured', 'repaired')
  );

  insert into public.streak_days (
    user_id, local_date, state, first_capture_at, qualifying_capture_type,
    first_source_id_hash, timezone
  ) values (
    v_user_id, v_local_date, 'captured', v_occurred_at, v_capture_type,
    v_source_hash, v_timezone
  ) on conflict (user_id, local_date) do update set
    state = 'captured',
    first_capture_at = coalesce(streak_days.first_capture_at, excluded.first_capture_at),
    qualifying_capture_type = coalesce(streak_days.qualifying_capture_type, excluded.qualifying_capture_type),
    first_source_id_hash = coalesce(streak_days.first_source_id_hash, excluded.first_source_id_hash),
    updated_at = now();

  select repair_earning_progress, repairs_available, repairs_capacity
    into v_progress, v_repairs, v_capacity
  from public.streak_profiles where user_id = v_user_id for update;

  if v_first_capture and not v_is_history and v_repairs < v_capacity then
    v_progress := v_progress + 1;
    if v_progress >= 7 then
      v_progress := 0;
      v_repairs := v_repairs + 1;
      insert into public.streak_repair_ledger (user_id, local_date, delta, reason)
      values (v_user_id, v_local_date, 1, 'seven_captured_days');
    end if;
  end if;

  v_end_date := case
    when exists (select 1 from public.streak_days where user_id = v_user_id and local_date = (now() at time zone v_timezone)::date and state in ('captured', 'repaired'))
      then (now() at time zone v_timezone)::date
    else (now() at time zone v_timezone)::date - 1
  end;

  select coalesce(min(offset_value), 5001) into v_current
  from generate_series(0, 5000) as offset_value
  where not exists (
    select 1 from public.streak_days
    where user_id = v_user_id
      and local_date = v_end_date - offset_value::integer
      and state in ('captured', 'repaired')
  );

  select coalesce(max(group_count), 0) into v_longest
  from (
    select count(*)::integer as group_count
    from (
      select local_date,
        local_date - (row_number() over (order by local_date))::integer as island
      from public.streak_days
      where user_id = v_user_id and state in ('captured', 'repaired')
    ) islands
    group by island
  ) streak_groups;

  select count(*)::integer into v_lifetime from public.streak_days
  where user_id = v_user_id and state = 'captured';

  update public.streak_profiles set
    current_streak = v_current,
    longest_streak = greatest(longest_streak, v_longest),
    lifetime_captured_days = v_lifetime,
    repair_earning_progress = v_progress,
    repairs_available = v_repairs,
    repairable_date = case
      when exists (
        select 1 from public.streak_days
        where user_id = v_user_id and local_date = (now() at time zone v_timezone)::date - 2 and state in ('captured', 'repaired')
      ) and not exists (
        select 1 from public.streak_days
        where user_id = v_user_id and local_date = (now() at time zone v_timezone)::date - 1 and state in ('captured', 'repaired')
      ) then (now() at time zone v_timezone)::date - 1
      else null
    end,
    history_imported_at = case when v_is_history then coalesce(history_imported_at, now()) else history_imported_at end,
    updated_at = now()
  where user_id = v_user_id;

  v_reward := case v_current
    when 3 then 3 when 7 then 7 when 14 then 10 when 30 then 20
    when 50 then 25 when 100 then 50 when 365 then 150 else null end;
  if v_reward is not null then
    insert into public.streak_milestones (user_id, milestone_days, essence_reward, reached_at)
    values (v_user_id, v_current, v_reward, v_occurred_at)
    on conflict do nothing;
  end if;

  return jsonb_build_object(
    'current_streak', v_current,
    'first_capture_of_day', v_first_capture,
    'lifetime_captured_days', v_lifetime,
    'longest_streak', v_longest,
    'repairs_available', v_repairs
  );
end;
$$;

create or replace function private.use_streak_repair_v1(target_local_date date)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_profile public.streak_profiles%rowtype;
  v_end_date date;
  v_current integer := 0;
  v_longest integer := 0;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  select * into v_profile from public.streak_profiles where user_id = v_user_id for update;
  if v_profile.repairs_available < 1 or v_profile.repairable_date is distinct from target_local_date then
    raise exception 'This day is not repairable';
  end if;
  insert into public.streak_days (user_id, local_date, state, timezone, repaired_at, repair_source)
  values (v_user_id, target_local_date, 'repaired', v_profile.timezone, now(), 'earned')
  on conflict (user_id, local_date) do update set state = 'repaired', repaired_at = now(), repair_source = 'earned', updated_at = now();
  insert into public.streak_repair_ledger (user_id, local_date, delta, reason)
  values (v_user_id, target_local_date, -1, 'repair_used');
  v_end_date := case
    when exists (select 1 from public.streak_days where user_id = v_user_id and local_date = (now() at time zone v_profile.timezone)::date and state in ('captured', 'repaired'))
      then (now() at time zone v_profile.timezone)::date
    else (now() at time zone v_profile.timezone)::date - 1
  end;
  select coalesce(min(offset_value), 5001) into v_current
  from generate_series(0, 5000) as offset_value
  where not exists (
    select 1 from public.streak_days
    where user_id = v_user_id and local_date = v_end_date - offset_value::integer and state in ('captured', 'repaired')
  );
  select coalesce(max(group_count), 0) into v_longest
  from (
    select count(*)::integer as group_count
    from (
      select local_date, local_date - (row_number() over (order by local_date))::integer as island
      from public.streak_days where user_id = v_user_id and state in ('captured', 'repaired')
    ) islands group by island
  ) streak_groups;
  update public.streak_profiles set
    repairs_available = repairs_available - 1,
    current_streak = v_current,
    longest_streak = greatest(longest_streak, v_longest),
    repairable_date = null,
    updated_at = now()
  where user_id = v_user_id;
  return jsonb_build_object('repaired', true, 'local_date', target_local_date);
end;
$$;

create or replace function public.get_streak_snapshot_v1(history_days integer default 28)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select jsonb_build_object(
    'profile', to_jsonb(profile_row),
    'days', coalesce((
      select jsonb_agg(to_jsonb(day_row) order by day_row.local_date)
      from public.streak_days day_row
      where day_row.user_id = auth.uid()
        and day_row.local_date >= current_date - greatest(1, least(history_days, 366))
    ), '[]'::jsonb),
    'milestones', coalesce((
      select jsonb_agg(to_jsonb(milestone_row) order by milestone_row.milestone_days)
      from public.streak_milestones milestone_row
      where milestone_row.user_id = auth.uid()
    ), '[]'::jsonb)
  )
  from public.streak_profiles profile_row
  where profile_row.user_id = auth.uid();
$$;

create or replace function private.decline_streak_repair_v1(target_local_date date)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  update public.streak_profiles set
    declined_repair_date = target_local_date,
    repairable_date = null,
    current_streak = case
      when exists (select 1 from public.streak_days where user_id = v_user_id and local_date > target_local_date and state = 'captured') then 1
      else 0 end,
    updated_at = now()
  where user_id = v_user_id and repairable_date = target_local_date;
  return jsonb_build_object('declined', true, 'local_date', target_local_date);
end;
$$;

create or replace function public.register_daily_capture_v1(payload jsonb)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.register_daily_capture_v1(payload);
$$;

create or replace function public.use_streak_repair_v1(target_local_date date)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.use_streak_repair_v1(target_local_date);
$$;

create or replace function public.decline_streak_repair_v1(target_local_date date)
returns jsonb
language sql
security invoker
set search_path = ''
as $$
  select private.decline_streak_repair_v1(target_local_date);
$$;

revoke all on function public.register_daily_capture_v1(jsonb) from public;
revoke all on function public.use_streak_repair_v1(date) from public;
revoke all on function public.decline_streak_repair_v1(date) from public;
revoke all on function public.get_streak_snapshot_v1(integer) from public;
grant execute on function public.register_daily_capture_v1(jsonb) to authenticated;
grant execute on function public.use_streak_repair_v1(date) to authenticated;
grant execute on function public.decline_streak_repair_v1(date) to authenticated;
grant execute on function public.get_streak_snapshot_v1(integer) to authenticated;
revoke all on function private.register_daily_capture_v1(jsonb) from public;
revoke all on function private.use_streak_repair_v1(date) from public;
revoke all on function private.decline_streak_repair_v1(date) from public;
grant usage on schema private to authenticated;
grant execute on function private.register_daily_capture_v1(jsonb) to authenticated;
grant execute on function private.use_streak_repair_v1(date) to authenticated;
grant execute on function private.decline_streak_repair_v1(date) to authenticated;
