import type { CosmeticDef } from '@/types/cosmetics';

// The cosmetics catalog. v1 = lantern colours (the egg's glow tint). Each entry is
// obtained via Discovery (unlockDiscoveryId, free) OR Essence purchase (essenceCost)
// — ownership is derived in cosmetics-engine. unlockDiscoveryId must be a real id in
// utils/discoveries-catalog.ts (harness-verified). The default has no value → the
// egg keeps its own natural day colour. No gameplay effect, ever.

export const COSMETIC_CATALOG: CosmeticDef[] = [
  {
    id: 'lantern_natural',
    type: 'lanternColour',
    name: 'Natural',
    description: "Your day's own glow.",
    swatch: '#FFC36B',
    isDefault: true,
  },
  // ── Earned via Discovery (free) ──
  {
    id: 'lantern_aurora',
    type: 'lanternColour',
    name: 'Aurora',
    description: 'A calm teal glow.',
    swatch: '#7DE8CD',
    value: '#7DE8CD',
    unlockMethod: 'discoveryUnlock',
    unlockDiscoveryId: 'first_reflection',
    rarity: 'common',
  },
  {
    id: 'lantern_rose',
    type: 'lanternColour',
    name: 'Rose',
    description: 'A warm pink glow.',
    swatch: '#F49AC1',
    value: '#F49AC1',
    unlockMethod: 'discoveryUnlock',
    unlockDiscoveryId: 'first_voice_memory',
    rarity: 'common',
  },
  {
    id: 'lantern_violet',
    type: 'lanternColour',
    name: 'Violet',
    description: 'A soft amethyst glow.',
    swatch: '#A78BFA',
    value: '#A78BFA',
    unlockMethod: 'discoveryUnlock',
    unlockDiscoveryId: 'first_big_moment',
    rarity: 'rare',
  },
  {
    id: 'lantern_sky',
    type: 'lanternColour',
    name: 'Sky',
    description: 'A bright azure glow.',
    swatch: '#92D7FF',
    value: '#92D7FF',
    unlockMethod: 'discoveryUnlock',
    unlockDiscoveryId: 'steps_20k',
    rarity: 'rare',
  },
  {
    id: 'lantern_gold',
    type: 'lanternColour',
    name: 'Gold',
    description: 'A rare golden glow.',
    swatch: '#FFD479',
    value: '#FFD479',
    unlockMethod: 'discoveryUnlock',
    unlockDiscoveryId: 'first_legendary',
    rarity: 'legendary',
  },
  // ── Bought with Essence ──
  {
    id: 'lantern_ember',
    type: 'lanternColour',
    name: 'Ember',
    description: 'A cosy ember glow.',
    swatch: '#FF8C5A',
    value: '#FF8C5A',
    unlockMethod: 'essencePurchase',
    essenceCost: 20,
    rarity: 'common',
  },
  {
    id: 'lantern_mint',
    type: 'lanternColour',
    name: 'Mint',
    description: 'A fresh mint glow.',
    swatch: '#9BE7B4',
    value: '#9BE7B4',
    unlockMethod: 'essencePurchase',
    essenceCost: 35,
    rarity: 'rare',
  },
  {
    id: 'lantern_dusk',
    type: 'lanternColour',
    name: 'Dusk',
    description: 'A deep twilight glow.',
    swatch: '#8C7BE8',
    value: '#8C7BE8',
    unlockMethod: 'essencePurchase',
    essenceCost: 50,
    rarity: 'epic',
  },

  // ── World themes — an ambient accent over the whole world; `value` is the accent
  // tint (also the lantern's fallback colour via resolveSkin). Code-only (no art).
  {
    id: 'theme_natural',
    type: 'worldTheme',
    name: 'Natural',
    description: 'Your world, unfiltered.',
    swatch: '#C4BAF0',
    isDefault: true,
  },
  {
    id: 'theme_spring_bloom',
    type: 'worldTheme',
    name: 'Spring Bloom',
    description: 'Soft blossom light.',
    swatch: '#F4A8C4',
    value: '#F4A8C4',
    unlockMethod: 'discoveryUnlock',
    unlockDiscoveryId: 'first_reflection',
    rarity: 'common',
  },
  {
    id: 'theme_ocean_breeze',
    type: 'worldTheme',
    name: 'Ocean Breeze',
    description: 'Cool sea-glass air.',
    swatch: '#7FD4E8',
    value: '#7FD4E8',
    unlockMethod: 'essencePurchase',
    essenceCost: 60,
    rarity: 'rare',
  },
  {
    id: 'theme_autumn_glow',
    type: 'worldTheme',
    name: 'Autumn Glow',
    description: 'Warm amber evenings.',
    swatch: '#E8A85C',
    value: '#E8A85C',
    unlockMethod: 'essencePurchase',
    essenceCost: 60,
    rarity: 'rare',
  },
  {
    id: 'theme_enchanted_night',
    type: 'worldTheme',
    name: 'Enchanted Night',
    description: 'Deep, starlit calm.',
    swatch: '#8C7BE8',
    value: '#8C7BE8',
    unlockMethod: 'essencePurchase',
    essenceCost: 90,
    rarity: 'epic',
  },
];
