import type { DiscoveryDef } from '@/types/discoveries';

// The static Discoveries catalog. Each entry is pure data + a pure, MONOTONIC
// predicate over the derived DiscoveryContext. Milestone / first / threshold
// based only — never "complete N quests". See docs/discoveries-system-design.md.
//
// Defs whose data source isn't live yet (country, total distance, calendar) are
// intentionally omitted here and added as those sources land.

const cat = (count: Record<string, number>, key: string) => count[key] ?? 0;

export const DISCOVERY_CATALOG_VERSION = 3;

export const DISCOVERY_CATALOG: DiscoveryDef[] = [
  // ───────────────────────── 🌍 Exploration ─────────────────────────
  {
    id: 'first_museum',
    category: 'exploration',
    name: 'Museum Explorer',
    description: 'Visited your first museum.',
    rarity: 'common',
    hidden: false,
    icon: '🏛',
    worldRewardId: 'artefact_museum_banner',
    test: (c) => cat(c.placeCategoryCounts, 'museum') >= 1,
  },
  {
    id: 'museums_5',
    category: 'exploration',
    name: 'Gallery Regular',
    description: 'Visited five museums.',
    rarity: 'rare',
    hidden: true,
    icon: '🏛',
    test: (c) => cat(c.placeCategoryCounts, 'museum') >= 5,
  },
  {
    id: 'museums_3',
    category: 'exploration',
    name: 'Three Museum Days',
    description: 'Three museum visits.',
    rarity: 'common',
    hidden: false,
    icon: 'M3',
    test: (c) => cat(c.placeCategoryCounts, 'museum') >= 3,
  },
  {
    id: 'museums_50',
    category: 'exploration',
    name: 'Curator',
    description: 'Visited fifty museums.',
    rarity: 'legendary',
    hidden: false,
    icon: '🏛',
    test: (c) => cat(c.placeCategoryCounts, 'museum') >= 50,
  },
  {
    id: 'first_park',
    category: 'exploration',
    name: 'Into the Green',
    description: 'Visited your first park.',
    rarity: 'common',
    hidden: false,
    icon: '🌳',
    test: (c) => cat(c.placeCategoryCounts, 'park') >= 1,
  },
  {
    id: 'first_cinema',
    category: 'exploration',
    name: 'Picture Night',
    description: 'Visited your first cinema.',
    rarity: 'common',
    hidden: false,
    icon: '🎬',
    test: (c) => cat(c.placeCategoryCounts, 'cinema') >= 1,
  },
  {
    id: 'cafes_10',
    category: 'exploration',
    name: 'Café Wanderer',
    description: 'Ten café visits.',
    rarity: 'rare',
    hidden: false,
    icon: '☕',
    test: (c) => cat(c.placeCategoryCounts, 'cafe') >= 10,
  },
  {
    id: 'cafes_3',
    category: 'exploration',
    name: 'Cafe Ritual',
    description: 'Three cafe visits.',
    rarity: 'common',
    hidden: false,
    icon: 'C3',
    test: (c) => cat(c.placeCategoryCounts, 'cafe') >= 3,
  },
  {
    id: 'parks_3',
    category: 'exploration',
    name: 'Green Return',
    description: 'Three park visits.',
    rarity: 'common',
    hidden: false,
    icon: 'P3',
    test: (c) => cat(c.placeCategoryCounts, 'park') >= 3,
  },
  {
    id: 'places_10',
    category: 'exploration',
    name: 'Ten Places Marked',
    description: 'Ten places marked.',
    rarity: 'common',
    hidden: false,
    icon: '10',
    test: (c) => c.uniquePlaceCount >= 10,
  },
  {
    id: 'places_25',
    category: 'exploration',
    name: 'Wanderer',
    description: 'Twenty-five places marked.',
    rarity: 'rare',
    hidden: false,
    icon: '🗺',
    test: (c) => c.uniquePlaceCount >= 25,
  },
  {
    id: 'places_100',
    category: 'exploration',
    name: 'Cartographer',
    description: 'A hundred places marked.',
    rarity: 'legendary',
    hidden: false,
    icon: '🧭',
    test: (c) => c.uniquePlaceCount >= 100,
  },

  // ───────────────────────── 📸 Memory ─────────────────────────
  {
    id: 'first_memory',
    category: 'memory',
    name: 'First Memory',
    description: 'Captured your first memory.',
    rarity: 'common',
    hidden: false,
    icon: '📸',
    test: (c) => c.photoCount >= 1,
  },
  {
    id: 'first_voice_memory',
    category: 'memory',
    name: 'First Words',
    description: 'Recorded your first voice memory.',
    rarity: 'common',
    hidden: false,
    icon: '🎙',
    worldRewardId: 'artefact_voice_crystal',
    test: (c) => c.voiceMemoryCount >= 1,
  },
  {
    id: 'voice_10',
    category: 'memory',
    name: 'In Your Own Voice',
    description: 'Ten voice memories.',
    rarity: 'rare',
    hidden: false,
    icon: '🎙',
    test: (c) => c.voiceMemoryCount >= 10,
  },
  {
    id: 'voice_5',
    category: 'memory',
    name: 'Five Voice Memories',
    description: 'Five voice memories.',
    rarity: 'common',
    hidden: false,
    icon: 'V5',
    test: (c) => c.voiceMemoryCount >= 5,
  },
  {
    id: 'photos_10',
    category: 'memory',
    name: 'Ten Kept Memories',
    description: 'Ten memories captured.',
    rarity: 'common',
    hidden: false,
    icon: '10',
    test: (c) => c.photoCount >= 10,
  },
  {
    id: 'photos_50',
    category: 'memory',
    name: 'Fifty Kept Memories',
    description: 'Fifty memories captured.',
    rarity: 'rare',
    hidden: false,
    icon: '50',
    test: (c) => c.photoCount >= 50,
  },
  {
    id: 'photos_100',
    category: 'memory',
    name: 'Chronicler',
    description: 'A hundred memories captured.',
    rarity: 'epic',
    hidden: false,
    icon: '📷',
    test: (c) => c.photoCount >= 100,
  },
  {
    id: 'meaningful_50',
    category: 'memory',
    name: 'Held Moments',
    description: 'Fifty meaningful moments.',
    rarity: 'rare',
    hidden: false,
    icon: '✨',
    test: (c) => c.meaningfulMomentCount >= 50,
  },
  {
    id: 'meaningful_100',
    category: 'memory',
    name: 'A Life of Meaning',
    description: 'A hundred meaningful moments.',
    rarity: 'legendary',
    hidden: false,
    icon: '💫',
    test: (c) => c.meaningfulMomentCount >= 100,
  },
  {
    id: 'first_food',
    category: 'memory',
    name: 'First Taste',
    description: 'Saved your first food memory.',
    rarity: 'common',
    hidden: false,
    icon: '🍽',
    test: (c) => c.foodMemoryCount >= 1,
  },

  // ───────────────────────── ❤️ Life ─────────────────────────
  {
    id: 'food_10',
    category: 'memory',
    name: 'Table of Ten',
    description: 'Ten food memories saved.',
    rarity: 'rare',
    hidden: false,
    icon: 'F10',
    test: (c) => c.foodMemoryCount >= 10,
  },
  {
    id: 'studio_10',
    category: 'memory',
    name: 'Study Shelf',
    description: 'Ten inspirations saved.',
    rarity: 'rare',
    hidden: false,
    icon: 'S10',
    test: (c) => c.studioMemoryCount >= 10,
  },

  {
    id: 'first_big_moment',
    category: 'life',
    name: 'A Day That Mattered',
    description: 'Marked your first big moment.',
    rarity: 'rare',
    hidden: false,
    icon: '⭐️',
    test: (c) => c.bigMomentCount >= 1,
  },
  {
    id: 'goal_achieved',
    category: 'life',
    name: 'Goal Achieved',
    description: 'Marked an achievement.',
    rarity: 'rare',
    hidden: false,
    icon: 'GO',
    worldRewardId: 'artefact_life_monument',
    test: (c) => c.achievementMomentCount >= 1,
  },
  {
    id: 'big_birthday',
    category: 'life',
    name: 'Another Year',
    description: 'Marked a birthday.',
    rarity: 'rare',
    hidden: false,
    icon: '🎂',
    worldRewardId: 'artefact_festival_tree',
    test: (c) => c.bigMomentTypes.has('birthday'),
  },
  {
    id: 'big_trip',
    category: 'life',
    name: 'Away We Go',
    description: 'Marked a trip.',
    rarity: 'rare',
    hidden: false,
    icon: '🧳',
    worldRewardId: 'artefact_golden_arch',
    test: (c) => c.bigMomentTypes.has('trip'),
  },
  {
    id: 'big_milestone',
    category: 'life',
    name: 'A Turning Point',
    description: 'Marked a milestone.',
    rarity: 'epic',
    hidden: false,
    icon: '🗿',
    worldRewardId: 'artefact_life_monument',
    test: (c) => c.bigMomentTypes.has('milestone'),
  },

  // ───────────────────────── 🚶 Journey ─────────────────────────
  {
    id: 'steps_10k',
    category: 'journey',
    name: 'Ten Thousand',
    description: 'A 10,000-step day.',
    rarity: 'common',
    hidden: false,
    icon: '🚶',
    test: (c) => c.maxStepsInADay >= 10000,
  },
  {
    id: 'steps_15k',
    category: 'journey',
    name: 'Fifteen Thousand',
    description: 'A 15,000-step day.',
    rarity: 'common',
    hidden: false,
    icon: '15k',
    test: (c) => c.maxStepsInADay >= 15000,
  },
  {
    id: 'steps_20k',
    category: 'journey',
    name: 'Marathoner',
    description: 'A 20,000-step day.',
    rarity: 'rare',
    hidden: false,
    icon: '🥾',
    worldRewardId: 'artefact_journey_monument',
    test: (c) => c.maxStepsInADay >= 20000,
  },
  {
    id: 'steps_30k',
    category: 'journey',
    name: 'Thirty Thousand',
    description: 'A 30,000-step day.',
    rarity: 'epic',
    hidden: false,
    icon: '30k',
    worldRewardId: 'artefact_trail_bridge',
    test: (c) => c.maxStepsInADay >= 30000,
  },
  {
    id: 'walk_streak_3',
    category: 'journey',
    name: 'Three Days On',
    description: 'Three consecutive walking days.',
    rarity: 'common',
    hidden: false,
    icon: '3d',
    test: (c) => c.walkingStreak >= 3,
  },
  {
    id: 'walk_streak_7',
    category: 'journey',
    name: 'Seven Days On',
    description: 'Seven consecutive walking days.',
    rarity: 'epic',
    hidden: true,
    icon: '🌉',
    worldRewardId: 'artefact_trail_bridge',
    test: (c) => c.walkingStreak >= 7,
  },

  // ───────────────────────── 🌿 Reflection ─────────────────────────
  {
    id: 'first_reflection',
    category: 'reflection',
    name: 'First Pause',
    description: 'Your first reflection.',
    rarity: 'common',
    hidden: false,
    icon: '🌿',
    test: (c) => c.reflectionCount >= 1,
  },
  {
    id: 'reflections_3',
    category: 'reflection',
    name: 'Three Pauses',
    description: 'Three reflections.',
    rarity: 'common',
    hidden: false,
    icon: 'R3',
    test: (c) => c.reflectionCount >= 3,
  },
  {
    id: 'reflections_10',
    category: 'reflection',
    name: 'Inward Looking',
    description: 'Ten reflections.',
    rarity: 'rare',
    hidden: false,
    icon: '🍃',
    test: (c) => c.reflectionCount >= 10,
  },
  {
    id: 'calm_7',
    category: 'reflection',
    name: 'A Quiet Week',
    description: 'Seven calm days.',
    rarity: 'rare',
    hidden: false,
    icon: 'C7',
    test: (c) => c.calmDayCount >= 7,
  },
  {
    id: 'calm_30',
    category: 'reflection',
    name: 'Still Water',
    description: 'Thirty calm days.',
    rarity: 'epic',
    hidden: false,
    icon: '🕯',
    worldRewardId: 'artefact_memory_lantern',
    test: (c) => c.calmDayCount >= 30,
  },

  // ───────────────────────── 🌎 World ─────────────────────────
  {
    id: 'first_patch',
    category: 'world',
    name: 'A Day Remembered',
    description: 'Finished your first day in the world.',
    rarity: 'common',
    hidden: false,
    icon: '🌱',
    test: (c) => c.finalisedPatchCount >= 1,
  },
  {
    id: 'first_3_patches',
    category: 'world',
    name: 'A Village Forming',
    description: 'Finished three days in your world.',
    rarity: 'common',
    hidden: false,
    icon: '3',
    test: (c) => c.finalisedPatchCount >= 3,
  },
  {
    id: 'first_week_village',
    category: 'world',
    name: 'First Week Village',
    description: 'Seven days became your first village.',
    rarity: 'rare',
    hidden: false,
    icon: '7',
    worldRewardId: 'artefact_life_monument',
    test: (c) => c.finalisedPatchCount >= 7,
  },
  {
    id: 'patches_30',
    category: 'world',
    name: 'Thirty Days Remembered',
    description: 'Thirty finished days in your world.',
    rarity: 'epic',
    hidden: false,
    icon: '30',
    worldRewardId: 'artefact_memory_lantern',
    test: (c) => c.finalisedPatchCount >= 30,
  },
  {
    id: 'patches_100',
    category: 'world',
    name: 'A Hundred Days',
    description: 'A hundred finished days in your world.',
    rarity: 'legendary',
    hidden: false,
    icon: '🌎',
    test: (c) => c.finalisedPatchCount >= 100,
  },
  {
    id: 'first_legendary',
    category: 'world',
    name: 'Once in a While',
    description: 'Hatched a legendary katchimera.',
    rarity: 'epic',
    hidden: true,
    icon: '🌟',
    test: (c) => c.legendaryPatchCount >= 1,
  },
  {
    id: 'parks_10', category: 'exploration', name: 'Green Familiar', description: 'Ten park visits.',
    rarity: 'rare', hidden: false, icon: '🌿', test: (c) => cat(c.placeCategoryCounts, 'park') >= 10,
  },
  {
    id: 'parks_25', category: 'exploration', name: 'Keeper of Green Places', description: 'Twenty-five park visits.',
    rarity: 'epic', hidden: false, icon: '🌳', test: (c) => cat(c.placeCategoryCounts, 'park') >= 25,
  },
  {
    id: 'cafes_25', category: 'exploration', name: 'A Table Waiting', description: 'Twenty-five café visits.',
    rarity: 'epic', hidden: false, icon: '☕', test: (c) => cat(c.placeCategoryCounts, 'cafe') >= 25,
  },
  {
    id: 'cinemas_5', category: 'exploration', name: 'Five Evenings in Frame', description: 'Five cinema visits.',
    rarity: 'rare', hidden: false, icon: '🎞️', test: (c) => cat(c.placeCategoryCounts, 'cinema') >= 5,
  },
  {
    id: 'cinemas_20', category: 'exploration', name: 'House Lights Down', description: 'Twenty cinema visits.',
    rarity: 'epic', hidden: true, icon: '🎬', test: (c) => cat(c.placeCategoryCounts, 'cinema') >= 20,
  },
  {
    id: 'voice_25', category: 'memory', name: 'A Voice Kept', description: 'Twenty-five voice memories.',
    rarity: 'epic', hidden: false, icon: '🎙️', test: (c) => c.voiceMemoryCount >= 25,
  },
  {
    id: 'food_25', category: 'memory', name: 'Table of Twenty-Five', description: 'Twenty-five food memories.',
    rarity: 'epic', hidden: false, icon: '🍽️', test: (c) => c.foodMemoryCount >= 25,
  },
  {
    id: 'food_50', category: 'memory', name: 'A Life at the Table', description: 'Fifty food memories.',
    rarity: 'legendary', hidden: false, icon: '🥘', test: (c) => c.foodMemoryCount >= 50,
  },
  {
    id: 'studio_25', category: 'memory', name: 'Shelf of Influences', description: 'Twenty-five inspirations saved.',
    rarity: 'epic', hidden: false, icon: '📚', test: (c) => c.studioMemoryCount >= 25,
  },
  {
    id: 'studio_50', category: 'memory', name: 'A Personal Canon', description: 'Fifty inspirations saved.',
    rarity: 'legendary', hidden: true, icon: '✨', test: (c) => c.studioMemoryCount >= 50,
  },
  {
    id: 'big_moments_3', category: 'life', name: 'Three Turning Points', description: 'Three big moments marked.',
    rarity: 'rare', hidden: false, icon: '⭐', test: (c) => c.bigMomentCount >= 3,
  },
  {
    id: 'big_moments_10', category: 'life', name: 'A Life in Chapters', description: 'Ten big moments marked.',
    rarity: 'epic', hidden: false, icon: '📖', test: (c) => c.bigMomentCount >= 10,
  },
  {
    id: 'big_moments_25', category: 'life', name: 'Many Chapters', description: 'Twenty-five big moments marked.',
    rarity: 'legendary', hidden: true, icon: '🌟', test: (c) => c.bigMomentCount >= 25,
  },
  {
    id: 'walk_streak_14', category: 'journey', name: 'Two Weeks On', description: 'Fourteen consecutive walking days.',
    rarity: 'epic', hidden: false, icon: '🥾', test: (c) => c.walkingStreak >= 14,
  },
  {
    id: 'walk_streak_30', category: 'journey', name: 'A Month in Motion', description: 'Thirty consecutive walking days.',
    rarity: 'legendary', hidden: true, icon: '🛤️', test: (c) => c.walkingStreak >= 30,
  },
  {
    id: 'reflections_25', category: 'reflection', name: 'A Habit of Returning', description: 'Twenty-five reflections.',
    rarity: 'epic', hidden: false, icon: '🍃', test: (c) => c.reflectionCount >= 25,
  },
  {
    id: 'reflections_50', category: 'reflection', name: 'Inner Archive', description: 'Fifty reflections.',
    rarity: 'legendary', hidden: true, icon: '🕯️', test: (c) => c.reflectionCount >= 50,
  },
  {
    id: 'legendary_3', category: 'world', name: 'Constellation of Rarities', description: 'Three legendary Katchimeras hatched.',
    rarity: 'legendary', hidden: true, icon: '🌌', test: (c) => c.legendaryPatchCount >= 3,
  },
];

/** Discoveries without a natural companion owner remain in the app-wide hall. */
export const COMPANION_OWNED_DISCOVERY_IDS = new Set([
  'big_birthday', 'big_milestone', 'big_moments_10', 'big_moments_25', 'big_moments_3', 'big_trip',
  'cafes_10', 'cafes_25', 'cafes_3', 'calm_30', 'calm_7', 'cinemas_20', 'cinemas_5',
  'first_big_moment', 'first_cinema', 'first_food', 'first_museum', 'first_park', 'first_reflection',
  'food_10', 'food_25', 'food_50', 'goal_achieved', 'museums_3', 'museums_5', 'museums_50',
  'parks_10', 'parks_25', 'parks_3', 'places_10', 'places_25', 'places_100',
  'reflections_3', 'reflections_10', 'reflections_25', 'reflections_50',
  'steps_10k', 'steps_15k', 'steps_20k', 'steps_30k',
  'walk_streak_3', 'walk_streak_7', 'walk_streak_14', 'walk_streak_30',
]);

export const GLOBAL_DISCOVERY_CATALOG: DiscoveryDef[] = DISCOVERY_CATALOG.filter(
  (definition) => !COMPANION_OWNED_DISCOVERY_IDS.has(definition.id)
);
