import type { DiscoveryDef } from '@/types/discoveries';

// The static Discoveries catalog. Each entry is pure data + a pure, MONOTONIC
// predicate over the derived DiscoveryContext. Milestone / first / threshold
// based only — never "complete N quests". See docs/discoveries-system-design.md.
//
// Defs whose data source isn't live yet (country, total distance, calendar) are
// intentionally omitted here and added as those sources land.

const cat = (count: Record<string, number>, key: string) => count[key] ?? 0;

export const DISCOVERY_CATALOG: DiscoveryDef[] = [
  // ───────────────────────── 🌍 Exploration ─────────────────────────
  {
    id: 'first_museum',
    category: 'exploration',
    name: 'Museum Explorer',
    description: 'Visited your first museum.',
    rarity: 'common',
    hidden: false,
    icon: '🏛',
    worldRewardId: 'artefact_museum_banner',
    test: (c) => cat(c.placeCategoryCounts, 'museum') >= 1,
  },
  {
    id: 'museums_5',
    category: 'exploration',
    name: 'Gallery Regular',
    description: 'Visited five museums.',
    rarity: 'rare',
    hidden: true,
    icon: '🏛',
    test: (c) => cat(c.placeCategoryCounts, 'museum') >= 5,
  },
  {
    id: 'museums_3',
    category: 'exploration',
    name: 'Three Museum Days',
    description: 'Three museum visits.',
    rarity: 'common',
    hidden: false,
    icon: 'M3',
    test: (c) => cat(c.placeCategoryCounts, 'museum') >= 3,
  },
  {
    id: 'museums_50',
    category: 'exploration',
    name: 'Curator',
    description: 'Visited fifty museums.',
    rarity: 'legendary',
    hidden: false,
    icon: '🏛',
    test: (c) => cat(c.placeCategoryCounts, 'museum') >= 50,
  },
  {
    id: 'first_park',
    category: 'exploration',
    name: 'Into the Green',
    description: 'Visited your first park.',
    rarity: 'common',
    hidden: false,
    icon: '🌳',
    test: (c) => cat(c.placeCategoryCounts, 'park') >= 1,
  },
  {
    id: 'first_cinema',
    category: 'exploration',
    name: 'Picture Night',
    description: 'Visited your first cinema.',
    rarity: 'common',
    hidden: false,
    icon: '🎬',
    test: (c) => cat(c.placeCategoryCounts, 'cinema') >= 1,
  },
  {
    id: 'cafes_10',
    category: 'exploration',
    name: 'Café Wanderer',
    description: 'Ten café visits.',
    rarity: 'rare',
    hidden: false,
    icon: '☕',
    test: (c) => cat(c.placeCategoryCounts, 'cafe') >= 10,
  },
  {
    id: 'cafes_3',
    category: 'exploration',
    name: 'Cafe Ritual',
    description: 'Three cafe visits.',
    rarity: 'common',
    hidden: false,
    icon: 'C3',
    test: (c) => cat(c.placeCategoryCounts, 'cafe') >= 3,
  },
  {
    id: 'parks_3',
    category: 'exploration',
    name: 'Green Return',
    description: 'Three park visits.',
    rarity: 'common',
    hidden: false,
    icon: 'P3',
    test: (c) => cat(c.placeCategoryCounts, 'park') >= 3,
  },
  {
    id: 'places_10',
    category: 'exploration',
    name: 'Ten Places Marked',
    description: 'Ten places marked.',
    rarity: 'common',
    hidden: false,
    icon: '10',
    test: (c) => c.uniquePlaceCount >= 10,
  },
  {
    id: 'places_25',
    category: 'exploration',
    name: 'Wanderer',
    description: 'Twenty-five places marked.',
    rarity: 'rare',
    hidden: false,
    icon: '🗺',
    test: (c) => c.uniquePlaceCount >= 25,
  },
  {
    id: 'places_100',
    category: 'exploration',
    name: 'Cartographer',
    description: 'A hundred places marked.',
    rarity: 'legendary',
    hidden: false,
    icon: '🧭',
    test: (c) => c.uniquePlaceCount >= 100,
  },

  // ───────────────────────── 📸 Memory ─────────────────────────
  {
    id: 'first_memory',
    category: 'memory',
    name: 'First Memory',
    description: 'Captured your first memory.',
    rarity: 'common',
    hidden: false,
    icon: '📸',
    test: (c) => c.photoCount >= 1,
  },
  {
    id: 'first_voice_memory',
    category: 'memory',
    name: 'First Words',
    description: 'Recorded your first voice memory.',
    rarity: 'common',
    hidden: false,
    icon: '🎙',
    worldRewardId: 'artefact_voice_crystal',
    test: (c) => c.voiceMemoryCount >= 1,
  },
  {
    id: 'voice_10',
    category: 'memory',
    name: 'In Your Own Voice',
    description: 'Ten voice memories.',
    rarity: 'rare',
    hidden: false,
    icon: '🎙',
    test: (c) => c.voiceMemoryCount >= 10,
  },
  {
    id: 'voice_5',
    category: 'memory',
    name: 'Five Voice Memories',
    description: 'Five voice memories.',
    rarity: 'common',
    hidden: false,
    icon: 'V5',
    test: (c) => c.voiceMemoryCount >= 5,
  },
  {
    id: 'photos_10',
    category: 'memory',
    name: 'Ten Kept Memories',
    description: 'Ten memories captured.',
    rarity: 'common',
    hidden: false,
    icon: '10',
    test: (c) => c.photoCount >= 10,
  },
  {
    id: 'photos_50',
    category: 'memory',
    name: 'Fifty Kept Memories',
    description: 'Fifty memories captured.',
    rarity: 'rare',
    hidden: false,
    icon: '50',
    test: (c) => c.photoCount >= 50,
  },
  {
    id: 'photos_100',
    category: 'memory',
    name: 'Chronicler',
    description: 'A hundred memories captured.',
    rarity: 'epic',
    hidden: false,
    icon: '📷',
    test: (c) => c.photoCount >= 100,
  },
  {
    id: 'meaningful_50',
    category: 'memory',
    name: 'Held Moments',
    description: 'Fifty meaningful moments.',
    rarity: 'rare',
    hidden: false,
    icon: '✨',
    test: (c) => c.meaningfulMomentCount >= 50,
  },
  {
    id: 'meaningful_100',
    category: 'memory',
    name: 'A Life of Meaning',
    description: 'A hundred meaningful moments.',
    rarity: 'legendary',
    hidden: false,
    icon: '💫',
    test: (c) => c.meaningfulMomentCount >= 100,
  },
  {
    id: 'first_food',
    category: 'memory',
    name: 'First Taste',
    description: 'Saved your first food memory.',
    rarity: 'common',
    hidden: false,
    icon: '🍽',
    test: (c) => c.foodMemoryCount >= 1,
  },

  // ───────────────────────── ❤️ Life ─────────────────────────
  {
    id: 'food_10',
    category: 'memory',
    name: 'Table of Ten',
    description: 'Ten food memories saved.',
    rarity: 'rare',
    hidden: false,
    icon: 'F10',
    test: (c) => c.foodMemoryCount >= 10,
  },
  {
    id: 'studio_10',
    category: 'memory',
    name: 'Study Shelf',
    description: 'Ten inspirations saved.',
    rarity: 'rare',
    hidden: false,
    icon: 'S10',
    test: (c) => c.studioMemoryCount >= 10,
  },

  {
    id: 'first_big_moment',
    category: 'life',
    name: 'A Day That Mattered',
    description: 'Marked your first big moment.',
    rarity: 'rare',
    hidden: false,
    icon: '⭐️',
    test: (c) => c.bigMomentCount >= 1,
  },
  {
    id: 'goal_achieved',
    category: 'life',
    name: 'Goal Achieved',
    description: 'Marked an achievement.',
    rarity: 'rare',
    hidden: false,
    icon: 'GO',
    worldRewardId: 'artefact_life_monument',
    test: (c) => c.achievementMomentCount >= 1,
  },
  {
    id: 'big_birthday',
    category: 'life',
    name: 'Another Year',
    description: 'Marked a birthday.',
    rarity: 'rare',
    hidden: false,
    icon: '🎂',
    worldRewardId: 'artefact_festival_tree',
    test: (c) => c.bigMomentTypes.has('birthday'),
  },
  {
    id: 'big_trip',
    category: 'life',
    name: 'Away We Go',
    description: 'Marked a trip.',
    rarity: 'rare',
    hidden: false,
    icon: '🧳',
    worldRewardId: 'artefact_golden_arch',
    test: (c) => c.bigMomentTypes.has('trip'),
  },
  {
    id: 'big_milestone',
    category: 'life',
    name: 'A Turning Point',
    description: 'Marked a milestone.',
    rarity: 'epic',
    hidden: false,
    icon: '🗿',
    worldRewardId: 'artefact_life_monument',
    test: (c) => c.bigMomentTypes.has('milestone'),
  },

  // ───────────────────────── 🚶 Journey ─────────────────────────
  {
    id: 'steps_10k',
    category: 'journey',
    name: 'Ten Thousand',
    description: 'A 10,000-step day.',
    rarity: 'common',
    hidden: false,
    icon: '🚶',
    test: (c) => c.maxStepsInADay >= 10000,
  },
  {
    id: 'steps_15k',
    category: 'journey',
    name: 'Fifteen Thousand',
    description: 'A 15,000-step day.',
    rarity: 'common',
    hidden: false,
    icon: '15k',
    test: (c) => c.maxStepsInADay >= 15000,
  },
  {
    id: 'steps_20k',
    category: 'journey',
    name: 'Marathoner',
    description: 'A 20,000-step day.',
    rarity: 'rare',
    hidden: false,
    icon: '🥾',
    worldRewardId: 'artefact_journey_monument',
    test: (c) => c.maxStepsInADay >= 20000,
  },
  {
    id: 'steps_30k',
    category: 'journey',
    name: 'Thirty Thousand',
    description: 'A 30,000-step day.',
    rarity: 'epic',
    hidden: false,
    icon: '30k',
    worldRewardId: 'artefact_trail_bridge',
    test: (c) => c.maxStepsInADay >= 30000,
  },
  {
    id: 'walk_streak_3',
    category: 'journey',
    name: 'Three Days On',
    description: 'Three consecutive walking days.',
    rarity: 'common',
    hidden: false,
    icon: '3d',
    test: (c) => c.walkingStreak >= 3,
  },
  {
    id: 'walk_streak_7',
    category: 'journey',
    name: 'Seven Days On',
    description: 'Seven consecutive walking days.',
    rarity: 'epic',
    hidden: true,
    icon: '🌉',
    worldRewardId: 'artefact_trail_bridge',
    test: (c) => c.walkingStreak >= 7,
  },

  // ───────────────────────── 🌿 Reflection ─────────────────────────
  {
    id: 'first_reflection',
    category: 'reflection',
    name: 'First Pause',
    description: 'Your first reflection.',
    rarity: 'common',
    hidden: false,
    icon: '🌿',
    test: (c) => c.reflectionCount >= 1,
  },
  {
    id: 'reflections_3',
    category: 'reflection',
    name: 'Three Pauses',
    description: 'Three reflections.',
    rarity: 'common',
    hidden: false,
    icon: 'R3',
    test: (c) => c.reflectionCount >= 3,
  },
  {
    id: 'reflections_10',
    category: 'reflection',
    name: 'Inward Looking',
    description: 'Ten reflections.',
    rarity: 'rare',
    hidden: false,
    icon: '🍃',
    test: (c) => c.reflectionCount >= 10,
  },
  {
    id: 'calm_7',
    category: 'reflection',
    name: 'A Quiet Week',
    description: 'Seven calm days.',
    rarity: 'rare',
    hidden: false,
    icon: 'C7',
    test: (c) => c.calmDayCount >= 7,
  },
  {
    id: 'calm_30',
    category: 'reflection',
    name: 'Still Water',
    description: 'Thirty calm days.',
    rarity: 'epic',
    hidden: false,
    icon: '🕯',
    worldRewardId: 'artefact_memory_lantern',
    test: (c) => c.calmDayCount >= 30,
  },

  // ───────────────────────── 🌎 World ─────────────────────────
  {
    id: 'first_patch',
    category: 'world',
    name: 'A Day Remembered',
    description: 'Finished your first day in the world.',
    rarity: 'common',
    hidden: false,
    icon: '🌱',
    test: (c) => c.finalisedPatchCount >= 1,
  },
  {
    id: 'first_3_patches',
    category: 'world',
    name: 'A Village Forming',
    description: 'Finished three days in your world.',
    rarity: 'common',
    hidden: false,
    icon: '3',
    test: (c) => c.finalisedPatchCount >= 3,
  },
  {
    id: 'first_week_village',
    category: 'world',
    name: 'First Week Village',
    description: 'Seven days became your first village.',
    rarity: 'rare',
    hidden: false,
    icon: '7',
    worldRewardId: 'artefact_life_monument',
    test: (c) => c.finalisedPatchCount >= 7,
  },
  {
    id: 'patches_30',
    category: 'world',
    name: 'Thirty Days Remembered',
    description: 'Thirty finished days in your world.',
    rarity: 'epic',
    hidden: false,
    icon: '30',
    worldRewardId: 'artefact_memory_lantern',
    test: (c) => c.finalisedPatchCount >= 30,
  },
  {
    id: 'patches_100',
    category: 'world',
    name: 'A Hundred Days',
    description: 'A hundred finished days in your world.',
    rarity: 'legendary',
    hidden: false,
    icon: '🌎',
    test: (c) => c.finalisedPatchCount >= 100,
  },
  {
    id: 'first_legendary',
    category: 'world',
    name: 'Once in a While',
    description: 'Hatched a legendary katchimera.',
    rarity: 'epic',
    hidden: true,
    icon: '🌟',
    test: (c) => c.legendaryPatchCount >= 1,
  },
];
