import type { DiscoveryRarity } from '@/types/discoveries';
import type { ObservationKind } from '@/utils/observations-engine';

export type WorldPropCategory = 'starter' | 'nature' | 'landmark' | 'ritual' | 'memory';
export type WorldPropUnlockKind = 'starter' | 'discovery' | 'observation' | 'mood';

export type WorldPropDef = {
  id: string;
  assetKey: string;
  name: string;
  description: string;
  category: WorldPropCategory;
  unlockKind: WorldPropUnlockKind;
  unlockSourceId?: string;
  starterIntentId?: 'memory' | 'trail' | 'quiet' | 'gathering' | 'study';
  sourceLabel: string;
  lockedLabel: string;
  rarity?: DiscoveryRarity;
  sizeScale?: number;
};

export const STARTER_WORLD_PROPS: WorldPropDef[] = [
  {
    id: 'starter_memory_tree',
    assetKey: 'memory_tree_1',
    name: 'Memory Tree',
    description: 'For remembering small moments before they disappear.',
    category: 'starter',
    unlockKind: 'starter',
    starterIntentId: 'memory',
    sourceLabel: 'First Seed',
    lockedLabel: 'Choose this as your first seed.',
    rarity: 'common',
    sizeScale: 1.15,
  },
  {
    id: 'starter_trail_lantern',
    assetKey: 'decor_12',
    name: 'Trail Lantern',
    description: 'For noticing the routes, walks, and places life leaves behind.',
    category: 'starter',
    unlockKind: 'starter',
    starterIntentId: 'trail',
    sourceLabel: 'First Seed',
    lockedLabel: 'Choose this as your first seed.',
    rarity: 'common',
    sizeScale: 1.15,
  },
  {
    id: 'starter_quiet_bench',
    assetKey: 'prop_bench',
    name: 'Quiet Bench',
    description: 'For giving your world somewhere calm to pause.',
    category: 'starter',
    unlockKind: 'starter',
    starterIntentId: 'quiet',
    sourceLabel: 'First Seed',
    lockedLabel: 'Choose this as your first seed.',
    rarity: 'common',
    sizeScale: 0.95,
  },
  {
    id: 'starter_gathering_table',
    assetKey: 'prop_coffee_table',
    name: 'Gathering Table',
    description: 'For people, food, and small shared rituals.',
    category: 'starter',
    unlockKind: 'starter',
    starterIntentId: 'gathering',
    sourceLabel: 'First Seed',
    lockedLabel: 'Choose this as your first seed.',
    rarity: 'common',
    sizeScale: 1.0,
  },
  {
    id: 'starter_study_lamp',
    assetKey: 'prop_lantern',
    name: 'Study Lamp',
    description: 'For books, films, ideas, and anything that stays with you.',
    category: 'starter',
    unlockKind: 'starter',
    starterIntentId: 'study',
    sourceLabel: 'First Seed',
    lockedLabel: 'Choose this as your first seed.',
    rarity: 'common',
    sizeScale: 0.95,
  },
];

export const EARNED_WORLD_PROPS: WorldPropDef[] = [
  {
    id: 'prop_first_memory_blossom',
    assetKey: 'decor_7',
    name: 'Memory Flowers',
    description: 'A small bloom for the first memory you kept.',
    category: 'nature',
    unlockKind: 'discovery',
    unlockSourceId: 'first_memory',
    sourceLabel: 'Earned from First Memory',
    lockedLabel: 'Capture your first memory.',
    rarity: 'common',
  },
  {
    id: 'prop_voice_crystal',
    assetKey: 'artefact_voice_crystal',
    name: 'Voice Crystal',
    description: 'A marker for the first memory saved in your own voice.',
    category: 'memory',
    unlockKind: 'discovery',
    unlockSourceId: 'first_voice_memory',
    sourceLabel: 'Earned from First Words',
    lockedLabel: 'Record your first voice memory.',
    rarity: 'common',
    sizeScale: 0.9,
  },
  {
    id: 'prop_museum_banner',
    assetKey: 'artefact_museum_banner',
    name: 'Museum Banner',
    description: 'A banner for the day curiosity opened a public room.',
    category: 'landmark',
    unlockKind: 'discovery',
    unlockSourceId: 'first_museum',
    sourceLabel: 'Earned from Museum Explorer',
    lockedLabel: 'Visit your first museum.',
    rarity: 'common',
  },
  {
    id: 'prop_cafe_table',
    assetKey: 'prop_coffee_table',
    name: 'Cafe Table',
    description: 'A table for routines that begin to feel familiar.',
    category: 'ritual',
    unlockKind: 'discovery',
    unlockSourceId: 'cafes_3',
    sourceLabel: 'Earned from Cafe Ritual',
    lockedLabel: 'Mark three cafe visits.',
    rarity: 'common',
  },
  {
    id: 'prop_food_stall',
    assetKey: 'food_stall',
    name: 'Feast Stall',
    description: 'A little place for food memories that keep returning.',
    category: 'ritual',
    unlockKind: 'discovery',
    unlockSourceId: 'food_10',
    sourceLabel: 'Earned from Table of Ten',
    lockedLabel: 'Save ten food memories.',
    rarity: 'rare',
    sizeScale: 1.05,
  },
  {
    id: 'prop_study_lamp',
    assetKey: 'prop_lantern',
    name: 'Study Lantern',
    description: 'A steady light for the ideas gathering in your Study.',
    category: 'memory',
    unlockKind: 'discovery',
    unlockSourceId: 'studio_10',
    sourceLabel: 'Earned from Study Shelf',
    lockedLabel: 'Save ten inspirations.',
    rarity: 'rare',
  },
  {
    id: 'prop_trail_marker',
    assetKey: 'decor_13',
    name: 'Trail Marker',
    description: 'A signpost for a long day in motion.',
    category: 'ritual',
    unlockKind: 'discovery',
    unlockSourceId: 'steps_20k',
    sourceLabel: 'Earned from a 20,000-step day',
    lockedLabel: 'Walk 20,000 steps in a day.',
    rarity: 'rare',
    sizeScale: 1.05,
  },
  {
    id: 'prop_trail_bridge',
    assetKey: 'artefact_trail_bridge',
    name: 'Trail Bridge',
    description: 'A crossing for a walking rhythm that lasted.',
    category: 'landmark',
    unlockKind: 'discovery',
    unlockSourceId: 'walk_streak_7',
    sourceLabel: 'Earned from Seven Days On',
    lockedLabel: 'Build a seven-day walking streak.',
    rarity: 'epic',
  },
  {
    id: 'prop_trophy_stone',
    assetKey: 'milestone_achievement',
    name: 'Trophy Stone',
    description: 'A marker for a goal you chose to remember.',
    category: 'landmark',
    unlockKind: 'discovery',
    unlockSourceId: 'goal_achieved',
    sourceLabel: 'Earned from Goal Achieved',
    lockedLabel: 'Mark an achievement.',
    rarity: 'rare',
    sizeScale: 1.1,
  },
  {
    id: 'prop_village_lantern',
    assetKey: 'artefact_memory_lantern',
    name: 'Village Lantern',
    description: 'A light for the first week your world held together.',
    category: 'landmark',
    unlockKind: 'discovery',
    unlockSourceId: 'first_week_village',
    sourceLabel: 'Earned from First Week Village',
    lockedLabel: 'Finish seven days in your world.',
    rarity: 'rare',
  },
  {
    id: 'prop_calm_flowers',
    assetKey: 'decor_6',
    name: 'Quiet Ferns',
    description: 'Soft growth for an emotional season that has become calm.',
    category: 'nature',
    unlockKind: 'observation',
    unlockSourceId: 'mood',
    sourceLabel: 'Noticed by the Observatory',
    lockedLabel: 'Let the Observatory notice a mood pattern.',
    rarity: 'common',
  },
  {
    id: 'prop_mood_sunbud',
    assetKey: 'decor_7',
    name: 'Sunbud',
    description: 'A bright bloom from a radiant day.',
    category: 'nature',
    unlockKind: 'mood',
    unlockSourceId: 'energized',
    sourceLabel: 'Earned from a Radiant mood',
    lockedLabel: 'Light the Mood Monument with a Radiant day.',
    rarity: 'common',
  },
  {
    id: 'prop_mood_breezegrass',
    assetKey: 'decor_5',
    name: 'Breezegrass',
    description: 'Soft grass from a light, open day.',
    category: 'nature',
    unlockKind: 'mood',
    unlockSourceId: 'good',
    sourceLabel: 'Earned from a Light mood',
    lockedLabel: 'Light the Mood Monument with a Light day.',
    rarity: 'common',
  },
  {
    id: 'prop_mood_moss_pebble',
    assetKey: 'decor_14',
    name: 'Moss Pebble',
    description: 'A grounded marker for a neutral day that still counted.',
    category: 'nature',
    unlockKind: 'mood',
    unlockSourceId: 'meh',
    sourceLabel: 'Earned from a Meh mood',
    lockedLabel: 'Light the Mood Monument with a Meh day.',
    rarity: 'common',
  },
  {
    id: 'prop_mood_rain_fern',
    assetKey: 'decor_6',
    name: 'Rain Fern',
    description: 'Gentle growth from a heavy day carried through.',
    category: 'nature',
    unlockKind: 'mood',
    unlockSourceId: 'drained',
    sourceLabel: 'Earned from a Heavy mood',
    lockedLabel: 'Light the Mood Monument with a Heavy day.',
    rarity: 'common',
  },
  {
    id: 'prop_mood_night_iris',
    assetKey: 'decor_15',
    name: 'Night Iris',
    description: 'A violet bloom from a stormy day survived.',
    category: 'nature',
    unlockKind: 'mood',
    unlockSourceId: 'stressed',
    sourceLabel: 'Earned from a Stormy mood',
    lockedLabel: 'Light the Mood Monument with a Stormy day.',
    rarity: 'common',
  },
  {
    id: 'prop_routine_table',
    assetKey: 'prop_coffee_table',
    name: 'Ritual Table',
    description: 'A small table for a routine becoming part of the map.',
    category: 'ritual',
    unlockKind: 'observation',
    unlockSourceId: 'routine',
    sourceLabel: 'Noticed by the Observatory',
    lockedLabel: 'Let the Observatory notice a routine.',
    rarity: 'common',
  },
  {
    id: 'prop_walking_signpost',
    assetKey: 'decor_13',
    name: 'Walking Signpost',
    description: 'A marker for movement that keeps coming back.',
    category: 'ritual',
    unlockKind: 'observation',
    unlockSourceId: 'movement',
    sourceLabel: 'Noticed by the Observatory',
    lockedLabel: 'Let the Observatory notice a walking rhythm.',
    rarity: 'common',
  },
];

export const WORLD_PROP_CATALOG: WorldPropDef[] = [...STARTER_WORLD_PROPS, ...EARNED_WORLD_PROPS];

export function isObservationKind(value: string | undefined): value is ObservationKind {
  return !!value && ['place', 'routine', 'mood', 'movement', 'food', 'studio', 'creature', 'week', 'life', 'reflection'].includes(value);
}
