import { createEditorialCompanionPack, type EditorialCompanionProfile } from '@/constants/editorial-companion-pack';

const profiles = {
  snuglet: {
    companionName: 'Snuglet', focusName: 'human caregiving', momentName: 'caregiving moment',
    kinds: [['routine', 'A daily care routine'], ['connection', 'Comfort or connection'], ['practical', 'Practical help or advocacy'], ['shared', 'Care shared with someone else'], ['limit', 'A limit, interruption, or no care moment']],
    effects: [['connection', 'Connection'], ['settled', 'Something became more settled'], ['relief', 'A little practical relief'], ['strain', 'Strain or depletion'], ['mixed', 'Mixed or unclear effects']],
    supports: [['help', 'Practical help'], ['routine', 'A workable routine'], ['communication', 'Clear communication'], ['resources', 'Enough time or resources'], ['boundary', 'A boundary around my capacity']],
    barriers: [['load', 'Too much to hold'], ['unpredictable', 'Unpredictable or changing needs'], ['support', 'Not enough support'], ['systems', 'Services, cost, or admin barriers'], ['capacity', 'My own health, energy, or limits']],
    details: [['need', 'A need that became clearer'], ['preference', 'The person’s preference or choice'], ['routine', 'A routine detail'], ['support', 'What support helped'], ['limit', 'A limit I reached']],
    fit: [['well', 'The care moment fitted'], ['shared', 'I shared or delegated care'], ['adapted', 'I adapted the plan'], ['boundary', 'I held a limit'], ['hard', 'It was hard or not enough']],
    next: [['prepare', 'Prepare one small thing'], ['ask', 'Ask for specific help'], ['connect', 'Choose a connection moment'], ['boundary', 'Protect one limit'], ['none', 'No extra task for now']],
    conditions: [['person', 'The other person’s needs and choices'], ['capacity', 'My capacity'], ['support', 'Available support'], ['resources', 'Time, money, or services'], ['uncertainty', 'Uncertainty or changing needs']],
    limits: [['asked', 'I asked for help'], ['delegated', 'I shared or delegated'], ['stopped', 'I stopped what could wait'], ['boundary', 'I held a boundary'], ['none', 'No boundary was available']],
    learning: [['needs', 'Which needs repeat'], ['communication', 'What supports communication'], ['load', 'What makes the load heavier'], ['support', 'Which support actually helps'], ['varies', 'Care needs vary']],
    keep: [['connection', 'One connecting moment'], ['routine', 'A workable routine'], ['support', 'Shared support'], ['boundary', 'A caregiver boundary'], ['honesty', 'An honest record of the strain']],
    adapt: [['smaller', 'Make the task smaller'], ['share', 'Share more of it'], ['different', 'Try another routine'], ['support', 'Seek practical support'], ['pause', 'Pause what can wait']],
  },
  waglet: {
    companionName: 'Waglet', focusName: 'life with a dog', momentName: 'dog-companionship moment',
    kinds: [['walk', 'A walk or outdoor moment'], ['play', 'Play or enrichment'], ['care', 'Food, grooming, rest, or care'], ['quiet', 'Quiet company'], ['none', 'No shared moment']],
    effects: [['connection', 'Connection'], ['enjoyment', 'Enjoyment'], ['settled', 'A settled moment'], ['learning', 'I learned a preference'], ['mixed', 'Mixed or no clear effect']],
    supports: [['choice', 'Following the dog’s choice'], ['routine', 'A familiar routine'], ['environment', 'A suitable environment'], ['support', 'Help from another person'], ['capacity', 'Enough human and dog capacity']],
    barriers: [['weather', 'Weather or environment'], ['health', 'Health, age, pain, or energy needs'], ['stress', 'Stress, fear, or overstimulation'], ['access', 'Route, space, or resource access'], ['time', 'Time or human capacity']],
    details: [['signal', 'A body-language signal'], ['preference', 'A preference or choice'], ['routine', 'A routine detail'], ['environment', 'An environmental detail'], ['change', 'A change worth following up']],
    fit: [['well', 'It suited both of us'], ['dog-stopped', 'The dog opted out or stopped'], ['adapted', 'I adapted the activity'], ['quiet', 'Quiet company fitted better'], ['none', 'It did not fit today']],
    next: [['choice', 'Offer a simple choice'], ['play', 'A brief play option'], ['quiet', 'Quiet company'], ['care', 'One routine care task'], ['support', 'Get appropriate help if needed']],
    conditions: [['dog', 'The dog’s health, age, or energy'], ['environment', 'Weather, noise, or route'], ['human', 'My capacity'], ['routine', 'Timing and routine'], ['support', 'Available help']],
    limits: [['stopped', 'I stopped when the dog asked'], ['changed', 'I changed the activity'], ['space', 'I gave the dog space'], ['help', 'I sought appropriate help'], ['none', 'No boundary stood out']],
    learning: [['signals', 'Which signals I recognise'], ['preferences', 'What the dog prefers'], ['routine', 'Which routines suit us'], ['environment', 'What affects comfort'], ['uncertain', 'I am not sure yet']],
    keep: [['choice', 'Respect for the dog’s choice'], ['connection', 'A connecting routine'], ['play', 'Enjoyable play'], ['comfort', 'Comfort and rest'], ['support', 'Appropriate care support']],
    adapt: [['shorter', 'Make it shorter'], ['quieter', 'Make it quieter'], ['different', 'Offer another activity'], ['help', 'Get qualified help'], ['pause', 'Pause it']],
  },
  whiskit: {
    companionName: 'Whiskit', focusName: 'life with a cat', momentName: 'cat-companionship moment',
    kinds: [['play', 'Play or hunting-style enrichment'], ['care', 'Food, grooming, rest, or care'], ['observe', 'Watching behaviour or preference'], ['quiet', 'Quiet company'], ['none', 'No shared moment']],
    effects: [['connection', 'Connection'], ['enjoyment', 'Enjoyment'], ['settled', 'A settled moment'], ['learning', 'I learned a preference'], ['mixed', 'Mixed or no clear effect']],
    supports: [['choice', 'Following the cat’s choice'], ['space', 'A suitable hiding or resting space'], ['routine', 'A familiar routine'], ['play', 'An appropriate play option'], ['capacity', 'Enough human and cat capacity']],
    barriers: [['health', 'Health, age, pain, or energy needs'], ['stress', 'Stress, fear, or overstimulation'], ['environment', 'Noise, change, or other animals'], ['resources', 'Space, time, or resource access'], ['uncertain', 'I did not understand the behaviour']],
    details: [['signal', 'A body-language signal'], ['preference', 'A preference or choice'], ['space', 'A resting or hiding place'], ['routine', 'A routine detail'], ['change', 'A change worth following up']],
    fit: [['well', 'It suited both of us'], ['cat-stopped', 'The cat opted out or left'], ['adapted', 'I adapted the activity'], ['quiet', 'Quiet company fitted better'], ['none', 'It did not fit today']],
    next: [['choice', 'Offer a simple choice'], ['play', 'A brief play option'], ['space', 'Refresh a safe resting space'], ['care', 'One routine care task'], ['support', 'Get appropriate help if needed']],
    conditions: [['cat', 'The cat’s health, age, or energy'], ['environment', 'Noise, change, or space'], ['human', 'My capacity'], ['routine', 'Timing and routine'], ['support', 'Available help']],
    limits: [['stopped', 'I stopped when the cat disengaged'], ['changed', 'I changed the activity'], ['space', 'I gave the cat space'], ['help', 'I sought appropriate help'], ['none', 'No boundary stood out']],
    learning: [['signals', 'Which signals I recognise'], ['preferences', 'What the cat prefers'], ['routine', 'Which routines suit us'], ['environment', 'What affects comfort'], ['uncertain', 'I am not sure yet']],
    keep: [['choice', 'Respect for the cat’s choice'], ['connection', 'A connecting routine'], ['play', 'Enjoyable play'], ['comfort', 'Comfort and safe space'], ['support', 'Appropriate care support']],
    adapt: [['shorter', 'Make it shorter'], ['quieter', 'Make it quieter'], ['different', 'Offer another activity'], ['help', 'Get qualified help'], ['pause', 'Pause it']],
  },
  mendle: {
    companionName: 'Mendle', focusName: 'everyday emotional support and repair', momentName: 'emotional-support moment',
    kinds: [['notice', 'Naming what was present'], ['reduce', 'Lowering a demand'], ['comfort', 'Comfort or grounding'], ['support', 'Contact with a trusted person or service'], ['none', 'No check-in or action']],
    effects: [['understood', 'I felt more understood'], ['space', 'A little more space'], ['human-support', 'More supported by a person or service'], ['unchanged', 'Nothing clearly changed'], ['harder', 'It felt harder']],
    supports: [['person', 'A trusted person'], ['grounding', 'A grounding activity'], ['permission', 'Permission to lower demands'], ['care', 'Professional or practical support'], ['time', 'Time for the feeling to move']],
    barriers: [['judgement', 'Self-judgement'], ['pressure', 'Pressure to recover quickly'], ['isolation', 'Not having safe support'], ['overwhelm', 'Feeling overwhelmed or unsafe'], ['needs', 'Practical or health needs']],
    details: [['feeling', 'A feeling or body signal'], ['need', 'A need'], ['pressure', 'A pressure I can lower'], ['support', 'A support that is available'], ['unclear', 'I cannot name it yet']],
    fit: [['helped', 'It helped a little'], ['neutral', 'It felt neutral'], ['stopped', 'I stopped because it did not help'], ['support', 'I needed human or professional support'], ['none', 'Nothing fitted today']],
    next: [['lower', 'Lower one demand'], ['ground', 'Choose one grounding action'], ['person', 'Contact someone trusted'], ['care', 'Use appropriate professional support'], ['none', 'No extra task now']],
    conditions: [['safety', 'Feeling safe enough'], ['person', 'Trusted human support'], ['body', 'Sleep, pain, or physical needs'], ['demands', 'Practical demands'], ['time', 'Time and change']],
    limits: [['stopped', 'I stopped an unhelpful exercise'], ['lowered', 'I lowered a demand'], ['reached', 'I reached for human support'], ['urgent', 'I needed urgent help'], ['none', 'No boundary was available']],
    learning: [['signals', 'Which signals I notice'], ['pressure', 'Which pressure can soften'], ['grounding', 'What grounds me'], ['support', 'When and how I seek support'], ['varies', 'What helps varies']],
    keep: [['honesty', 'Honest check-ins'], ['fairness', 'Fairer self-talk'], ['grounding', 'One grounding option'], ['support', 'A route to human support'], ['permission', 'Permission not to improve on schedule']],
    adapt: [['smaller', 'Make it smaller'], ['different', 'Try another support'], ['human', 'Bring in another person'], ['professional', 'Use professional support'], ['pause', 'Pause it']],
  },
} satisfies Record<string, EditorialCompanionProfile>;

export const BATCH_SIX_COMPANION_CONTENT = Object.fromEntries(
  Object.entries(profiles).map(([familyId, profile]) => [familyId, createEditorialCompanionPack(profile)]),
);
