import type { EditorialCompanionProfile, EditorialOptions } from '@/constants/editorial-companion-pack';
import { createSpecialistCompanionSystem, type SpecialistCompanionSystemConfig } from '@/constants/specialist-companion-system';

type Seed = Omit<EditorialCompanionProfile, 'fit' | 'limits'>;
const editorial = (seed: Seed): EditorialCompanionProfile => ({
  ...seed,
  fit: [['fit', 'It fitted well enough'], ['smaller', 'A smaller version fitted'], ['adapted', 'I adapted it'], ['other', 'I chose rest or something else'], ['none', 'It did not fit today']],
  limits: [['capacity', 'Energy, health, or capacity'], ['access', 'Cost, equipment, place, or access'], ['safety', 'Safety or environmental conditions'], ['boundary', 'A personal or social boundary'], ['none', 'No limit stood out']],
});

const configs = [
  {
    familyId: 'voltstep', journeyId: 'voltstep-cardio-rhythm', title: 'Sustainable sparks', subject: 'vigorous cardio and recovery',
    introduction: 'Explore short vigorous efforts only when they suit your body, health guidance, access, and energy. Adaptation, recovery, stopping, and choosing another intensity are part of the practice.',
    first: { prompt: 'What would you like vigorous cardio to give you?', helperText: 'Choose the experience, not a performance rank.', options: [['energy', 'A lively energy shift'], ['confidence', 'More confidence with intensity'], ['fitness', 'A repeatable cardio practice'], ['challenge', 'A chosen challenge'], ['curious', 'I am still finding out']] },
    second: { prompt: 'What most affects whether intensity fits?', helperText: 'Symptoms, health guidance, recovery, equipment, and motivation all matter. Never push through warning signs for a Focus.', options: [['body', 'Health, symptoms, or body response'], ['recovery', 'Recovery and sleep'], ['access', 'Space, equipment, or access'], ['pace', 'Starting too hard'], ['interest', 'Whether I want intensity today']] },
    directions: [
      { id: 'rhythm', label: 'Build a sustainable rhythm', goalTitle: 'Build a sustainable vigorous-cardio rhythm', quickGoalSuffixes: ['choose-session', 'short-interval'] },
      { id: 'pace', label: 'Learn my pacing', goalTitle: 'Learn how to pace vigorous efforts', quickGoalSuffixes: ['notice-effort', 'choose-stop'] },
      { id: 'recovery', label: 'Protect recovery', goalTitle: 'Pair vigorous effort with enough recovery', quickGoalSuffixes: ['plan-recovery', 'recovery-note'] },
      { id: 'adapt', label: 'Find suitable alternatives', goalTitle: 'Find cardio options that fit my body and access', quickGoalSuffixes: ['adapt-option', 'check-guidance'] },
    ],
    quickGoals: [
      { suffix: 'choose-session', title: 'Choose whether a vigorous session suits me today' }, { suffix: 'short-interval', title: 'Try one short suitable interval and stop if needed' },
      { suffix: 'notice-effort', title: 'Notice one breathing, effort, or body-response detail' }, { suffix: 'choose-stop', title: 'Choose a stopping cue before I begin' },
      { suffix: 'plan-recovery', title: 'Make room for one recovery period' }, { suffix: 'recovery-note', title: 'Note how recovery affected the next effort' },
      { suffix: 'adapt-option', title: 'Choose one lower-impact, seated, or adapted cardio option' }, { suffix: 'check-guidance', title: 'Follow relevant health guidance before adding intensity' },
    ],
    editorial: editorial({
      companionName: 'Voltstep', focusName: 'vigorous cardio', momentName: 'cardio moment',
      kinds: [['interval', 'A short interval'], ['session', 'A longer session'], ['adapted', 'An adapted or lower-impact effort'], ['recovery', 'Recovery instead of intensity'], ['none', 'No cardio moment']],
      effects: [['energised', 'More energised'], ['confident', 'More confident'], ['neutral', 'No clear change'], ['tired', 'Tired or depleted'], ['symptoms', 'Pain, symptoms, or concern']],
      supports: [['warmup', 'A gradual start'], ['pace', 'A suitable pace'], ['recovery', 'Enough recovery'], ['access', 'Suitable space or equipment'], ['guidance', 'Relevant qualified guidance']],
      barriers: [['symptoms', 'Pain, symptoms, or health needs'], ['recovery', 'Not enough recovery'], ['pace', 'The pace was too demanding'], ['access', 'Space, equipment, or access'], ['interest', 'I did not want intensity']],
      details: [['breath', 'Breathing'], ['effort', 'Effort level'], ['interval', 'An interval or round'], ['recovery', 'Recovery response'], ['stop', 'A reason to stop or adapt']],
      next: [['brief', 'A brief suitable effort'], ['pace', 'A pacing experiment'], ['recover', 'Recovery'], ['adapt', 'An adapted option'], ['none', 'No intensity task now']],
      conditions: [['health', 'Health and symptoms'], ['recovery', 'Sleep and recovery'], ['environment', 'Space and environment'], ['time', 'Time and capacity'], ['support', 'Guidance or support']],
      learning: [['pace', 'Which pace suits me'], ['duration', 'Which duration is manageable'], ['recovery', 'How much recovery I need'], ['warning', 'Which signals mean stop'], ['varies', 'It varies']],
      keep: [['choice', 'Choice about intensity'], ['pace', 'A sustainable pace'], ['recovery', 'Enough recovery'], ['adaptation', 'Useful adaptations'], ['safety', 'Stopping when needed']],
      adapt: [['lower', 'Lower the intensity'], ['shorter', 'Make it shorter'], ['seated', 'Use a seated or supported option'], ['guidance', 'Get appropriate guidance'], ['pause', 'Pause the Focus']],
    }),
  },
  {
    familyId: 'pulsepounce', journeyId: 'pulsepounce-playful-agility', title: 'Playful coordination', subject: 'agility and playful movement',
    introduction: 'Explore coordination, rhythm, and dynamic movement through playful, seated, supported, low-impact, or standing options. Speed and conventional technique are not the measure.',
    first: { prompt: 'What would make agility practice worthwhile?', helperText: 'Choose what feels enjoyable or useful in your body.', options: [['play', 'Play and enjoyment'], ['coordination', 'Coordination'], ['confidence', 'Movement confidence'], ['rhythm', 'Rhythm or timing'], ['variety', 'A change from usual movement']] },
    second: { prompt: 'What most shapes the movement that fits?', helperText: 'Space, mobility, balance, pain, energy, equipment, and support can all change the form.', options: [['body', 'Mobility, balance, pain, or energy'], ['space', 'Available space'], ['access', 'Equipment or support'], ['pressure', 'Pressure to be quick or precise'], ['ideas', 'Not knowing what to try']] },
    directions: [
      { id: 'play', label: 'Make movement playful', goalTitle: 'Build a playful movement rhythm', quickGoalSuffixes: ['choose-play', 'music-move'] },
      { id: 'coordination', label: 'Practise one pattern', goalTitle: 'Develop one coordination pattern', quickGoalSuffixes: ['one-pattern', 'repeat-pattern'] },
      { id: 'adapt', label: 'Find accessible movement', goalTitle: 'Find agility options that fit my access needs', quickGoalSuffixes: ['adapt-pattern', 'clear-space'] },
      { id: 'confidence', label: 'Build confidence gently', goalTitle: 'Build movement confidence without speed pressure', quickGoalSuffixes: ['slow-first', 'keep-success'] },
    ],
    quickGoals: [
      { suffix: 'choose-play', title: 'Choose one movement that feels playful' }, { suffix: 'music-move', title: 'Move with one song or rhythm in a suitable way' },
      { suffix: 'one-pattern', title: 'Try one short coordination pattern' }, { suffix: 'repeat-pattern', title: 'Repeat one pattern only while it still feels useful' },
      { suffix: 'adapt-pattern', title: 'Adapt one pattern for seated, supported, or lower-impact movement' }, { suffix: 'clear-space', title: 'Prepare one safe movement space' },
      { suffix: 'slow-first', title: 'Try one pattern slowly before choosing whether to continue' }, { suffix: 'keep-success', title: 'Keep one movement detail that felt more confident' },
    ],
    editorial: editorial({
      companionName: 'Pulsepounce', focusName: 'playful agility', momentName: 'coordination moment',
      kinds: [['feet', 'A footwork pattern'], ['hands', 'A hand or upper-body pattern'], ['rhythm', 'Movement with rhythm'], ['adapted', 'Seated, supported, or adapted play'], ['none', 'No movement moment']],
      effects: [['fun', 'Fun'], ['focused', 'More focused'], ['confident', 'More confident'], ['frustrated', 'Frustrated or pressured'], ['mixed', 'Mixed or no clear effect']],
      supports: [['space', 'A safe clear space'], ['slow', 'Starting slowly'], ['music', 'Music or a cue'], ['adaptation', 'A useful adaptation'], ['company', 'Support or company']],
      barriers: [['body', 'Pain, balance, mobility, or energy'], ['space', 'Not enough suitable space'], ['pressure', 'Speed or accuracy pressure'], ['ideas', 'Not knowing a pattern'], ['interest', 'It did not appeal today']],
      details: [['timing', 'Timing'], ['sequence', 'The sequence'], ['balance', 'Balance or support'], ['rhythm', 'Rhythm'], ['adaptation', 'An adaptation']],
      next: [['play', 'A playful pattern'], ['slow', 'A slow repeat'], ['adapt', 'An adapted option'], ['rest', 'Rest or recovery'], ['none', 'No movement task now']],
      conditions: [['body', 'Body and energy'], ['space', 'Space'], ['support', 'Support or equipment'], ['mood', 'Mood and interest'], ['time', 'Time']],
      learning: [['pattern', 'Which patterns suit me'], ['pace', 'Which pace feels useful'], ['cue', 'Which cues help'], ['adapt', 'Which adaptations work'], ['varies', 'It varies']],
      keep: [['play', 'Playfulness'], ['pattern', 'One useful pattern'], ['confidence', 'Confidence without comparison'], ['adapt', 'An accessible adaptation'], ['stop', 'Permission to stop']],
      adapt: [['slower', 'Make it slower'], ['simpler', 'Use fewer steps'], ['seated', 'Try it seated or supported'], ['space', 'Use a different space'], ['pause', 'Pause the Focus']],
    }),
  },
  {
    familyId: 'museling', journeyId: 'museling-creative-practice', title: 'A creative thread', subject: 'hands-on creative practice',
    introduction: 'Protect a small relationship with making. Starting, experimenting, continuing, abandoning, resting, and making privately can all be meaningful.',
    first: { prompt: 'What would you like creative practice to give you?', helperText: 'Choose the experience you want, not an output target.', options: [['expression', 'A way to express something'], ['play', 'Play and experimentation'], ['skill', 'Learning a craft'], ['project', 'A thread to continue'], ['quiet', 'Absorbed or quiet time']] },
    second: { prompt: 'What most often interrupts making?', helperText: 'Capacity and conditions matter more than forcing inspiration.', options: [['time', 'Time or energy'], ['perfection', 'Perfection or comparison'], ['start', 'Not knowing how to start'], ['materials', 'Materials, space, or cost'], ['interest', 'The idea no longer interests me']] },
    directions: [
      { id: 'show-up', label: 'Make small creative time', goalTitle: 'Build a small creative rhythm', quickGoalSuffixes: ['ten-minutes', 'prepare-material'] },
      { id: 'experiment', label: 'Experiment without outcome pressure', goalTitle: 'Use creative experiments to learn', quickGoalSuffixes: ['one-experiment', 'keep-learning'] },
      { id: 'continue', label: 'Continue one thread', goalTitle: 'Continue one creative thread at a workable pace', quickGoalSuffixes: ['choose-next', 'leave-return'] },
      { id: 'access', label: 'Reduce barriers to making', goalTitle: 'Make creative practice easier to access', quickGoalSuffixes: ['use-available', 'smaller-version'] },
    ],
    quickGoals: [
      { suffix: 'ten-minutes', title: 'Make for up to ten minutes' }, { suffix: 'prepare-material', title: 'Prepare one material or tool for an easier return' },
      { suffix: 'one-experiment', title: 'Try one small creative experiment' }, { suffix: 'keep-learning', title: 'Keep one thing the experiment taught me' },
      { suffix: 'choose-next', title: 'Choose one concrete next change to a piece' }, { suffix: 'leave-return', title: 'Leave one clear return point before stopping' },
      { suffix: 'use-available', title: 'Make with something already available' }, { suffix: 'smaller-version', title: 'Choose the smallest useful version of an idea' },
    ],
    editorial: editorial({
      companionName: 'Museling', focusName: 'creative practice', momentName: 'making moment',
      kinds: [['started', 'Started something'], ['continued', 'Continued a piece'], ['experimented', 'Experimented'], ['prepared', 'Prepared or gathered'], ['none', 'No making moment']],
      effects: [['absorbed', 'Absorption'], ['expressive', 'Expression'], ['playful', 'Playfulness'], ['frustrated', 'Frustration'], ['mixed', 'Mixed or no clear effect']],
      supports: [['time', 'Protected time'], ['small', 'A small scope'], ['materials', 'Available materials'], ['permission', 'Permission to experiment'], ['return', 'A clear return point']],
      barriers: [['capacity', 'Time or energy'], ['perfection', 'Perfection or comparison'], ['materials', 'Materials, space, or cost'], ['clarity', 'An unclear next step'], ['interest', 'The thread lost interest']],
      details: [['material', 'A material'], ['tool', 'A tool'], ['decision', 'A decision'], ['surprise', 'A surprise'], ['change', 'A change in the piece']],
      next: [['tiny', 'A tiny making session'], ['experiment', 'An experiment'], ['continue', 'Continue one thread'], ['prepare', 'Prepare for later'], ['none', 'No creative task now']],
      conditions: [['capacity', 'Time and energy'], ['space', 'Space'], ['materials', 'Materials'], ['mood', 'Mood and attention'], ['privacy', 'Privacy or company']],
      learning: [['process', 'Which process suits me'], ['scope', 'Which scope is manageable'], ['material', 'Which materials interest me'], ['thread', 'Which thread wants more time'], ['varies', 'It varies']],
      keep: [['play', 'Play'], ['process', 'A useful process'], ['thread', 'One continuing thread'], ['learning', 'Learning from imperfect work'], ['privacy', 'The right to make privately']],
      adapt: [['smaller', 'Make it smaller'], ['different', 'Change material or method'], ['prepare', 'Prepare without making'], ['drop', 'Let the idea go'], ['pause', 'Pause the Focus']],
    }),
  },
  {
    familyId: 'pixooka', journeyId: 'pixooka-intentional-play', title: 'Intentional play', subject: 'video-game play',
    introduction: 'Explore games through enjoyment, mastery, story, connection, and chosen stopping points. Play does not need to be productive, social, difficult, or brief to count.',
    first: { prompt: 'What do you most want from games right now?', helperText: 'Choose what you actually value in play.', options: [['relax', 'Relaxation or escape'], ['story', 'Story and discovery'], ['skill', 'Challenge or mastery'], ['social', 'Playing with others'], ['variety', 'Trying different kinds of play']] },
    second: { prompt: 'When does play stop fitting well?', helperText: 'Notice the pattern without treating screen time as a moral score.', options: [['time', 'I lose track of chosen time'], ['energy', 'It leaves me depleted'], ['frustration', 'Challenge becomes frustration'], ['social', 'Social play stops feeling good'], ['unclear', 'There is no clear problem']] },
    directions: [
      { id: 'chosen', label: 'Make play feel chosen', goalTitle: 'Build a more intentional gaming rhythm', quickGoalSuffixes: ['choose-purpose', 'choose-stop'] },
      { id: 'story', label: 'Follow a game or story', goalTitle: 'Give one game the attention I want', quickGoalSuffixes: ['return-game', 'keep-moment'] },
      { id: 'skill', label: 'Learn without pressure', goalTitle: 'Develop one game skill without rank pressure', quickGoalSuffixes: ['one-mechanic', 'notice-learning'] },
      { id: 'social', label: 'Shape social play', goalTitle: 'Create social play that respects my boundaries', quickGoalSuffixes: ['invite-play', 'social-boundary'] },
    ],
    quickGoals: [
      { suffix: 'choose-purpose', title: 'Choose what I want from one play session' }, { suffix: 'choose-stop', title: 'Choose a stopping or check-in point before playing' },
      { suffix: 'return-game', title: 'Return to one game I genuinely want to play' }, { suffix: 'keep-moment', title: 'Keep one decision, discovery, or story moment' },
      { suffix: 'one-mechanic', title: 'Explore one mechanic, route, or strategy' }, { suffix: 'notice-learning', title: 'Notice one thing that became clearer' },
      { suffix: 'invite-play', title: 'Offer one low-pressure play invitation' }, { suffix: 'social-boundary', title: 'Choose one boundary for social play' },
    ],
    editorial: editorial({
      companionName: 'Pixooka', focusName: 'intentional gaming', momentName: 'game moment',
      kinds: [['story', 'Story or discovery'], ['challenge', 'Challenge or mastery'], ['social', 'Social play'], ['rest', 'Relaxed familiar play'], ['none', 'No game moment']],
      effects: [['enjoyed', 'Enjoyment'], ['absorbed', 'Absorption'], ['connected', 'Connection'], ['frustrated', 'Frustration or depletion'], ['mixed', 'Mixed or no clear effect']],
      supports: [['choice', 'A game I chose'], ['time', 'Enough suitable time'], ['difficulty', 'A fitting challenge'], ['people', 'The right people'], ['stop', 'A chosen stopping point']],
      barriers: [['time', 'Time drift'], ['energy', 'Fatigue or overstimulation'], ['frustration', 'Frustration or difficulty'], ['social', 'Social pressure or conflict'], ['access', 'Cost, hardware, or access']],
      details: [['decision', 'A decision'], ['mechanic', 'A mechanic'], ['story', 'A story beat'], ['social', 'A shared moment'], ['stop', 'How the session ended']],
      next: [['familiar', 'A familiar game'], ['story', 'Continue a story'], ['skill', 'Explore one skill'], ['social', 'A social session'], ['none', 'No play task now']],
      conditions: [['time', 'Available time'], ['energy', 'Energy and attention'], ['game', 'The game and difficulty'], ['people', 'Other players'], ['access', 'Hardware and access']],
      learning: [['play', 'Which play suits me'], ['challenge', 'Which challenge level fits'], ['social', 'Which social settings feel good'], ['stop', 'Which stopping cues work'], ['varies', 'It varies']],
      keep: [['joy', 'Enjoyment'], ['story', 'A meaningful game thread'], ['skill', 'Learning without rank pressure'], ['connection', 'Good social play'], ['choice', 'Choice about when to stop']],
      adapt: [['easier', 'Change difficulty or mode'], ['shorter', 'Use a shorter check-in window'], ['solo', 'Choose solo play'], ['different', 'Choose another activity'], ['pause', 'Pause the Focus']],
    }),
  },
  {
    familyId: 'glimmuse', journeyId: 'glimmuse-art-encounters', title: 'A way of looking', subject: 'visual-art encounters',
    introduction: 'Build a personal relationship with visual art through looking, context, and honest response. Galleries, public art, books, reproductions, and accessible digital collections can all count.',
    first: { prompt: 'What would you like art encounters to give you?', helperText: 'There is no requirement to know art language or admire the work.', options: [['attention', 'A reason to look closely'], ['feeling', 'An emotional or personal response'], ['ideas', 'New visual ideas'], ['context', 'Artists and context'], ['taste', 'A clearer sense of my taste']] },
    second: { prompt: 'What most affects whether art feels accessible?', helperText: 'Travel, cost, sensory access, confidence, and available time all count.', options: [['place', 'Travel, venue, or cost'], ['sensory', 'Sensory or physical access'], ['confidence', 'Feeling I need expertise'], ['time', 'Time and attention'], ['interest', 'Finding work that interests me']] },
    directions: [
      { id: 'look', label: 'Look closely', goalTitle: 'Build a close-looking practice', quickGoalSuffixes: ['one-artwork', 'one-detail'] },
      { id: 'taste', label: 'Understand my response', goalTitle: 'Learn what draws or repels me in visual art', quickGoalSuffixes: ['honest-response', 'compare-works'] },
      { id: 'context', label: 'Learn context', goalTitle: 'Learn context that deepens visual-art encounters', quickGoalSuffixes: ['learn-artist', 'check-source'] },
      { id: 'access', label: 'Find accessible encounters', goalTitle: 'Find accessible ways to encounter visual art', quickGoalSuffixes: ['digital-art', 'nearby-art'] },
    ],
    quickGoals: [
      { suffix: 'one-artwork', title: 'Spend a little time with one artwork' }, { suffix: 'one-detail', title: 'Keep one colour, form, material, or scale detail' },
      { suffix: 'honest-response', title: 'Name one honest response without needing to like the work' }, { suffix: 'compare-works', title: 'Compare two works through one visible detail' },
      { suffix: 'learn-artist', title: 'Learn one reliable detail about an artist or work' }, { suffix: 'check-source', title: 'Check the source of one art-context claim' },
      { suffix: 'digital-art', title: 'Open one accessible digital art collection or reproduction' }, { suffix: 'nearby-art', title: 'Notice one artwork, design, or public image already nearby' },
    ],
    editorial: editorial({
      companionName: 'Glimmuse', focusName: 'visual-art encounters', momentName: 'art encounter',
      kinds: [['gallery', 'A gallery or exhibition'], ['public', 'Public or nearby art'], ['book', 'A book or reproduction'], ['digital', 'A digital collection'], ['none', 'No art encounter']],
      effects: [['held', 'It held my attention'], ['felt', 'It brought up a feeling'], ['question', 'It raised a question'], ['disliked', 'I disliked or resisted it'], ['mixed', 'Mixed or no clear response']],
      supports: [['time', 'Time to look'], ['access', 'Accessible presentation'], ['context', 'Useful context'], ['company', 'Company or conversation'], ['permission', 'Permission not to like it']],
      barriers: [['access', 'Travel, cost, or venue access'], ['sensory', 'Sensory or physical access'], ['expertise', 'Expertise pressure'], ['attention', 'Limited time or attention'], ['interest', 'The work did not interest me']],
      details: [['colour', 'Colour or light'], ['form', 'Shape or composition'], ['material', 'Material or technique'], ['scale', 'Scale or space'], ['subject', 'Subject or idea']],
      next: [['return', 'Return to one work'], ['different', 'Try a different kind of work'], ['context', 'Learn context'], ['accessible', 'Use an accessible collection'], ['none', 'No art task now']],
      conditions: [['access', 'Access and cost'], ['setting', 'The setting'], ['context', 'Available context'], ['attention', 'Attention and time'], ['company', 'Company or solitude']],
      learning: [['visual', 'Which visual qualities draw me'], ['response', 'Which responses repeat'], ['context', 'Which context helps'], ['setting', 'Which settings suit me'], ['varies', 'My taste varies']],
      keep: [['detail', 'One visual detail'], ['response', 'An honest response'], ['question', 'A question'], ['context', 'Reliable context'], ['permission', 'Permission not to admire it']],
      adapt: [['digital', 'Use a digital or printed work'], ['shorter', 'Look for less time'], ['different', 'Choose another kind of art'], ['support', 'Use access support'], ['pause', 'Pause the Focus']],
    }),
  },
  {
    familyId: 'shellio', journeyId: 'shellio-water-connection', version: 4, title: 'Your way into water', subject: 'swimming, beach, and water connection',
    introduction: 'Build a relationship with water through swimming, beaches and shores, or simply being near it. A pool, a lifeguarded beach, an accessible water view, and choosing not to enter can all count. Shellio never asks you to swim beyond your ability or ignore local safety guidance.',
    first: { prompt: 'What would you like water to bring into your life?', helperText: 'Choose the relationship you want—not what you think a swimmer or beachgoer should be able to do.', options: [['rhythm', 'A more regular swimming rhythm'], ['confidence', 'More confidence in or around water'], ['movement', 'Enjoyable movement or fitness'], ['shore', 'More beach or shoreline time'], ['connection', 'Connection without needing to swim']] },
    second: { prompt: 'What most shapes the water experiences that fit you?', helperText: 'Swimming ability, health, access, cost, supervision, weather, water quality, and travel can all change the safest useful next step.', options: [['ability', 'Swimming ability or water confidence'], ['body', 'Health, mobility, energy, or recovery'], ['access', 'Pool, beach, equipment, cost, or transport'], ['conditions', 'Supervision, weather, water quality, or conditions'], ['time', 'Time, company, or caring duties']] },
    directions: [
      { id: 'swim-rhythm', label: 'Build a swimming rhythm', goalTitle: 'Build a safe swimming rhythm that fits my life', quickGoalSuffixes: ['choose-swim', 'plan-return'] },
      { id: 'confidence', label: 'Grow water confidence', goalTitle: 'Grow my confidence in or around water safely', quickGoalSuffixes: ['lesson-option', 'confidence-step'] },
      { id: 'movement', label: 'Swim for enjoyable movement', goalTitle: 'Use swimming as enjoyable movement without performance pressure', quickGoalSuffixes: ['movement-intention', 'body-check'] },
      { id: 'shore', label: 'Make room for beach or shore time', goalTitle: 'Spend meaningful time at beaches or shores', quickGoalSuffixes: ['shore-plan', 'shore-moment'] },
      { id: 'connection', label: 'Connect without entering the water', goalTitle: 'Build a water connection that does not require swimming', quickGoalSuffixes: ['safe-view', 'water-detail'] },
    ],
    quickGoals: [
      { suffix: 'choose-swim', title: 'Choose one swim that suits my ability and capacity' }, { suffix: 'plan-return', title: 'Check one pool timetable or plan one safe return swim' },
      { suffix: 'lesson-option', title: 'Find one qualified lesson or supported swim option' }, { suffix: 'confidence-step', title: 'Choose one supervised water-confidence step that feels manageable' },
      { suffix: 'movement-intention', title: 'Choose a comfortable purpose or pace for one swim' }, { suffix: 'body-check', title: 'Notice how my body and energy respond during and after a swim' },
      { suffix: 'shore-plan', title: 'Plan one accessible beach or shoreline visit' }, { suffix: 'shore-moment', title: 'Take one unhurried moment at a beach or shore' },
      { suffix: 'safe-view', title: 'Find one safe water view that does not require entering' }, { suffix: 'water-detail', title: 'Notice one sound, reflection, tide, colour, or movement detail' },
    ],
    editorial: editorial({
      companionName: 'Shellio', focusName: 'swimming and water connection', momentName: 'water moment',
      kinds: [['pool', 'A pool swim'], ['open-water', 'A supervised or lifeguarded open-water swim'], ['shore', 'A beach or shoreline visit'], ['view', 'Time near water without entering'], ['none', 'No water moment']],
      effects: [['movement', 'Enjoyable movement or energy'], ['confidence', 'More confidence or familiarity'], ['connection', 'Connection to water or place'], ['uncomfortable', 'Discomfort, fear, fatigue, or concern'], ['mixed', 'Mixed or no clear effect']],
      supports: [['supervision', 'A lifeguarded, supervised, or otherwise suitable setting'], ['ability', 'A depth and activity suited to my ability'], ['access', 'Affordable, accessible facilities or equipment'], ['conditions', 'Suitable weather, water quality, and local guidance'], ['company', 'The right company, lesson, or support']],
      barriers: [['ability', 'Swimming ability, confidence, or fear'], ['body', 'Health, mobility, energy, or recovery'], ['access', 'Pool, beach, equipment, cost, or transport'], ['conditions', 'Supervision, weather, water quality, or conditions'], ['time', 'Time, company, or caring duties']],
      details: [['body', 'How my body or energy responded'], ['breath', 'Breathing, pace, or a swimming movement'], ['confidence', 'A comfort or confidence cue'], ['shore', 'Sand, tide, wildlife, or the waterline'], ['sense', 'Sound, light, temperature, or reflection']],
      next: [['swim', 'A suitable pool or supported swim'], ['confidence', 'A lesson or supervised confidence step'], ['shore', 'A beach or shoreline visit'], ['view', 'A water view without entering'], ['none', 'No water task now']],
      conditions: [['ability', 'Ability and confidence'], ['body', 'Health, energy, and recovery'], ['setting', 'Supervision and setting'], ['environment', 'Weather, water quality, and local advice'], ['access', 'Cost, equipment, travel, and access']],
      learning: [['swim-fit', 'Which kind of swim suits me'], ['pace', 'Which pace or duration feels workable'], ['confidence', 'What supports water confidence'], ['place', 'Which beach or water place draws me back'], ['limits', 'When not entering or stopping is right']],
      keep: [['rhythm', 'A sustainable swimming rhythm'], ['confidence', 'One confidence-building step'], ['movement', 'Enjoyable movement without comparison'], ['shore', 'A meaningful beach or shore'], ['choice', 'The choice to swim, stay ashore, adapt, or stop']],
      adapt: [['pool', 'Choose a pool or lifeguarded setting'], ['lesson', 'Use a qualified lesson or support'], ['shallower', 'Stay in a suitable depth or out of the water'], ['view', 'Choose a shore or water view instead'], ['pause', 'Pause the Focus']],
    }),
  },
] as const satisfies readonly SpecialistCompanionSystemConfig[];

export const BATCH_EIGHT_SPECIALIST_SYSTEMS = configs.map(createSpecialistCompanionSystem);
export const BATCH_EIGHT_COMPANION_CONTENT = Object.fromEntries(BATCH_EIGHT_SPECIALIST_SYSTEMS.map((system) => [system.familyId, system.content]));
export const BATCH_EIGHT_SPECIALIST_JOURNEY_IDS = new Map(BATCH_EIGHT_SPECIALIST_SYSTEMS.map((system) => [system.familyId, system.journeyId]));
