// Generated by scripts/generate-katchimera-idle.py. Do not edit by hand.
import type { ImageSourcePropType } from 'react-native';

import type { HomeVisualKey } from '@/types/home';

const CREATURE_IDLE_ANIMATION_SOURCES: Partial<Record<HomeVisualKey, ImageSourcePropType>> = {
  'mossprout': require('../assets/images/katchimeras/animations/mossprout-idle.webp'),
  'steppling': require('../assets/images/katchimeras/animations/steppling-idle.webp'),
};

export function resolveCreatureIdleAnimationSource(
  visualKey: HomeVisualKey,
): ImageSourcePropType | null {
  return CREATURE_IDLE_ANIMATION_SOURCES[visualKey] ?? null;
}
