// Generated by scripts/generate-hatchling-lod.py. Do not hand edit.
import type { ImageSourcePropType } from 'react-native';
import type { HomeVisualKey } from '@/types/home';

export type CreatureHatchlingLod = 'full' | 'medium' | 'thumb';

export const CREATURE_HATCHLING_SOURCES: Record<CreatureHatchlingLod, Partial<Record<HomeVisualKey, ImageSourcePropType>>> = {
  full: {
    feastle: require('../assets/images/katchimeras/hatchlings/feastle.png'),
    flickerbun: require('../assets/images/katchimeras/hatchlings/flickerbun.png'),
    mossprout: require('../assets/images/katchimeras/hatchlings/base-hatchling-v2.png'),
  },
  medium: {
    feastle: require('../assets/images/katchimeras/hatchlings_lod/feastle_512.webp'),
    flickerbun: require('../assets/images/katchimeras/hatchlings_lod/flickerbun_512.webp'),
    mossprout: require('../assets/images/katchimeras/hatchlings_lod/mossprout_512.webp'),
  },
  thumb: {
    feastle: require('../assets/images/katchimeras/hatchlings_lod/feastle_256.webp'),
    flickerbun: require('../assets/images/katchimeras/hatchlings_lod/flickerbun_256.webp'),
    mossprout: require('../assets/images/katchimeras/hatchlings_lod/mossprout_256.webp'),
  },
};
