// Generated by scripts/generate-hatchling-lod.py. Do not hand edit.
import type { ImageSourcePropType } from 'react-native';
import type { HomeVisualKey } from '@/types/home';

export type CreatureHatchlingLod = 'full' | 'medium' | 'thumb';
export type CreatureHatchlingAlphaBounds = { left: number; top: number; right: number; bottom: number };

export const CREATURE_HATCHLING_SOURCES: Record<CreatureHatchlingLod, Partial<Record<HomeVisualKey, ImageSourcePropType>>> = {
  full: {
    bedrotte: require('../assets/images/katchimeras/hatchlings/bedrotte.png'),
    cheerlet: require('../assets/images/katchimeras/hatchlings/cheerlet.png'),
    feastle: require('../assets/images/katchimeras/hatchlings/feastle.png'),
    flickerbun: require('../assets/images/katchimeras/hatchlings/flickerbun.png'),
    gatherglow: require('../assets/images/katchimeras/hatchlings/gatherglow.png'),
    mossprout: require('../assets/images/katchimeras/hatchlings/base-hatchling-v2.png'),
    pagelet: require('../assets/images/katchimeras/hatchlings/pagelet.png'),
    relicoon: require('../assets/images/katchimeras/hatchlings/relicoon.png'),
    shellio: require('../assets/images/katchimeras/hatchlings/shellio.png'),
    skylo: require('../assets/images/katchimeras/hatchlings/skylo.png'),
    steppling: require('../assets/images/katchimeras/hatchlings/steppling.png'),
    tasklet: require('../assets/images/katchimeras/hatchlings/tasklet.png'),
    vesperitt: require('../assets/images/katchimeras/hatchlings/vesperitt.png'),
  },
  medium: {
    bedrotte: require('../assets/images/katchimeras/hatchlings_lod/bedrotte_512.webp'),
    cheerlet: require('../assets/images/katchimeras/hatchlings_lod/cheerlet_512.webp'),
    feastle: require('../assets/images/katchimeras/hatchlings_lod/feastle_512.webp'),
    flickerbun: require('../assets/images/katchimeras/hatchlings_lod/flickerbun_512.webp'),
    gatherglow: require('../assets/images/katchimeras/hatchlings_lod/gatherglow_512.webp'),
    mossprout: require('../assets/images/katchimeras/hatchlings_lod/mossprout_512.webp'),
    pagelet: require('../assets/images/katchimeras/hatchlings_lod/pagelet_512.webp'),
    relicoon: require('../assets/images/katchimeras/hatchlings_lod/relicoon_512.webp'),
    shellio: require('../assets/images/katchimeras/hatchlings_lod/shellio_512.webp'),
    skylo: require('../assets/images/katchimeras/hatchlings_lod/skylo_512.webp'),
    steppling: require('../assets/images/katchimeras/hatchlings_lod/steppling_512.webp'),
    tasklet: require('../assets/images/katchimeras/hatchlings_lod/tasklet_512.webp'),
    vesperitt: require('../assets/images/katchimeras/hatchlings_lod/vesperitt_512.webp'),
  },
  thumb: {
    bedrotte: require('../assets/images/katchimeras/hatchlings_lod/bedrotte_256.webp'),
    cheerlet: require('../assets/images/katchimeras/hatchlings_lod/cheerlet_256.webp'),
    feastle: require('../assets/images/katchimeras/hatchlings_lod/feastle_256.webp'),
    flickerbun: require('../assets/images/katchimeras/hatchlings_lod/flickerbun_256.webp'),
    gatherglow: require('../assets/images/katchimeras/hatchlings_lod/gatherglow_256.webp'),
    mossprout: require('../assets/images/katchimeras/hatchlings_lod/mossprout_256.webp'),
    pagelet: require('../assets/images/katchimeras/hatchlings_lod/pagelet_256.webp'),
    relicoon: require('../assets/images/katchimeras/hatchlings_lod/relicoon_256.webp'),
    shellio: require('../assets/images/katchimeras/hatchlings_lod/shellio_256.webp'),
    skylo: require('../assets/images/katchimeras/hatchlings_lod/skylo_256.webp'),
    steppling: require('../assets/images/katchimeras/hatchlings_lod/steppling_256.webp'),
    tasklet: require('../assets/images/katchimeras/hatchlings_lod/tasklet_256.webp'),
    vesperitt: require('../assets/images/katchimeras/hatchlings_lod/vesperitt_256.webp'),
  },
};

export const CREATURE_HATCHLING_ALPHA_THRESHOLD = 16;
export const CREATURE_HATCHLING_ALPHA_BOUNDS: Partial<Record<HomeVisualKey, CreatureHatchlingAlphaBounds>> = {
  bedrotte: { left: 0.210938, top: 0.072266, right: 0.793945, bottom: 0.948242 },
  cheerlet: { left: 0.210938, top: 0.064453, right: 0.794922, bottom: 0.900391 },
  feastle: { left: 0.177734, top: 0.140625, right: 0.829102, bottom: 0.894531 },
  flickerbun: { left: 0.261719, top: 0.116211, right: 0.737305, bottom: 0.872070 },
  gatherglow: { left: 0.271484, top: 0.100586, right: 0.736328, bottom: 0.888672 },
  mossprout: { left: 0.135742, top: 0.047852, right: 0.864258, bottom: 0.953125 },
  pagelet: { left: 0.134766, top: 0.088867, right: 0.857422, bottom: 0.867188 },
  relicoon: { left: 0.237305, top: 0.094727, right: 0.760742, bottom: 0.898438 },
  shellio: { left: 0.195312, top: 0.098633, right: 0.804688, bottom: 0.888672 },
  skylo: { left: 0.235352, top: 0.097656, right: 0.760742, bottom: 0.897461 },
  steppling: { left: 0.261719, top: 0.084961, right: 0.740234, bottom: 0.886719 },
  tasklet: { left: 0.271484, top: 0.046875, right: 0.776367, bottom: 0.932617 },
  vesperitt: { left: 0.240234, top: 0.096680, right: 0.749023, bottom: 0.892578 },
};
