/* This file is generated by scripts/generate-egg-avatar-catalog.cjs. Do not edit. */

export const EGG_AVATAR_READY_ASSETS = {
  body: {
    'classic': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/classic.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/classic.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/classic.webp'),
    },
    'moss': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/moss.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/moss.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/moss.webp'),
    },
    'tide': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/tide.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/tide.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/tide.webp'),
    },
    'sunset': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/sunset.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/sunset.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/sunset.webp'),
    },
    'starglow': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/starglow.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/starglow.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/starglow.webp'),
    },
    'frost': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/frost.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/frost.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/frost.webp'),
    },
    'ember': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/ember.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/ember.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/ember.webp'),
    },
    'barista': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/barista.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/barista.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/barista.webp'),
    },
    'robot': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/robot.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/robot.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/robot.webp'),
    },
    'pumpkin': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/pumpkin.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/pumpkin.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/pumpkin.webp'),
    },
    'honeycomb': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/honeycomb.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/honeycomb.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/honeycomb.webp'),
    },
    'strawberry-cream': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/strawberry-cream.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/strawberry-cream.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/strawberry-cream.webp'),
    },
    'blueberry-swirl': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/blueberry-swirl.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/blueberry-swirl.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/blueberry-swirl.webp'),
    },
    'matcha-marble': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/matcha-marble.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/matcha-marble.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/matcha-marble.webp'),
    },
    'wizard-robes': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/wizard-robes.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/wizard-robes.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/wizard-robes.webp'),
    },
    'watermelon': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/watermelon.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/watermelon.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/watermelon.webp'),
    },
    'football-kit': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/football-kit.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/football-kit.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/football-kit.webp'),
    },
    'sunny-raincoat': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/sunny-raincoat.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/sunny-raincoat.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/sunny-raincoat.webp'),
    },
    'knight-tunic': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/knight-tunic.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/knight-tunic.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/knight-tunic.webp'),
    },
    'astronaut-suit': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/astronaut-suit.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/astronaut-suit.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/astronaut-suit.webp'),
    },
    'explorer-vest': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/explorer-vest.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/explorer-vest.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/explorer-vest.webp'),
    },
    'royal-robe': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/royal-robe.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/royal-robe.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/royal-robe.webp'),
    },
    'party-outfit': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/party-outfit.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/party-outfit.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/party-outfit.webp'),
    },
    'sailor-uniform': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/sailor-uniform.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/sailor-uniform.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/sailor-uniform.webp'),
    },
    'chef-apron': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/chef-apron.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/chef-apron.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/chef-apron.webp'),
    },
    'superhero-suit': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/bases/superhero-suit.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/bases/superhero-suit.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/bases/thumbnails/superhero-suit.webp'),
    },
  },
  face: {
    'classic-smile': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/faces/classic-smile.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/faces/classic-smile.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/faces/thumbnails/classic-smile.webp'),
    },
    'happy-squint': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/faces/happy-squint.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/faces/happy-squint.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/faces/thumbnails/happy-squint.webp'),
    },
    'sleepy': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/faces/sleepy.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/faces/sleepy.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/faces/thumbnails/sleepy.webp'),
    },
    'curious': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/faces/curious.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/faces/curious.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/faces/thumbnails/curious.webp'),
    },
    'determined': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/faces/determined.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/faces/determined.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/faces/thumbnails/determined.webp'),
    },
  },
  hat: {
    'moss-sprout': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/hats/moss-sprout.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/hats/moss-sprout.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/hats/thumbnails/moss-sprout.webp'),
    },
    'barista-beret': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/hats/barista-beret.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/hats/barista-beret.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/hats/thumbnails/barista-beret.webp'),
    },
    'pumpkin-vine-crown': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/hats/pumpkin-vine-crown.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/hats/pumpkin-vine-crown.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/hats/thumbnails/pumpkin-vine-crown.webp'),
    },
    'cozy-beanie': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/hats/cozy-beanie.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/hats/cozy-beanie.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/hats/thumbnails/cozy-beanie.webp'),
    },
    'stargazer-hat': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/hats/stargazer-hat.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/hats/stargazer-hat.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/hats/thumbnails/stargazer-hat.webp'),
    },
    'tiny-golden-crown': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/hats/tiny-golden-crown.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/hats/tiny-golden-crown.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/hats/thumbnails/tiny-golden-crown.webp'),
    },
  },
  held: {
    'warm-lantern': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/held/warm-lantern.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/held/warm-lantern.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/held/thumbnails/warm-lantern.webp'),
    },
    'daisy-posy': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/held/daisy-posy.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/held/daisy-posy.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/held/thumbnails/daisy-posy.webp'),
    },
    'tiny-storybook': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/held/tiny-storybook.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/held/tiny-storybook.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/held/thumbnails/tiny-storybook.webp'),
    },
    'star-wand': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/held/star-wand.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/held/star-wand.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/held/thumbnails/star-wand.webp'),
    },
    'cozy-mug': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/held/cozy-mug.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/held/cozy-mug.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/held/thumbnails/cozy-mug.webp'),
    },
    'adventure-pennant': {
      highResolutionSource: require('../assets/images/katchimeras/egg-avatars/held/adventure-pennant.png'),
      fullSource: require('../assets/images/katchimeras/egg-avatars/held/adventure-pennant.webp'),
      thumbnailSource: require('../assets/images/katchimeras/egg-avatars/held/thumbnails/adventure-pennant.webp'),
    },
  },
} as const;
