// Generated by scripts/generate-game-hub-art.py promote.
export const GAME_HUB_ART_SOURCES: Readonly<Record<string, number>> = {
  'quest-tasklet-desk-jam': require('../assets/images/katchimeras/game-hub/tasklet-desk-jam.webp'),
  'quest-cheerlet-block-party': require('../assets/images/katchimeras/game-hub/cheerlet-block-party.webp'),
};

export function gameHubArtSource(questId: string): number | null {
  return GAME_HUB_ART_SOURCES[questId] ?? null;
}
