import type { DayPromptDefinition } from '@/constants/day-prompts';

// Retrospective prompts unique to Hatch-Your-Past — same chip format as the live
// app (so it still teaches the loop), but worded about the days already lived.
// One at a time, each answer flies into the egg and its seed steers a first hatch.
export const hatchPastPrompts: DayPromptDefinition[] = [
  {
    id: 'feeling',
    title: 'How have the last few days felt?',
    categoryIcon: 'face.smiling',
    dayparts: ['evening'],
    maxOptions: 3,
    launchEnabled: true,
    options: [
      {
        id: 'good',
        label: 'Good',
        emoji: 'Good',
        icon: 'sun.max.fill',
        semanticTags: ['recap:good'],
        scoreBias: { calm: 0.12, energy: 0.08 },
        encounterSeedBias: [{ seedId: 'well_rested', intensity: 0.34 }],
      },
      {
        id: 'mixed',
        label: 'A mixed bag',
        emoji: 'Mixed',
        icon: 'cloud.fill',
        semanticTags: ['recap:mixed'],
        scoreBias: { calm: 0.06 },
      },
      {
        id: 'tough',
        label: 'Tough',
        emoji: 'Tough',
        icon: 'cloud.rain.fill',
        semanticTags: ['recap:tough', 'tender_day'],
        scoreBias: { calm: 0.18 },
        encounterSeedBias: [{ seedId: 'tender_day', intensity: 0.36 }],
      },
    ],
  },
  {
    id: 'activity',
    title: 'What filled them most?',
    categoryIcon: 'figure.walk',
    dayparts: ['evening'],
    maxOptions: 8,
    launchEnabled: true,
    options: [
      {
        id: 'coffee',
        label: 'Coffee runs',
        emoji: 'Coffee',
        icon: 'cup.and.saucer.fill',
        semanticTags: ['recap:coffee'],
        scoreBias: { calm: 0.1 },
        encounterSeedBias: [{ seedId: 'coffee_shop', intensity: 0.4 }],
      },
      {
        id: 'outdoors',
        label: 'Outdoors',
        emoji: 'Outdoors',
        icon: 'leaf.fill',
        semanticTags: ['recap:outdoors'],
        scoreBias: { exploration: 0.2, calm: 0.08 },
        encounterSeedBias: [{ seedId: 'park', intensity: 0.38 }],
      },
      {
        id: 'workouts',
        label: 'Workouts',
        emoji: 'Workouts',
        icon: 'dumbbell.fill',
        semanticTags: ['recap:workouts'],
        scoreBias: { energy: 0.3 },
        encounterSeedBias: [{ seedId: 'gym_day', intensity: 0.4 }],
      },
      {
        id: 'people',
        label: 'With people',
        emoji: 'People',
        icon: 'bubble.left.and.bubble.right.fill',
        semanticTags: ['recap:people'],
        scoreBias: { social: 0.26 },
        encounterSeedBias: [{ seedId: 'social_gathering', intensity: 0.4 }],
      },
      {
        id: 'errands',
        label: 'Errands',
        emoji: 'Errands',
        icon: 'cart.fill',
        semanticTags: ['recap:errands'],
        scoreBias: { energy: 0.1, focus: 0.08 },
        encounterSeedBias: [{ seedId: 'errand_loop', intensity: 0.34 }],
      },
      {
        id: 'home',
        label: 'Cozy at home',
        emoji: 'Home',
        icon: 'moon.stars.fill',
        semanticTags: ['recap:home'],
        scoreBias: { calm: 0.24 },
        encounterSeedBias: [{ seedId: 'home_evening', intensity: 0.34 }],
      },
      {
        id: 'food',
        label: 'Good food',
        emoji: 'Food',
        icon: 'fork.knife',
        semanticTags: ['recap:food'],
        scoreBias: { social: 0.08, calm: 0.08 },
        encounterSeedBias: [{ seedId: 'feast', intensity: 0.34 }],
      },
      {
        id: 'making',
        label: 'Making something',
        emoji: 'Making',
        icon: 'paintbrush.fill',
        semanticTags: ['recap:making'],
        scoreBias: { focus: 0.14, exploration: 0.06 },
        encounterSeedBias: [{ seedId: 'creative_day', intensity: 0.4 }],
      },
    ],
  },
  {
    id: 'meaning',
    title: 'Any standout in there?',
    categoryIcon: 'sparkles',
    dayparts: ['evening'],
    maxOptions: 4,
    launchEnabled: true,
    options: [
      {
        id: 'new_place',
        label: 'Somewhere new',
        emoji: 'New',
        icon: 'mappin.and.ellipse',
        semanticTags: ['recap:travel', 'novelty'],
        scoreBias: { exploration: 0.28 },
        encounterSeedBias: [{ seedId: 'travel_day', intensity: 0.4 }],
      },
      {
        id: 'celebration',
        label: 'A celebration',
        emoji: 'Celebration',
        icon: 'party.popper.fill',
        semanticTags: ['recap:celebration'],
        scoreBias: { social: 0.18, energy: 0.08 },
        encounterSeedBias: [{ seedId: 'celebration', intensity: 0.42 }],
      },
      {
        id: 'music',
        label: 'Live music',
        emoji: 'Music',
        icon: 'music.note',
        semanticTags: ['recap:music'],
        scoreBias: { calm: 0.12, energy: 0.06 },
        encounterSeedBias: [{ seedId: 'live_music', intensity: 0.38 }],
      },
      {
        id: 'usual',
        label: 'Just the usual',
        emoji: 'Usual',
        icon: 'moon.stars.fill',
        semanticTags: ['recap:usual'],
        scoreBias: { calm: 0.16 },
        encounterSeedBias: [{ seedId: 'home_evening', intensity: 0.3 }],
      },
    ],
  },
];
