// Generated by scripts/generate-merge-board-atlas.py. Do not hand edit.
export const MERGE_BOARD_ATLAS_SOURCE = require('../assets/images/katchimeras/merge-world/generated/merge-board-atlas.webp');
export const MERGE_BOARD_ATLAS_TILE_SIZE = 128;
export const MERGE_BOARD_ATLAS_WIDTH = 2048;
export const MERGE_BOARD_ATLAS_HEIGHT = 256;
export const MERGE_BOARD_ATLAS_HASH = 'a48b7302fddc55c1';
export const MERGE_BOARD_ATLAS_ENTRIES = {
  '__cell.normal': { x: 0, y: 0, width: 128, height: 128 },
  '__cell.alternate': { x: 128, y: 0, width: 128, height: 128 },
  '__cell.selected': { x: 256, y: 0, width: 128, height: 128 },
  '__cell.compatible': { x: 384, y: 0, width: 128, height: 128 },
  '__cell.invalid': { x: 512, y: 0, width: 128, height: 128 },
  '__cloud.lock': { x: 640, y: 0, width: 128, height: 128 },
  'adventure:trail:1': { x: 768, y: 0, width: 128, height: 128 },
  'adventure:travel:1': { x: 896, y: 0, width: 128, height: 128 },
  'comfort:care:1': { x: 1024, y: 0, width: 128, height: 128 },
  'comfort:rest:1': { x: 1152, y: 0, width: 128, height: 128 },
  'creative:art:1': { x: 1280, y: 0, width: 128, height: 128 },
  'creative:screen:1': { x: 1408, y: 0, width: 128, height: 128 },
  'drink:hot:1': { x: 1536, y: 0, width: 128, height: 128 },
  'drink:refresh:1': { x: 1664, y: 0, width: 128, height: 128 },
  'food:dessert:1': { x: 1792, y: 0, width: 128, height: 128 },
  'food:table:1': { x: 1920, y: 0, width: 128, height: 128 },
  'mind:books:1': { x: 0, y: 128, width: 128, height: 128 },
  'mind:work:1': { x: 128, y: 128, width: 128, height: 128 },
  'nature:garden:1': { x: 256, y: 128, width: 128, height: 128 },
  'nature:garden:2': { x: 384, y: 128, width: 128, height: 128 },
  'nature:garden:3': { x: 512, y: 128, width: 128, height: 128 },
  'nature:garden:4': { x: 640, y: 128, width: 128, height: 128 },
  'nature:garden:5': { x: 768, y: 128, width: 128, height: 128 },
  'nature:waterside:1': { x: 896, y: 128, width: 128, height: 128 },
  'social:celebration:1': { x: 1024, y: 128, width: 128, height: 128 },
  'social:gathering:1': { x: 1152, y: 128, width: 128, height: 128 },
} as const;
export type MergeBoardAtlasEntryId = keyof typeof MERGE_BOARD_ATLAS_ENTRIES;
