// Generated by scripts/generate-exploration-background.py. Do not hand edit.
import type { ImageSourcePropType } from 'react-native';

import type { TodayExplorationBackgroundKey } from '@/constants/today-exploration-background-keys.gen';

export const TODAY_EXPLORATION_BACKGROUND_SOURCES = {
  'home': {
    recyclingKey: 'today-home-exploration-v1',
    source: require('../assets/images/katchimeras/world/backgrounds/home/home-exploration-v1.png'),
  },
  'bedrotte': {
    recyclingKey: 'today-bedrotte-exploration-v1',
    source: require('../assets/images/katchimeras/world/backgrounds/bedrotte-exploration-v1.png'),
  },
  'cheerlet': {
    recyclingKey: 'today-cheerlet-exploration-v1',
    source: require('../assets/images/katchimeras/world/backgrounds/cheerlet-exploration-v1.png'),
  },
  'feastle': {
    recyclingKey: 'today-feastle-exploration-v5',
    source: require('../assets/images/katchimeras/world/backgrounds/feastle-exploration-v5.png'),
  },
  'flickerbun': {
    recyclingKey: 'today-flickerbun-exploration-v1',
    source: require('../assets/images/katchimeras/world/backgrounds/flickerbun-exploration-v1.png'),
  },
  'mossprout': {
    recyclingKey: 'today-mossprout-exploration-v1',
    source: require('../assets/images/katchimeras/world/backgrounds/mossprout-exploration-v1.png'),
  },
  'pagelet': {
    recyclingKey: 'today-pagelet-exploration-v1',
    source: require('../assets/images/katchimeras/world/backgrounds/pagelet-exploration-v1.png'),
  },
  'relicoon': {
    recyclingKey: 'today-relicoon-exploration-v3',
    source: require('../assets/images/katchimeras/world/backgrounds/relicoon-exploration-v3.png'),
  },
  'skylo': {
    recyclingKey: 'today-skylo-exploration-v1',
    source: require('../assets/images/katchimeras/world/backgrounds/skylo-exploration-v1.png'),
  },
  'steppling': {
    recyclingKey: 'today-steppling-exploration-v2',
    source: require('../assets/images/katchimeras/world/backgrounds/steppling-exploration-v2.png'),
  },
  'tasklet': {
    recyclingKey: 'today-tasklet-exploration-v1',
    source: require('../assets/images/katchimeras/world/backgrounds/tasklet-exploration-v1.png'),
  },
} as const satisfies Record<
  TodayExplorationBackgroundKey,
  { recyclingKey: string; source: ImageSourcePropType }
>;
