/* Generated by scripts/generate-today-atmosphere-backgrounds.py. */
import type { ImageSourcePropType } from 'react-native';

import type { DayBackgroundSceneId } from '@/types/home';

export type BundledTodayAtmosphereBackground = {
  id: string;
  source: ImageSourcePropType;
};

export const TODAY_ATMOSPHERE_BACKGROUND_SOURCES: Record<
  DayBackgroundSceneId,
  BundledTodayAtmosphereBackground
> = {
  clear_day: {
    id: "clear-sky-islands-v1",
    source: require('../assets/images/katchimeras/world/today-atmosphere/clear-day.webp'),
  },
  radiant_golden: {
    id: "radiant-golden-sky-v1",
    source: require('../assets/images/katchimeras/world/today-atmosphere/radiant-golden.webp'),
  },
  celebration_connected: {
    id: "celebration-connected-sky-v1",
    source: require('../assets/images/katchimeras/world/today-atmosphere/celebration-connected.webp'),
  },
  garden_bloom: {
    id: "garden-bloom-sky-v1",
    source: require('../assets/images/katchimeras/world/today-atmosphere/garden-bloom.webp'),
  },
  autumn_hearth: {
    id: "autumn-hearth-sky-v1",
    source: require('../assets/images/katchimeras/world/today-atmosphere/autumn-hearth.webp'),
  },
  twilight_reflective: {
    id: "twilight-reflective-sky-v1",
    source: require('../assets/images/katchimeras/world/today-atmosphere/twilight-reflective.webp'),
  },
  inspired_journey: {
    id: "inspired-journey-sky-v1",
    source: require('../assets/images/katchimeras/world/today-atmosphere/inspired-journey.webp'),
  },
  rain_overcast: {
    id: "rain-overcast-sky-v1",
    source: require('../assets/images/katchimeras/world/today-atmosphere/rain-overcast.webp'),
  },
  mist_cold: {
    id: "mist-cold-sky-v1",
    source: require('../assets/images/katchimeras/world/today-atmosphere/mist-cold.webp'),
  },
  storm: {
    id: "storm-sky-v1",
    source: require('../assets/images/katchimeras/world/today-atmosphere/storm.webp'),
  },
};
