#!/usr/bin/env python3
"""Publish optional hatchling cutouts and their runtime LOD manifest.

Species-specific files live at ``assets/images/katchimeras/hatchlings/<visual-key>``.
Until Mossprout gets a separately named export, the approved project base
``base-hatchling-v2.png`` is intentionally aliased to it. Missing keys are not
emitted: the runtime resolver then falls back to the regular creature cutout.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
HOME_TYPES = ROOT / "types" / "home.ts"
HATCHLING_ROOT = ROOT / "assets" / "images" / "katchimeras" / "hatchlings"
LOD_ROOT = ROOT / "assets" / "images" / "katchimeras" / "hatchlings_lod"
MANIFEST = ROOT / "constants" / "creature-hatchling-sources.gen.ts"

# The approved v2 base is Mossprout's stage-one art for the current experiment.
# A future ``mossprout.png`` in HATCHLING_ROOT automatically supersedes it.
SOURCE_ALIASES = {
    "mossprout": HATCHLING_ROOT / "base-hatchling-v2.png",
}


def visual_keys() -> set[str]:
    source = HOME_TYPES.read_text(encoding="utf-8")
    match = re.search(r"export type HomeVisualKey\s*=\s*(.*?);", source, re.DOTALL)
    if not match:
        raise RuntimeError("Could not parse HomeVisualKey from types/home.ts")
    return set(re.findall(r"'([^']+)'", match.group(1)))


def hatchling_sources() -> dict[str, Path]:
    keys = visual_keys()
    sources: dict[str, Path] = {}
    for path in sorted(HATCHLING_ROOT.iterdir()):
        if path.is_file() and path.suffix.lower() in {".png", ".webp"} and path.stem in keys:
            sources[path.stem] = path
    for key, path in SOURCE_ALIASES.items():
        if key in keys and key not in sources and path.exists():
            sources[key] = path
    return sources


def make_lod(source: Path, key: str, max_dim: int, quality: int) -> Path:
    target = LOD_ROOT / f"{key}_{max_dim}.webp"
    with Image.open(source) as image:
        converted = image.convert("RGBA")
        converted.thumbnail((max_dim, max_dim), Image.Resampling.LANCZOS)
        converted.save(target, "WEBP", quality=quality, alpha_quality=100, method=6)
    return target


def require_path(path: Path) -> str:
    return f"../{path.relative_to(ROOT).as_posix()}"


def write_manifest(
    full: dict[str, Path],
    medium: dict[str, Path],
    thumb: dict[str, Path],
) -> None:
    def block(entries: dict[str, Path]) -> str:
        return "\n".join(
            f"    {key}: require('{require_path(path)}'),"
            for key, path in sorted(entries.items())
        )

    MANIFEST.write_text(
        "\n".join(
            [
                "// Generated by scripts/generate-hatchling-lod.py. Do not hand edit.",
                "import type { ImageSourcePropType } from 'react-native';",
                "import type { HomeVisualKey } from '@/types/home';",
                "",
                "export type CreatureHatchlingLod = 'full' | 'medium' | 'thumb';",
                "",
                "export const CREATURE_HATCHLING_SOURCES: Record<CreatureHatchlingLod, Partial<Record<HomeVisualKey, ImageSourcePropType>>> = {",
                "  full: {",
                block(full),
                "  },",
                "  medium: {",
                block(medium),
                "  },",
                "  thumb: {",
                block(thumb),
                "  },",
                "};",
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--medium", type=int, default=512)
    parser.add_argument("--thumb", type=int, default=256)
    parser.add_argument("--quality", type=int, default=88)
    parser.add_argument("--report-only", action="store_true")
    args = parser.parse_args()

    sources = hatchling_sources()
    print(f"Published hatchlings: {len(sources)}")
    for key, path in sources.items():
        with Image.open(path) as image:
            print(f"  {key:<16} {image.width}x{image.height}  {path.relative_to(ROOT)}")

    if args.report_only:
        return

    LOD_ROOT.mkdir(parents=True, exist_ok=True)
    for stale in LOD_ROOT.glob("*.webp"):
        stale.unlink()

    medium = {
        key: make_lod(path, key, args.medium, args.quality)
        for key, path in sources.items()
    }
    thumb = {
        key: make_lod(path, key, args.thumb, args.quality)
        for key, path in sources.items()
    }
    write_manifest(sources, medium, thumb)
    print(f"Wrote {MANIFEST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
