#!/usr/bin/env python3
"""Generate the board-resolution Merge sprite atlas and typed manifest."""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
ART_SOURCE = ROOT / "constants" / "merge-world-art.ts"
CATALOG_SOURCE = ROOT / "constants" / "merge-world-catalog.ts"
ATLAS_PATH = ROOT / "assets" / "images" / "katchimeras" / "merge-world" / "generated" / "merge-board-atlas.webp"
MANIFEST_PATH = ROOT / "constants" / "merge-board-atlas.generated.ts"
TILE = 128
COLS = 16

CELL_TILES = {
    "__cell.normal": ((242, 223, 184, 255), (150, 104, 51, 87)),
    "__cell.alternate": ((236, 212, 167, 255), (150, 104, 51, 87)),
    "__cell.selected": ((255, 233, 173, 255), (198, 126, 44, 255)),
    "__cell.compatible": ((241, 217, 149, 255), (209, 145, 53, 255)),
    "__cell.invalid": ((242, 223, 184, 255), (217, 94, 75, 255)),
}


def item_sources() -> dict[str, Path]:
    text = ART_SOURCE.read_text(encoding="utf-8")
    block = text.split("export const MERGE_WORLD_ITEM_ART = {", 1)[1].split("} as const;", 1)[0]
    entries: dict[str, Path] = {}
    pattern = re.compile(r"\s*'([^']+)'\s*:\s*require\('([^']+)'\)")
    for definition_id, relative in pattern.findall(block):
        entries[definition_id] = (ART_SOURCE.parent / relative).resolve()
    return entries


def static_item_ids() -> list[str]:
    """Return only artwork that can appear underneath the interactive layer."""
    text = CATALOG_SOURCE.read_text(encoding="utf-8")
    moss_block = text.split("export const MOSSPROUT_DREAM_ECHOES = [", 1)[1].split("] as const;", 1)[0]
    ids = set(re.findall(r"definitionId:\s*'([^']+)'", moss_block))
    generator_block = text.split("export const MERGE_GENERATORS:", 1)[1].split("];", 1)[0]
    for first_chain, second_chain in re.findall(r"\['([^']+)',\s*'([^']+)'\]", generator_block):
        ids.add(f"{first_chain}:1")
        ids.add(f"{second_chain}:1")
    return sorted(ids)


def cell_tile(colors: tuple[tuple[int, int, int, int], tuple[int, int, int, int]]) -> Image.Image:
    color, border = colors
    image = Image.new("RGBA", (TILE, TILE), color)
    pixels = image.load()
    for y in range(12):
        alpha = int(87 * (1 - y / 12))
        for x in range(TILE):
            base = pixels[x, y]
            pixels[x, y] = tuple(int(base[i] * (1 - alpha / 255) + 255 * alpha / 255) for i in range(3)) + (255,)
    shade = (101, 65, 25)
    for offset in range(16):
        y = TILE - 1 - offset
        alpha = int(30 * (1 - offset / 16))
        for x in range(TILE):
            base = pixels[x, y]
            pixels[x, y] = tuple(int(base[i] * (1 - alpha / 255) + shade[i] * alpha / 255) for i in range(3)) + (255,)
    draw = ImageDraw.Draw(image)
    draw.rectangle((0, 0, TILE - 1, TILE - 1), outline=border, width=3)
    return image


def resized_art(path: Path) -> Image.Image:
    with Image.open(path) as source:
        return source.convert("RGBA").resize((TILE, TILE), Image.Resampling.LANCZOS)


def build() -> tuple[bytes, str]:
    sources = item_sources()
    static_ids = static_item_ids()
    missing = [definition_id for definition_id in static_ids if definition_id not in sources]
    if missing:
        raise RuntimeError(f"Missing Merge artwork for static atlas entries: {', '.join(missing)}")
    keys = [*CELL_TILES.keys(), "__cloud.lock", *static_ids]
    rows = (len(keys) + COLS - 1) // COLS
    atlas = Image.new("RGBA", (COLS * TILE, rows * TILE), (0, 0, 0, 0))
    entries: dict[str, tuple[int, int]] = {}
    cloud = ROOT / "assets" / "images" / "katchimeras" / "merge-world" / "locked" / "cloud-lock.webp"
    for index, key in enumerate(keys):
        x = (index % COLS) * TILE
        y = (index // COLS) * TILE
        if key in CELL_TILES:
            tile = cell_tile(CELL_TILES[key])
        elif key == "__cloud.lock":
            tile = resized_art(cloud)
        else:
            tile = resized_art(sources[key])
        atlas.alpha_composite(tile, (x, y))
        entries[key] = (x, y)

    import io
    buffer = io.BytesIO()
    atlas.save(buffer, "WEBP", lossless=True, method=6)
    atlas_bytes = buffer.getvalue()
    digest = hashlib.sha256(atlas_bytes).hexdigest()[:16]
    lines = [
        "// Generated by scripts/generate-merge-board-atlas.py. Do not hand edit.",
        "export const MERGE_BOARD_ATLAS_SOURCE = require('../assets/images/katchimeras/merge-world/generated/merge-board-atlas.webp');",
        f"export const MERGE_BOARD_ATLAS_TILE_SIZE = {TILE};",
        f"export const MERGE_BOARD_ATLAS_WIDTH = {atlas.width};",
        f"export const MERGE_BOARD_ATLAS_HEIGHT = {atlas.height};",
        f"export const MERGE_BOARD_ATLAS_HASH = '{digest}';",
        "export const MERGE_BOARD_ATLAS_ENTRIES = {",
    ]
    for key, (x, y) in entries.items():
        lines.append(f"  {key!r}: {{ x: {x}, y: {y}, width: {TILE}, height: {TILE} }},")
    lines.extend([
        "} as const;",
        "export type MergeBoardAtlasEntryId = keyof typeof MERGE_BOARD_ATLAS_ENTRIES;",
        "",
    ])
    return atlas_bytes, "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    atlas_bytes, manifest = build()
    if args.check:
        current_atlas = ATLAS_PATH.read_bytes() if ATLAS_PATH.exists() else b""
        current_manifest = MANIFEST_PATH.read_text(encoding="utf-8") if MANIFEST_PATH.exists() else ""
        if current_atlas != atlas_bytes or current_manifest != manifest:
            print("Merge board atlas is stale. Run npm run art:merge-board-atlas")
            return 1
        print("Merge board atlas is current")
        return 0
    ATLAS_PATH.parent.mkdir(parents=True, exist_ok=True)
    ATLAS_PATH.write_bytes(atlas_bytes)
    MANIFEST_PATH.write_text(manifest, encoding="utf-8", newline="\n")
    print(f"Wrote {ATLAS_PATH.relative_to(ROOT)} ({len(atlas_bytes) / 1024:.1f} KB)")
    print(f"Wrote {MANIFEST_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
