import fs from 'node:fs';
import path from 'node:path';

import { JOURNAL_CLASSIFICATION_CATALOG } from '../utils/journal-classification-catalog';

const root = path.join(import.meta.dirname, '..');
const outputPath = path.join(root, 'modules', 'katchimera-foundation', 'ios', 'JournalNoteRoute.generated.swift');
const routeValues = [...JOURNAL_CLASSIFICATION_CATALOG.map((entry) => entry.routeKey), 'ambiguous'];
const flowValues = [...new Set(JOURNAL_CLASSIFICATION_CATALOG.map((entry) => entry.flowId))];

function swiftString(value: string): string {
  return JSON.stringify(value).replaceAll('\\/', '/');
}

const taxonomy = JOURNAL_CLASSIFICATION_CATALOG.map((entry) => {
  const examples = entry.examples.map((example) => `“${example}”`).join('; ');
  const exclusions = entry.exclusions.length ? ` Not: ${entry.exclusions.join('; ')}.` : '';
  return `${entry.routeKey}: ${entry.definition} Examples: ${examples}.${exclusions}`;
}).join('\n');

const allowed = routeValues.map(swiftString).join(', ');
const allowedAlternative = ['', ...routeValues].map(swiftString).join(', ');
const allowedFlows = ['', ...flowValues].map(swiftString).join(', ');
const swiftRouteValues = routeValues.filter((value) => value !== 'ambiguous').map(swiftString).join(', ');
const source = `// Generated by scripts/generate-note-route-schema.ts. Do not edit by hand.
#if canImport(FoundationModels)
import FoundationModels

@available(iOS 26.0, *)
enum JournalNoteRouteCatalog {
  static let schemaVersion = "5"
  static let photoSchemaVersion = "13"
  static let routeKeys: Set<String> = [${swiftRouteValues}]
  static let promptTaxonomy = """
${taxonomy}
"""
}

@available(iOS 26.0, *)
@Generable
struct NoteRouteDecision {
  @Guide(description: "The single best atomic journal route, or ambiguous only when no route clearly leads", .anyOf([${allowed}]))
  let routeKey: String

  @Guide(description: "The second plausible atomic journal route, or empty when there is no close alternative", .anyOf([${allowedAlternative}]))
  let alternativeRouteKey: String

  @Guide(description: "Confidence that routeKey is the best destination", .range(0.0...1.0))
  let routeConfidence: Double

  @Guide(description: "Confidence in alternativeRouteKey, or zero when it is empty", .range(0.0...1.0))
  let alternativeRouteConfidence: Double

  @Guide(description: "A concise specific person, place, activity, food, work, project, or event explicitly supported by the note; otherwise empty")
  let specific: String
}

@available(iOS 26.0, *)
@Generable
struct PhotoJournalCandidateDecision {
  @Guide(description: "Zero-based index of the best candidate", .range(0...127))
  let candidateIndex: Int
  @Guide(description: "Score for the best candidate", .range(0.0...1.0))
  let candidateScore: Double
  @Guide(description: "Zero-based index of the second candidate, or -1", .range(-1...127))
  let alternativeIndex: Int
  @Guide(description: "Score for the second candidate or zero", .range(0.0...1.0))
  let alternativeScore: Double
  @Guide(description: "Zero-based index of the third candidate, or -1", .range(-1...127))
  let thirdIndex: Int
  @Guide(description: "Score for the third candidate or zero", .range(0.0...1.0))
  let thirdScore: Double
  @Guide(description: "A visual-only 2-5 word subject")
  let visualSubject: String
}

@available(iOS 26.0, *)
@Generable
struct NoteRead {
  @Guide(description: "A short warm 2-4 word title for the moment under 24 characters, with no punctuation, emoji, or quotes")
  let title: String

  @Guide(description: "The dominant feeling of the note", .anyOf(["calm", "energy", "together", "meaningful"]))
  let feeling: String

  @Guide(description: "The consumed media kind; other covers watched sport, news, podcasts, livestreams, and other formats; otherwise none", .anyOf(["none", "book", "film", "show", "game", "music", "art", "other"]))
  let mediaKind: String

  @Guide(description: "The mentioned work's full official title when confidently known, otherwise empty")
  let mediaTitle: String

  @Guide(description: "The work's author, director, or artist when confidently known, otherwise empty")
  let mediaCreator: String

  @Guide(description: "A short dish or drink name when the note is about eating or drinking, otherwise empty")
  let food: String
}
#endif
`;

if (process.argv.includes('--check')) {
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf8') : '';
  if (current !== source) {
    console.error('JournalNoteRoute.generated.swift is out of date. Run npx tsx scripts/generate-note-route-schema.ts.');
    process.exit(1);
  }
  console.log(`Journal note route schema is current (${JOURNAL_CLASSIFICATION_CATALOG.length} routes).`);
} else {
  fs.writeFileSync(outputPath, source);
  console.log(`Generated ${path.relative(root, outputPath)} with ${JOURNAL_CLASSIFICATION_CATALOG.length} routes.`);
}
