"""Generate deterministic visible-pixel bounds for bundled Kingdom hex tiles.

Only full 1024px WebPs are measured. LODs are resized from the same square
canvas and intentionally reuse the full asset's world-space frame.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
HEX_DIR = ROOT / "assets" / "images" / "katchimeras" / "world" / "hex"
OUTPUT = ROOT / "constants" / "kingdom-hex-tile-bounds.gen.ts"
ALPHA_THRESHOLD = 16
ASSET_SIZE = 1024


def is_full_hex_tile(path: Path) -> bool:
    return (
        path.suffix.lower() == ".webp"
        and "hex_tile" in path.stem
        and not path.stem.endswith(("_256", "_512"))
    )


def measure(path: Path) -> tuple[int, int, int, int]:
    with Image.open(path) as image:
        rgba = image.convert("RGBA")
        if rgba.size != (ASSET_SIZE, ASSET_SIZE):
            raise ValueError(f"{path.name}: expected {ASSET_SIZE}x{ASSET_SIZE}, received {rgba.size}")
        visible = rgba.getchannel("A").point(lambda alpha: 255 if alpha >= ALPHA_THRESHOLD else 0)
        bounds = visible.getbbox()
    if bounds is None:
        raise ValueError(f"{path.name}: no pixels meet alpha threshold {ALPHA_THRESHOLD}")
    left, top, right, bottom = bounds
    if right <= left or bottom <= top:
        raise ValueError(f"{path.name}: invalid bounds {bounds}")
    return bounds


def render(entries: list[tuple[str, tuple[int, int, int, int]]]) -> str:
    lines = [
        "// Generated by scripts/generate-hex-tile-bounds.py. Do not edit by hand.",
        f"export const KINGDOM_HEX_TILE_ALPHA_THRESHOLD = {ALPHA_THRESHOLD};",
        "",
        "export const KINGDOM_HEX_TILE_ALPHA_BOUNDS = {",
    ]
    for name, (left, top, right, bottom) in entries:
        lines.append(
            f"  '{name}': {{ left: {left}, top: {top}, right: {right}, bottom: {bottom} }},"
        )
    lines.extend(["} as const;", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when the checked-in manifest is stale.")
    args = parser.parse_args()

    assets = sorted((path for path in HEX_DIR.glob("*.webp") if is_full_hex_tile(path)), key=lambda path: path.name)
    if not assets:
        raise SystemExit("No full hex tile WebPs found.")

    try:
        content = render([(path.name, measure(path)) for path in assets])
    except ValueError as error:
        raise SystemExit(str(error)) from error

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            print("Hex tile bounds manifest is stale. Run: python scripts/generate-hex-tile-bounds.py")
            raise SystemExit(1)
        print(f"Hex tile bounds verified for {len(assets)} assets.")
        return

    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} for {len(assets)} assets.")


if __name__ == "__main__":
    main()
