/** @type {import('@bacons/apple-targets').Config} */
module.exports = {
  type: 'widget',
  name: 'KatchimeraWidget',
  displayName: 'Katchimeras',
  deploymentTarget: '17.0',
  bundleIdentifier: '.widget',
  colors: {
    $accent: '#FFC36B',
    ink: '#0C0A14',
  },
  images: {
    "egg": "../../assets/images/katchimeras/cutouts/egg-base.png",
    "voltstep": "../../assets/images/katchimeras/cutouts/voltstep.png",
    "hearthsip": "../../assets/images/katchimeras/cutouts/hearthsip.png",
    "glimmuse": "../../assets/images/katchimeras/cutouts/glimmuse.png",
    "skysette": "../../assets/images/katchimeras/cutouts/skysette.png",
    "creamalume": "../../assets/images/katchimeras/cutouts/creamalume.png",
    "gatherglow": "../../assets/images/katchimeras/cutouts/gatherglow.png",
    "mossprout": "../../assets/images/katchimeras/cutouts/mossprout.png",
    "lattelet": "../../assets/images/katchimeras/cutouts/lattelet.png",
    "sprintail": "../../assets/images/katchimeras/cutouts/sprintail.png",
    "neonpoko": "../../assets/images/katchimeras/cutouts/neonpoko.png",
    "crumbun": "../../assets/images/katchimeras/cutouts/crumbun.png",
    "hayhorn": "../../assets/images/katchimeras/cutouts/hayhorn.png",
    "ironette": "../../assets/images/katchimeras/cutouts/ironette.png",
    "bedrotte": "../../assets/images/katchimeras/cutouts/bedrotte.png",
    "steppling": "../../assets/images/katchimeras/cutouts/steppling.png",
    "errandimp": "../../assets/images/katchimeras/cutouts/errandimp.png",
    "quietome": "../../assets/images/katchimeras/cutouts/quietome.png",
    "relicoon": "../../assets/images/katchimeras/cutouts/relicoon.png",
    "shellio": "../../assets/images/katchimeras/cutouts/shellio.png",
    "flickerbun": "../../assets/images/katchimeras/cutouts/flickerbun.png",
    "baristabbit": "../../assets/images/katchimeras/cutouts/baristabbit.png",
    "pulsepounce": "../../assets/images/katchimeras/cutouts/hayhorn.png"
},
  entitlements: {
    'com.apple.security.application-groups': ['group.com.daruk.katchimeras'],
  },
};
